### ISSUE TITLE
[STDOUT] HOTSWAP AGENT: 17:25:59.934 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.proxy.ProxyPlugin' class ~

### ISSUE THREAD

**Issue by funsterisdafunniest** [HotswapProjects/HotswapAgent#102]
Getting this error after migrating my development project to new machine.

Environment : 
imac late 2013, el capitan with all updates installed
jdk 7u79 with dcevm (the latest dcevm light for java 7 that i can find) + hotswap agetn 0.3
Netbeans IDE 8.1
Jboss 5.1.0 GA (still need to use it since my workplace uses it)
disabledplugin on the hotswap : hibernate (since obviously, since it's jboss 5, we're still using hibernate 3, which is not supported)
the project structure is
App.ear
--App.war
--App.ejb

the exception thrown everytime i save a file while debugging is as follow

```
17:25:59,934 INFO  [STDOUT] HOTSWAP AGENT: 17:25:59.934 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.proxy.ProxyPlugin' class '--edited--'.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:157)
    at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
    at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
Caused by: java.lang.IllegalStateException: BaseClassLoader@6740931a{vfszip:/--edited--} classLoader is not connected to a domain (probably undeployed?) for class java.io.ByteArrayInputStream
    at org.jboss.classloader.spi.base.BaseClassLoader.loadClassFromDomain(BaseClassLoader.java:793)
    at org.jboss.classloader.spi.base.BaseClassLoader.loadClass(BaseClassLoader.java:441)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2499)
    at java.lang.Class.getField0(Class.java:2804)
    at java.lang.Class.getField(Class.java:1582)
    at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParamsMap(GeneratorParametersTransformer.java:83)
    at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParams(GeneratorParametersTransformer.java:111)
    at org.hotswap.agent.plugin.proxy.ProxyPlugin.transformCglibProxy(ProxyPlugin.java:75)
    ... 9 more
```

which is strange, since java.io.ByteArrayInputStream does not need classloader right? or am i wrong?

**Comment by skybber** [comment]
It looks hotswap agent's Proxy plugin has a problem under some circumstances. Try to disable Proxy plugin in the same way you disabled the Hibernate plugin. Belive it doesn't have any consequences.

**Comment by funsterisdafunniest** [comment]
that's also one of the problem, i don't know how to disable two plugin, i disabled it with -javaagent:/Users/Funster/PrivateLib/hotswap/hotswap-agent.jar=disablePlugin=hibernate

i didn't know how to disable the second one.

**Comment by skybber** [comment]
look at "Quick Start" / "Run your application" in Readme.md. Btw. if you have some configuration problem please ask at https://groups.google.com/forum/#!forum/hotswapagent . Thanks.

**Comment by funsterisdafunniest** [comment]
thanks! one more question though. where should i put this properties file? should i put it in the resource folder inside the .ear project? (since that project contains all the other ones)

**Comment by funsterisdafunniest** [comment]
nevermind, found how to disable it in jvm commandline,
for anyone who's wondering to disable multiple plugins too,here's how
-javaagent:/location_of_hotswap_agent/hotswap-agent.jar=disablePlugin=hibernate,disablePlugin=proxy

**Comment by skybber** [comment]
Put into WEB-INF/classes/ of your web project.

**Comment by funsterisdafunniest** [comment]
hi @skybber  did you reopened this to find out what's the problem with the proxy plugin? What does that plugin does anyway? the documentation link on the main hotswap site leads to 404 to me.. want to help if i can.

**Comment by skybber** [comment]
It looks there is a problem in the Proxy plugin but not critical one. You needn't bother about it if you don't change proxied class. Proxy plugin was done by @erkieh as a port of his own agent https://github.com/erkieh/proxyhotswap

**Comment by erkieh** [comment]
The proxy plugin regenerates dynamic proxying classes that are created at runtime. 
In this case the JBoss classloader seems to do some additional checks that I have not taken into account.

**Comment by skybber** [comment]
Fixed by change of proxy reloading to deferred one.
