### ISSUE TITLE
Errors with snapshot version on JBoss EAP

### ISSUE THREAD

**Issue by hvico** [HotswapProjects/HotswapAgent#111]
Hello, 

I've trying to setup hotswap agent for a project, which is a MAVEN multi-module EAR project (JSF/PrimeFaces, Hibernate, Weld, patched JRE 1.7.0u79, and the IDE is Eclipse). The ear is deployed on JBoss EAP 6.3 (JBoss AS 7).

I specified the "target" output directories in Eclipse as extraClasspath in hotswap-agent.properties in order to override the classes bundled at the EAR.

Using the stable version (0.3) of hotswap-agent I get classloader errors, the ones reported at [this issue](https://github.com/HotswapProjects/HotswapAgent/issues/101).

Using the latest snapshot I get other sort of errors deploying the app. These are:

(after JBossModulesPlugin initialization)
InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.weld.WeldPlugin' class 'org/jboss/weld/bean/proxy/ProxyFactory'.

Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] no such field: beanArchiveType
at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:841)
at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:759)
at org.hotswap.agent.plugin.weld.BeanDeploymentArchiveTransformer.transformJbossBda(BeanDeploymentArchiveTransformer.java:80)

 HHH000274: Unable to apply constraints on DDL for: com.somecompany.SomeEntity java.lang.IllegalArgumentException: Plugin not found in the registry org.hotswap.agent.plugin.hibernate.HibernatePlugin@3ecc25ad

(after Hibernate plugin initialization which occurs much later than the previous error)
 InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.weld.WeldPlugin' class 'org/jboss/as/weld/deployment/BeanDeploymentArchiveImpl'.
.....
Caused by: org.hotswap.agent.javassist.NotFoundException: no such constructor
at org.hotswap.agent.javassist.CtClass.getConstructor(CtClass.java:883)

Thanks,

**Comment by skybber** [comment]
You have probably unsupported version of Weld. WeldPlugin supports versions >8.x.

**Comment by mallorygiles** [comment]
Which versions of Weld are supported? I thought that Weld is only at version 3.

**Comment by skybber** [comment]
Look at
https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-weld-plugin/run-tests.sh
. But I didn't check the v3.0 till now.

2017-08-09 14:42 GMT+02:00 mallorygiles <notifications@github.com>:
