### ISSUE TITLE
Reloading @Stateless bean fails in WeldPlugin

### ISSUE THREAD

**Issue by skybber** [HotswapProjects/HotswapAgent#112]
15:45:14,951 INFO  [stdout](Thread-341) java.lang.reflect.InvocationTargetException
15:45:14,951 INFO  [stdout](Thread-341)    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:45:14,951 INFO  [stdout](Thread-341)    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:45:14,951 INFO  [stdout](Thread-341)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:45:14,951 INFO  [stdout](Thread-341)    at java.lang.reflect.Method.invoke(Method.java:497)
15:45:14,951 INFO  [stdout](Thread-341)    at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.executeCommand(BeanClassRefreshCommand.java:73)
15:45:14,951 INFO  [stdout](Thread-341)    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
15:45:14,951 INFO  [stdout](Thread-341) Caused by: java.lang.IllegalStateException: JBAS016071: Singleton not set for ModuleClassLoader for Module "deployment.mytest.war:main" from Service Module Loader. This means that you are trying to access a weld deployment with a Thread Context ClassLoader that is not associated with the deployment.
15:45:14,951 INFO  [stdout](Thread-341)    at org.jboss.as.weld.services.ModuleGroupSingletonProvider$TCCLSingleton.get(ModuleGroupSingletonProvider.java:77)
15:45:14,951 INFO  [stdout](Thread-341)    at org.jboss.as.weld.services.ModuleGroupSingletonProvider$TCCLSingleton.get(ModuleGroupSingletonProvider.java:134)
15:45:14,951 INFO  [stdout](Thread-341)    at org.jboss.weld.Container.instance(Container.java:55)
15:45:14,951 INFO  [stdout](Thread-341)    at org.jboss.as.weld.WeldProvider.getCDI(WeldProvider.java:61)
15:45:14,951 INFO  [stdout](Thread-341)    at javax.enterprise.inject.spi.CDI.current(CDI.java:60)
15:45:14,951 INFO  [stdout](Thread-341)    at org.hotswap.agent.plugin.weld.command.BeanDeploymentArchiveAgent.reloadBean(BeanDeploymentArchiveAgent.java:179)
15:45:14,951 INFO  [stdout](Thread-341)    at org.hotswap.agent.plugin.weld.command.BeanDeploymentArchiveAgent.refreshBeanClass(BeanDeploymentArchiveAgent.java:157)
15:45:14,951 INFO  [stdout](Thread-341)    ... 6 more

**Comment by spike-rabbit** [comment]
Hi,
I am facing this issue right now.
What was the solution or reason for closing this issue?

**Comment by skybber** [comment]
What weld version and technology stack are you using?

**Comment by spike-rabbit** [comment]
Server: JBoss EAP 7.1.6
Weld version: 2.4.3.Final-redhat-1
Multi Maven Project:

- JAX-RS Webservices which are @Stateless (bundled as war)
- @Transactional CDI Beans using hibernate (bundled as jar)
- ear (including war and jar)

IntelliJ Ultimate (latest) is used for development

The error from above is thrown several times on a single class reload. Doesnt't matter which class.
Error code: WFLYWELD0039

Directly before the error is thrown hotswap agent logs that PurgeWildFlyBeanELResolverCacheCommand - Cleaning BeanPropertiesCache <changed class> ModuleClassLoader for Module "not the module of the changed class"

**Comment by skybber** [comment]
Jersey or RestEasy? (jersy could use hk2-weld bridge)

**Comment by spike-rabbit** [comment]
RestEasy

**Comment by TranThanhHuy-pixels-aavn** [comment]
I'm facing the same issue 

10:24:59,104 INFO  [stdout] (Thread-979) HOTSWAP AGENT: 10:24:59.104 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService] (autoHotswap)
10:24:59,105 INFO  [stdout] (Thread-980) HOTSWAP AGENT: 10:24:59.104 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService] (autoHotswap)
10:24:59,105 INFO  [stdout] (Thread-981) HOTSWAP AGENT: 10:24:59.105 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService] (autoHotswap)
10:24:59,105 INFO  [stdout] (Thread-982) HOTSWAP AGENT: 10:24:59.105 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService] (autoHotswap)
[945.565s][info][redefine,class,load ] redefined name=com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService, count=9 (avail_mem=4616996K)
[945.565s][info][redefine,class,load ] redefined name=com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService$Proxy$_$$_Weld$EnterpriseProxy$, count=9 (avail_mem=4616988K)
[945.565s][info][redefine,class,load ] redefined name=com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService$$$view1152, count=9 (avail_mem=4616984K)
[946.666s][info][redefine,class,timer] vm_op: all=1162  prologue=62  doit=1100
[946.666s][info][redefine,class,timer] doit: heap iterate=662  fullgc=0
10:25:00,283 INFO  [stdout] (Thread-984) HOTSWAP AGENT: 10:25:00.281 INFO (org.hotswap.agent.plugin.wildfly.el.PurgeWildFlyBeanELResolverCacheCommand) - Cleaning  BeanPropertiesCache com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService ModuleClassLoader for Module "deployment.luz_doc_manager.war" from Service Module Loader.
10:25:00,318 INFO  [stdout] (Thread-985) HOTSWAP AGENT: 10:25:00.283 ERROR (org.hotswap.agent.plugin.jvm.ClassInitPlugin) - Error initializing redefined class com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService
10:25:00,319 INFO  [stdout] (Thread-985) java.lang.reflect.InvocationTargetException
10:25:00,320 INFO  [stdout] (Thread-985)        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:25:00,320 INFO  [stdout] (Thread-985)        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:25:00,321 INFO  [stdout] (Thread-985)        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:25:00,321 INFO  [stdout] (Thread-985)        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
10:25:00,322 INFO  [stdout] (Thread-985)        at org.hotswap.agent.plugin.jvm.ClassInitPlugin$2.executeCommand(ClassInitPlugin.java:130)
10:25:00,322 INFO  [stdout] (Thread-985)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
10:25:00,323 INFO  [stdout] (Thread-985) Caused by: java.lang.IllegalAccessError: Update to static final field com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService.logger attempted from a different method ($$ha$clinit) than the initializer method <clinit>
10:25:00,324 INFO  [stdout] (Thread-985)        at deployment.luz_compensation.war//com.axonivy.compensation.accounting.additional.service.AdditionalBookingConfigurationService.$$ha$clinit(Unknown Source)
10:25:00,324 INFO  [stdout] (Thread-985)        ... 6 more
10:25:00,325 INFO  [stdout] (Thread-985)
10:25:00,326 INFO  [stdout] (Thread-987) HOTSWAP AGENT: 10:25:00.320 INFO (org.hotswap.agent.plugin.jackson.JacksonPlugin) - Reloaded Jackson.
10:25:00,370 INFO  [stdout] (Thread-983) HOTSWAP AGENT: 10:25:00.369 ERROR (org.hotswap.agent.plugin.weld.command.BeanClassRefreshAgent) - Bean reloading failed.
10:25:00,370 INFO  [stdout] (Thread-983) java.lang.IllegalStateException: WFLYWELD0039: Singleton not set for ModuleClassLoader for Module "deployment.luz_compensation.war" from Service Module Loader. This means that you are trying to access a weld deployment with a Thread Context ClassLoader that is not associated with the deployment.
10:25:00,371 INFO  [stdout] (Thread-983)        at org.jboss.as.weld@26.1.3.Final//org.jboss.as.weld.services.ModuleGroupSingletonProvider$TCCLSingleton.get(ModuleGroupSingletonProvider.java:77)
10:25:00,371 INFO  [stdout] (Thread-983)        at org.jboss.as.weld@26.1.3.Final//org.jboss.as.weld.services.ModuleGroupSingletonProvider$TCCLSingleton.get(ModuleGroupSingletonProvider.java:134)
10:25:00,371 INFO  [stdout] (Thread-983)        at org.jboss.weld.core@3.1.9.Final//org.jboss.weld.Container.instance(Container.java:57)
10:25:00,371 INFO  [stdout] (Thread-983)        at org.jboss.as.weld@26.1.3.Final//org.jboss.as.weld.WeldProvider.getCDI(WeldProvider.java:69)
10:25:00,371 INFO  [stdout] (Thread-983)        at javax.enterprise.api//javax.enterprise.inject.spi.CDI.current(CDI.java:64)
10:25:00,372 INFO  [stdout] (Thread-983)        at deployment.luz_compensation.war//org.hotswap.agent.plugin.weld.command.BeanClassRefreshAgent.reloadBean(BeanClassRefreshAgent.java:197)
10:25:00,372 INFO  [stdout] (Thread-983)        at jdk.internal.reflect.GeneratedMethodAccessor349.invoke(Unknown Source)
10:25:00,372 INFO  [stdout] (Thread-983)        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:25:00,372 INFO  [stdout] (Thread-983)        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
10:25:00,372 INFO  [stdout] (Thread-983)        at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.reloadBean(BeanClassRefreshCommand.java:204)
10:25:00,372 INFO  [stdout] (Thread-983)        at org.hotswap.agent.plugin.weld.command.BeanClassRefreshCommand.executeCommand(BeanClassRefreshCommand.java:139)
10:25:00,374 INFO  [stdout] (Thread-983)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
10:25:00,374 INFO  [stdout] (Thread-983)
