### ISSUE TITLE
HOTSWAP AGENT (0.3.0-SNAPSHOT) RELOAD - ERROR

### ISSUE THREAD

**Issue by hatecko23** [HotswapProjects/HotswapAgent#119]
Hello, can you help me please? I have this issue:

```
HOTSWAP AGENT: 13:26:29.744 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.3.0-SNAPSHOT} - unlimited runtime class redefinition.
HOTSWAP AGENT: 13:26:30.313 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox, Proxy, WebObjects, Weld, JBossModules, Resteasy, Gae]

---

HOTSWAP AGENT: 15:39:18.076 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [cz.datalite.cetin.web.prikazy.PrikazyDetailPanelController$1, cz.datalite.cetin.web.desktop.attr.DLAttributeHodnotaObject] (autoHotswap)
HOTSWAP AGENT: 15:39:18.131 ERROR (org.hotswap.agent.plugin.spring.signature.ClassfileSignatureComparer) - Error reading siganture
org.hotswap.agent.javassist.NotFoundException: cz.datalite.cetin.web.prikazy.PrikazyDetailPanelController
	at org.hotswap.agent.javassist.ClassPool.get(ClassPool.java:445)
	at org.hotswap.agent.javassist.bytecode.Descriptor.toCtClass(Descriptor.java:577)
	at org.hotswap.agent.javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:430)
	at org.hotswap.agent.javassist.CtBehavior.getParameterTypes(CtBehavior.java:286)
	at org.hotswap.agent.plugin.spring.signature.CtClassSignature.getConstructorString(CtClassSignature.java:29)
	at org.hotswap.agent.plugin.spring.signature.CtClassSignature.get(CtClassSignature.java:71)
	at org.hotswap.agent.plugin.spring.signature.ClassfileSignatureComparer.isPoolClassDifferent(ClassfileSignatureComparer.java:24)
	at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.classChangeNeedsReload(SpringChangesAnalyzer.java:43)
	at org.hotswap.agent.plugin.spring.SpringChangesAnalyzer.isReloadNeeded(SpringChangesAnalyzer.java:36)
	at org.hotswap.agent.plugin.spring.SpringPlugin$1.transform(SpringPlugin.java:80)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:268)
	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

HOTSWAP AGENT: 15:39:18.143 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin' class 'cz/datalite/cetin/web/prikazy/PrikazyDetailPanelController$1'.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:157)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:268)
	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.NullPointerException
	at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.lastModified(AnonymousClassInfos.java:252)
	at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.<init>(AnonymousClassInfos.java:90)
	at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.getStateInfo(AnonymousClassPatchPlugin.java:216)
	at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.patchAnonymousClass(AnonymousClassPatchPlugin.java:82)
	... 14 more

HOTSWAP AGENT: 15:39:24.633 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [cz.datalite.cetin.web.prikazy.PrikazyDetailPanelController$1, cz.datalite.cetin.web.prikazy.PrikazyDetailPanelController$2] (autoHotswap)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000007c9ff3c, pid=8468, tid=8856
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.5-b02-dcevmlight-58 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x19ff3c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as: hs_err_pid8468.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Guidewire/DCEVM/issues
#
Dynamic Code Evolution 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Disconnected from the target VM, address: '127.0.0.1:61651', transport: 'socket'

Process finished with exit code 1
```

An error report file with more information is saved here: [hs_err_pid8468.log](http://s000.tinyupload.com/index.php?file_id=43525604096377566959)

**Comment by skybber** [comment]
Could you try last repo version? I've fixed some problems  with ClassSignatures in HA and Spring Plugin uses common Signature in HA core now.

**Comment by hatecko23** [comment]
I'm using version released this on 15 Feb

**Comment by skybber** [comment]
That's ok, I've fixed it on Feb 28. But in your case DCEVM crashed after anonymous class had been changed. I suspect that there is a bug in the DCEVM when internal or anonymous class is changing in application class loader.

**Comment by skybber** [comment]
I've commited change that fixes problems with anonymous class reloading. May be it could help you.

**Comment by hatecko23** [comment]
I just started using the latest version and will test it. Thank you

**Comment by hatecko23** [comment]
After 6 days of use, I now reappeared this error:

```console
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000f54f7c70, pid=3044, tid=6812
#
# JRE version: Java(TM) SE Runtime Environment (8.0_05-b13) (build 1.8.0_05-b13)
# Java VM: Dynamic Code Evolution 64-Bit Server VM (25.5-b02-dcevmlight-58 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x00000000f54f7c70
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as: hs_err_pid3044.log
# 
Compiled method (c1) 6658497 26153       1       sun.invoke.util.ValueConversions::identity (2 bytes)
 total in heap  [0x00000000145a5090,0x00000000145a5308] = 632
 relocation     [0x00000000145a51b0,0x00000000145a51d0] = 32
 main code      [0x00000000145a51e0,0x00000000145a5240] = 96
 stub code      [0x00000000145a5240,0x00000000145a52d0] = 144
 metadata       [0x00000000145a52d0,0x00000000145a52d8] = 8
 scopes data    [0x00000000145a52d8,0x00000000145a52e0] = 8
 scopes pcs     [0x00000000145a52e0,0x00000000145a5300] = 32
 dependencies   [0x00000000145a5300,0x00000000145a5308] = 8
#
# If you would like to submit a bug report, please visit:
#   https://github.com/Guidewire/DCEVM/issues
#
```

An error report file with more information is saved here: [hs_err_pid3044.log](http://s000.tinyupload.com/index.php?file_id=27805930213371559063)

**Comment by skybber** [comment]
You've probably changed lamba expression in the class. According log you have java 1.8.0_05. I would  recommend to uprgrade to the last DCEVM version since Ivan fixed many problems with lambda in later versions.

**Comment by hatecko23** [comment]
I already upgraded and will test. Thank you

**Comment by hatecko23** [comment]
Problem solved. Thank you
