### ISSUE TITLE
ConcurrentModificationException in NIO watcher

### ISSUE THREAD

**Issue by xsurfing** [HotswapProjects/HotswapAgent#128]
From time to time (on 25.66-b00 for matching JDK @ 64bit, tried on 3.0 and 3.0_SNAPSHOT) reload fails with

```
HOTSWAP AGENT: 19:29:1.729 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.jasper.servlet.JasperLoader@8e3827e'.
Exception in thread "Thread-1" java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at org.hotswap.agent.watch.nio.WatcherNIO2.callListeners(WatcherNIO2.java:239)
        at org.hotswap.agent.watch.nio.WatcherNIO2.processEvents(WatcherNIO2.java:207)
        at org.hotswap.agent.watch.nio.WatcherNIO2.access$100(WatcherNIO2.java:32)
        at org.hotswap.agent.watch.nio.WatcherNIO2$2.run(WatcherNIO2.java:272)
```

I also noticed that - in case this is not crashing the JVM - in some cases I get a repetition of reload events in log:

```
HOTSWAP AGENT: 20:38:38.940 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.X.amazonaws.AmazonAWSAccessService] (autoHotswap)
HOTSWAP AGENT: 20:38:38.941 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.X.amazonaws.AmazonAWSAccessService, com.X.amazonaws.AmazonAWSAccessService$AWSCognitoIdentity] (autoHotswap)
HOTSWAP AGENT: 20:38:38.952 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.X.amazonaws.AmazonAWSAccessService, com.X.amazonaws.AmazonAWSAccessService$AWSCognitoIdentity] (autoHotswap)
```

not sure if both are correlated.

**Comment by skybber** [comment]
Should be solved #127, could you check is?
