### ISSUE TITLE
Cannot initialize plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin', appClassLoader is null.

### ISSUE THREAD

**Issue by vpablos** [HotswapProjects/HotswapAgent#143]
Hi. 

Tried last version (git 373dfb5760e36bbf47ba443103be8463f0ad8ef5 )
and found problems (below). Checked out  RELEASE-0.3 and it is not there.
Just notifying so you take it into account for next stable version.
Thanks for your time supporting this incredible tool.

HOTSWAP AGENT: 9:14:4.067 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.3.0-SNAPSHOT} - unlimited runtime class redefinition.
HOTSWAP AGENT: 9:14:4.653 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@5502abdb'.
HOTSWAP AGENT: 9:14:4.727 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [WatchResources, Hotswapper, AnonymousClassPatch, Hibernate, Hibernate3, Hibernate3JPA, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox, Proxy, WebObjects, Weld, JBossModules, Resteasy, Gae, Deltaspike, JavaBeans]
HOTSWAP AGENT: 9:14:4.733 ERROR (org.hotswap.agent.annotation.handler.InitHandler) - InvocationTargetException in init method on plugin class org.hotswap.agent.plugin.hotswapper.HotswapperPlugin.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.annotation.handler.InitHandler.invokeInitMethod(InitHandler.java:86)
    at org.hotswap.agent.annotation.handler.InitHandler.access$100(InitHandler.java:28)
    at org.hotswap.agent.annotation.handler.InitHandler$1.onInit(InitHandler.java:110)
    at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:175)
    at org.hotswap.agent.util.HotswapTransformer.ensureClassLoaderInitialized(HotswapTransformer.java:170)
    at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
Caused by: java.lang.IllegalArgumentException: Cannot initialize plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin', appClassLoader is null.
    at org.hotswap.agent.config.PluginRegistry.initializePlugin(PluginRegistry.java:137)
    at org.hotswap.agent.util.PluginManagerInvoker.callInitializePlugin(PluginManagerInvoker.java:26)
    at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin.init(HotswapperPlugin.java:127)
    ... 12 more

HOTSWAP AGENT: 9:14:5.999 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'org.apache.catalina.loader.StandardClassLoader@57f0b146'.

...

HOTSWAP AGENT: 9:14:21.877 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.hibernate3.session.Hibernate3Plugin' class 'org/hibernate/cfg/Configuration'.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:157)
    at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
    at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:140)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2959)
    at org.apache.catalina.loader.WebappClassLoader.findClass(WebappClassLoader.java:1212)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1692)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1573)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
    at java.lang.Class.getDeclaredMethods(Class.java:1860)
    at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:609)
    at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:521)
    at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:507)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:241)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1069)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1042)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.java:865)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:796)
    at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:544)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:447)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:423)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:530)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:523)
    at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1162)
    at org.springframework.context.event.EventListenerMethodProcessor.getEventListenerFactories(EventListenerMethodProcessor.java:119)
    at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:74)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:792)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5017)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5531)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1574)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1564)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] _buildSessionFactory() not found in org.hibernate.cfg.Configuration
    at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:75)
    at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:43)
    at org.hotswap.agent.plugin.hibernate3.session.Hibernate3Transformers.proxySessionFactory(Hibernate3Transformers.java:62)
    ... 50 more
Caused by: compile error: _buildSessionFactory() not found in org.hibernate.cfg.Configuration
    at org.hotswap.agent.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:684)
    at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:650)
    at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:147)
    at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:43)
    at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:208)
    at org.hotswap.agent.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:670)
    at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:650)
    at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:147)
    at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:43)
    at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:241)
    at org.hotswap.agent.javassist.compiler.CodeGen.compileExpr(CodeGen.java:229)
    at org.hotswap.agent.javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:597)
    at org.hotswap.agent.javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:405)
    at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
    at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:51)
    at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:352)
    at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:51)
    at org.hotswap.agent.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:296)
    at org.hotswap.agent.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:279)
    at org.hotswap.agent.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:52)
    at org.hotswap.agent.javassist.compiler.Javac.compileMethod(Javac.java:153)
    at org.hotswap.agent.javassist.compiler.Javac.compile(Javac.java:83)
    at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:71)
    ... 52 more

$ java -version -XXaltjvm=dcevm
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
Dynamic Code Evolution 64-Bit Server VM (build 24.79-b02-dcevmfull-dev, mixed mode)

**Comment by tim-sysoev** [comment]
Same happens to us when Hibernate3 plugin tries to initialize with Hibernate 4.3 in classpath.

**Comment by skybber** [comment]
We have no mechanism resolving existence of Hibernate3/Hibernate4. You can temporarily disable Hibernate3 in hotswap-agent.properties by specifying disabledPlugins=Hibernate3,Hiberna3JPA

**Comment by skybber** [comment]
A new mechanism resolving Hibernate3/4 from @alpapad is in the repository. It is not released, you must clone the repo. Could you check if it solve your problem?

**Comment by skybber** [comment]
I have no problems to compile last version. What is your dev enviroment: java version / dcevm version ?

**Comment by vpablos** [comment]
Hi. Sorry for the delay.

$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
$ java -XXaltjvm=dcevm -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
Dynamic Code Evolution 64-Bit Server VM (build 24.79-b02-dcevmfull-8, mixed mode)
$

Compiles well 9026fb8 (RELEASE-0.3 tag)

**Comment by skybber** [comment]
I've tried to build HA with dcevm7u111. It works on my OS - ArchLinux. Dis you run mvn clean before? What kind of OS you have?

**Comment by skybber** [comment]
I'm closing this issue since it is not related to original subject anymore.
