### ISSUE TITLE
UnsupportedOperationException when reloading: class redefinition failed: attempted to add a method

### ISSUE THREAD

**Issue by geert3** [HotswapProjects/HotswapAgent#162]
Using Wildfly 10.
The following Exception is produced very often, for instance while simply modifying a String literal inside a simple statement inside existing method inside existing (non-CDI) class. 

```
20:53:26,180 INFO  [stdout] (JDWP Transport Listener: dt_socket) Non Static lgc.mysynap.server.logic.graph.DotBuilder
20:53:26,338 INFO  [stdout] (Thread-281) HOTSWAP AGENT: 20:53:26.337 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [lgc.mysynap.server.logic.graph.DotBuilder] (autoHotswap)
20:53:26,346 ERROR [stderr] (Thread-281) Exception in thread "Thread-281" java.lang.IllegalStateException: Unable to redefine classes
20:53:26,347 ERROR [stderr] (Thread-281) 	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:272)
20:53:26,347 ERROR [stderr] (Thread-281) 	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
20:53:26,347 ERROR [stderr] (Thread-281) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
20:53:26,347 ERROR [stderr] (Thread-281) Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method
20:53:26,348 ERROR [stderr] (Thread-281) 	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
20:53:26,348 ERROR [stderr] (Thread-281) 	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
20:53:26,348 ERROR [stderr] (Thread-281) 	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:269)
20:53:26,348 ERROR [stderr] (Thread-281) 	... 2 more
```

It does work in similar circumstances in other classes, I can't see an immediate logic behind when it fails and when it succeeds. This is the output for a similar (but successful) modification in another class:

```
21:05:33,328 INFO  [stdout] (JDWP Transport Listener: dt_socket) Declaringlgc.mysynap.server.dependency.DependencyGraph 0
21:05:33,329 INFO  [stdout] (JDWP Transport Listener: dt_socket) Staticlgc.mysynap.server.dependency.DependencyGraph$DependencyGraphNode
21:05:33,333 INFO  [stdout] (JDWP Transport Listener: dt_socket) Non Static lgc.mysynap.server.dependency.DependencyGraph
21:05:33,514 INFO  [stdout] (Thread-283) HOTSWAP AGENT: 21:05:33.513 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [lgc.mysynap.server.dependency.DependencyGraph, lgc.mysynap.server.dependency.DependencyGraph$DependencyGraphNode] (autoHotswap)
21:05:33,521 INFO  [stdout] (Thread-283) Non Static lgc.mysynap.server.dependency.DependencyGraph
21:05:33,528 INFO  [stdout] (Thread-283) Declaringlgc.mysynap.server.dependency.DependencyGraph 0
21:05:33,528 INFO  [stdout] (Thread-283) Staticlgc.mysynap.server.dependency.DependencyGraph$DependencyGraphNode
```

**Comment by skybber** [comment]
It looks like you don't use dcevm. Folowing error is produced by standard redefinition, dcevm redefinition allows method add. 

    20:53:26,347 ERROR [stderr] (Thread-281) Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to add a method

**Comment by geert3** [comment]
sorry about that, you're right, I must have inadvertedly changed wildfly's JDK to an unpatched version.
