### ISSUE TITLE
interface org.springframework.web.bind.annotation.RequestMapping is not visible from class loader

### ISSUE THREAD

**Issue by angelmanner** [HotswapProjects/HotswapAgent#175]
i dont know error. 

please help me.

Java : 1.7.0_79
OS : yosemite
Framework : spring 4.2.0
WAS : tomcat 7.0.69
Version : Hostwapper 1.1.0 snapshot or Hostwapper 1.0.0.release

 
HOTSWAP AGENT: 12:17:31.853 ERROR (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Failed to clear HandlerMappings
java.lang.IllegalArgumentException: interface org.springframework.web.bind.annotation.RequestMapping is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:616)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:592)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:244)
	at java.lang.reflect.WeakCache.get(WeakCache.java:141)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:455)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:738)
	at org.springframework.core.annotation.AnnotationUtils.synthesizeAnnotation(AnnotationUtils.java:1275)
	at org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation(AnnotatedElementUtils.java:413)
	at org.springframework.core.annotation.AnnotatedElementUtils.findMergedAnnotation(AnnotatedElementUtils.java:384)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.createRequestMappingInfo(RequestMappingHandlerMapping.java:211)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.getMappingForMethod(RequestMappingHandlerMapping.java:193)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.getMappingForMethod(RequestMappingHandlerMapping.java:53)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping$1.matches(AbstractHandlerMethodMapping.java:211)
	at org.springframework.web.method.HandlerMethodSelector$1.doWith(HandlerMethodSelector.java:62)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524)
	at org.springframework.web.method.HandlerMethodSelector.selectMethods(HandlerMethodSelector.java:57)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:208)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:183)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:164)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:133)
	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:74)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

**Comment by skybber** [comment]
Please check it with  snapshot 1.1.0-SNAPHOT if it help. Thanks
