### ISSUE TITLE
InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin'

### ISSUE THREAD

**Issue by sanity** [HotswapProjects/HotswapAgent#180]
I'm trying to use hotswapagent with a [Kotlin](http://kotlinlang.org/) project.  It seems to work, however the following error is being generated when it reloads a class.  I'm using the latest build of HotswapAgent (1.1.0-SNAPSHOT).

```
HOTSWAP AGENT: 14:28:48.994 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin' class 'investorscan/web/EmailAddressForm$$special$$inlined$apply$lambda$3'.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:189)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:85)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:181)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
Caused by: java.lang.NullPointerException
	at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.lastModified(AnonymousClassInfos.java:252)
	at org.hotswap.agent.plugin.jvm.AnonymousClassInfos.<init>(AnonymousClassInfos.java:90)
	at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.getStateInfo(AnonymousClassPatchPlugin.java:218)
	at org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin.patchAnonymousClass(AnonymousClassPatchPlugin.java:82)
	... 9 more
```

**Comment by skybber** [comment]
I'll look on this issue later, but you can temporarily fix this problem by disabling AnonymousClassPatch plugin:

    -javaagent:.../hotswap-agent.jar=disablePlugin=AnonymousClassPatch

**Comment by sanity** [comment]
Thanks, however I think Kotlin code makes quite heavy use of anonymous classes, will that be a problem?

**Comment by sanity** [comment]
Ok, tried it, the exception has gone, I haven't noticed any issues caused by disabling the anonymous class plugin.

**Comment by jorginius** [comment]
The exception is gone but the hotswap is not working properly. I am unable to set breakpoints and the code has not been executed. It seems to have been removed on reloading.

I'm not sure but I think it is an issue with [Kotlin's apply function](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/apply.html) and maybe with extension functions too.
