### ISSUE TITLE
NoClassDefFoundError exception for org/springframework/beans/factory/support/AbstractBeanDefinition

### ISSUE THREAD

**Issue by anfe0690** [HotswapProjects/HotswapAgent#183]
Hi, so I started using DCEVM because I wanted to be able to add and remove methods while developing, then after a couple of changes, I found out that I wasn't able to make work the new methods with annotations @RequestMapping (from Spring Framework) that I added. DCEVM can add new methods, but cannot register them in Spring as far I know.

Looking for another option, I found HotswapAgent, which in its web page http://hotswapagent.org/index.html, says that it supports Spring Framework. Then after configuring the JVM parameter, running the server in debug mode, and adding a comment line, I'm getting an Exception, which doesn't make any sense, a comment line should not provoke that:

<pre>
15:36:11,892Z ERROR [stderr] (Thread-440) Exception in thread "Thread-440" java.lang.NoClassDefFoundError: org/springframework/beans/factory/support/AbstractBeanDefinition
15:36:11,898Z ERROR [stderr] (Thread-440) Exception in thread "Thread-444" Exception in thread "Thread-443" Exception in thread "Thread-441" Exception in thread "Thread-442" 	at java.lang.Class.getDeclaredMethods0(Native Method)
15:36:11,898Z ERROR [stderr] (Thread-440) 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
15:36:11,898Z ERROR [stderr] (Thread-440) 	at java.lang.Class.getDeclaredMethod(Class.java:2128)
15:36:11,898Z ERROR [stderr] (Thread-440) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:72)
15:36:11,899Z ERROR [stderr] (Thread-440) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
15:36:11,899Z ERROR [stderr] (Thread-440) Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.support.AbstractBeanDefinition
15:36:11,899Z ERROR [stderr] (Thread-440) 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
15:36:11,900Z ERROR [stderr] (Thread-440) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
15:36:11,900Z ERROR [stderr] (Thread-440) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
15:36:11,900Z ERROR [stderr] (Thread-440) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
15:36:11,901Z ERROR [stderr] (Thread-440) 	... 5 more
15:36:11,901Z ERROR [stderr] (Thread-441) java.lang.NoClassDefFoundError: org/springframework/beans/factory/support/AbstractBeanDefinition
15:36:11,901Z ERROR [stderr] (Thread-441) 	at java.lang.Class.getDeclaredMethods0(Native Method)
15:36:11,902Z ERROR [stderr] (Thread-441) 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
15:36:11,902Z ERROR [stderr] (Thread-441) 	at java.lang.Class.getDeclaredMethod(Class.java:2128)
15:36:11,902Z ERROR [stderr] (Thread-441) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:72)
15:36:11,902Z ERROR [stderr] (Thread-441) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
</pre>

This is my enviroment:
- Linux Mint 18.1 KDE
- Netbeans 8.2
- Oracle JDK 8u112 with DCEVM Java 8 update 112, build 8 (Replaced the original files of oracle)
- Wildfly 10.1.0.Final
- Spring Framework 4.3.6.RELEASE

If there is anything that I'm doing wrong or something that you need to know please tell me, I really want to make this agent work, it can save me a lot of time.

Thanks.

**Comment by skybber** [comment]
Your setup is OK. We did't check Spring application under Wildfly properly yet. There is a [hack](https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/HotswapAgent.java#L109-L122) in HotswapAgent that setups classloading delegation for HA packages, but your problem is little bit diffferent. The [code throwing this exeption](https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/scanner/ClassPathBeanRefreshCommand.java#L71)  loads `ClassPathBeanRefreshCommand` from appClassLoader (classloader of your application). But under Wildfly `ClassPathBeanRefreshCommand` could be loaded by another (module) classloader. Therefore it is not visible from appClassLoader, may be appClassLoader is wrong. We have solved this problem for Weld some time ago, but not for Spring. Unfortunatelly I can't fix, since I don't use Spring. On the other hand I'would like to help to anybody who will try to fix it.

**Comment by anfe0690** [comment]
Hi @skybber, can you give me instructions?, maybe I can take a look.

Additionally, can you describe me an environment where the Agent works as intended with all the features?

Thanks in advance.

**Comment by skybber** [comment]
OK, write me an email on addres from repository logs.

**Comment by skybber** [comment]
Please check it with last snapshot 1.1.0-SNAPHOT if it helps. Thanks

**Comment by anfe0690** [comment]
Hi @skybber, I tested Spring with the version 1.1.0-SNAPHOT, and I was able to add a new method with a @RequestMapping annotation. I think that this will allow me to work for now.

But, I'm still getting an exception:

<pre>
01:08:29,715Z INFO  [stdout] (Thread-330) HOTSWAP AGENT: 01:08:29.715 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class test/MyController in classLoader ModuleClassLoader for Module "my-project.war:main" from Service Module Loader
01:08:29,719Z INFO  [stdout] (Thread-330) java.lang.reflect.InvocationTargetException
01:08:29,719Z INFO  [stdout] (Thread-330) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:08:29,719Z INFO  [stdout] (Thread-330) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:08:29,719Z INFO  [stdout] (Thread-330) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:08:29,719Z INFO  [stdout] (Thread-330) 	at java.lang.reflect.Method.invoke(Method.java:498)
01:08:29,719Z INFO  [stdout] (Thread-330) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
01:08:29,720Z INFO  [stdout] (Thread-330) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
</pre>

Right now I'm creating a project so I can test more properly a few of the frameworks that I use (Spring, JPA Hibernate, etc). Additionally, I'll be able to show you more detailed error messages.

I'll write you back when I'm done.

**Comment by skybber** [comment]
As I think it is different exception the original one was `Class not Found org/springframework/beans/factory/support/AbstractBeanDefinition` . I didn't received class not found one any more, your new problem looks strange, I will check it with spring 4.3 again (did tests with 4.2)

**Comment by skybber** [comment]
I've tested with Spring 4.3.6.RELEASE, Wildfy8, jdk8 and it works. What is your tech. stack?

**Comment by anfe0690** [comment]
Hi, they are the same that I listed before:
- Linux Mint 18.1 KDE
- Netbeans 8.2
- Oracle JDK 8u112 with DCEVM Java 8 update 112, build 8 (Replaced the original files of oracle)
- Wildfly 10.1.0.Final
- Spring Framework 4.3.6.RELEASE

Remember that I said it worked with the snapshot version, but that it is still throwing me an exception.

**Comment by skybber** [comment]
Could you supply full error stack trace please? It is no clear what was failed.

**Comment by anfe0690** [comment]
Hi, I have created a repository, that you can use if you want to reproduce the issue.

https://github.com/anfe0690/hotswap-spring-test

Just remove the comment characters around the methods in the MainController class and save. That should reproduce the issue. Of course I assume that you are using the same tech stack that I posted before.
Here is what the exception looks like:
<pre>
13:47:25,477Z INFO  [stdout] (Thread-302) HOTSWAP AGENT: 13:47:25.476 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'mainController'
13:47:25,486Z INFO  [stdout] (Thread-303) HOTSWAP AGENT: 13:47:25.486 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'mainController'
13:47:25,490Z INFO  [stdout] (Thread-303) HOTSWAP AGENT: 13:47:25.490 INFO (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Spring: clearing HandlerMapping for class org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
13:47:25,502Z INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] (Thread-303) Mapped "{[/],methods=[GET]}" onto public java.lang.String com.anfe0690.hotswapspringtest.MainController.homeGet()
13:47:25,503Z INFO  [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping] (Thread-303) Mapped "{[/test],methods=[GET]}" onto public java.lang.String com.anfe0690.hotswapspringtest.MainController.testGet()
13:47:25,515Z INFO  [stdout] (Thread-301) HOTSWAP AGENT: 13:47:25.515 RELOAD (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - Registering Spring bean 'mainController'
13:47:25,539Z INFO  [stdout] (Thread-302) HOTSWAP AGENT: 13:47:25.539 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class com/anfe0690/hotswapspringtest/MainController in classLoader ModuleClassLoader for Module "deployment.hotswap-spring-test.war:main" from Service Module Loader
13:47:25,539Z INFO  [stdout] (Thread-302) java.lang.reflect.InvocationTargetException
13:47:25,539Z INFO  [stdout] (Thread-302) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:47:25,540Z INFO  [stdout] (Thread-302) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:47:25,540Z INFO  [stdout] (Thread-302) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:47:25,540Z INFO  [stdout] (Thread-302) 	at java.lang.reflect.Method.invoke(Method.java:498)
13:47:25,540Z INFO  [stdout] (Thread-302) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
13:47:25,540Z INFO  [stdout] (Thread-302) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
13:47:25,540Z INFO  [stdout] (Thread-302) Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Initialization of bean failed; nested exception is java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
13:47:25,540Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
13:47:25,541Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
13:47:25,541Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
13:47:25,541Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
13:47:25,541Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
13:47:25,541Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
13:47:25,542Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:519)
13:47:25,542Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:310)
13:47:25,542Z INFO  [stdout] (Thread-302) 	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:36)
13:47:25,542Z INFO  [stdout] (Thread-302) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
13:47:25,542Z INFO  [stdout] (Thread-302) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
13:47:25,542Z INFO  [stdout] (Thread-302) 	... 6 more
13:47:25,543Z INFO  [stdout] (Thread-302) Caused by: java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
13:47:25,543Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:170)
13:47:25,543Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1197)
13:47:25,543Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:310)
13:47:25,543Z INFO  [stdout] (Thread-302) 	at org.springframework.web.servlet.handler.AbstractHandlerMapping.detectMappedInterceptors(AbstractHandlerMapping.java:272)
13:47:25,544Z INFO  [stdout] (Thread-302) 	at org.springframework.web.servlet.handler.AbstractHandlerMapping.initApplicationContext(AbstractHandlerMapping.java:247)
13:47:25,544Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.ApplicationObjectSupport.initApplicationContext(ApplicationObjectSupport.java:120)
13:47:25,544Z INFO  [stdout] (Thread-302) 	at org.springframework.web.context.support.WebApplicationObjectSupport.initApplicationContext(WebApplicationObjectSupport.java:76)
13:47:25,544Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:74)
13:47:25,545Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
13:47:25,545Z INFO  [stdout] (Thread-302) 	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
13:47:25,545Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
13:47:25,545Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
13:47:25,545Z INFO  [stdout] (Thread-302) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
13:47:25,546Z INFO  [stdout] (Thread-302) 	... 16 more
13:47:25,546Z INFO  [stdout] (Thread-302) 
13:47:25,563Z INFO  [stdout] (Thread-301) HOTSWAP AGENT: 13:47:25.563 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class com/anfe0690/hotswapspringtest/MainController in classLoader ModuleClassLoader for Module "deployment.hotswap-spring-test.war:main" from Service Module Loader
13:47:25,564Z INFO  [stdout] (Thread-301) java.lang.reflect.InvocationTargetException
13:47:25,564Z INFO  [stdout] (Thread-301) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:47:25,564Z INFO  [stdout] (Thread-301) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:47:25,564Z INFO  [stdout] (Thread-301) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:47:25,564Z INFO  [stdout] (Thread-301) 	at java.lang.reflect.Method.invoke(Method.java:498)
13:47:25,565Z INFO  [stdout] (Thread-301) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
13:47:25,565Z INFO  [stdout] (Thread-301) 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
13:47:25,565Z INFO  [stdout] (Thread-301) Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping': Initialization of bean failed; nested exception is java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
13:47:25,565Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
13:47:25,565Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
13:47:25,565Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:519)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:310)
13:47:25,566Z INFO  [stdout] (Thread-301) 	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:36)
13:47:25,567Z INFO  [stdout] (Thread-301) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
13:47:25,567Z INFO  [stdout] (Thread-301) 	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
13:47:25,567Z INFO  [stdout] (Thread-301) 	... 6 more
13:47:25,567Z INFO  [stdout] (Thread-301) Caused by: java.lang.IllegalStateException: BeanFactory not initialized or already closed - call 'refresh' before accessing beans via the ApplicationContext
13:47:25,567Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.AbstractRefreshableApplicationContext.getBeanFactory(AbstractRefreshableApplicationContext.java:170)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1197)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:310)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.web.servlet.handler.AbstractHandlerMapping.detectMappedInterceptors(AbstractHandlerMapping.java:272)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.web.servlet.handler.AbstractHandlerMapping.initApplicationContext(AbstractHandlerMapping.java:247)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.ApplicationObjectSupport.initApplicationContext(ApplicationObjectSupport.java:120)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.web.context.support.WebApplicationObjectSupport.initApplicationContext(WebApplicationObjectSupport.java:76)
13:47:25,568Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:74)
13:47:25,569Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
13:47:25,569Z INFO  [stdout] (Thread-301) 	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
13:47:25,569Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
13:47:25,569Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
13:47:25,569Z INFO  [stdout] (Thread-301) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
13:47:25,569Z INFO  [stdout] (Thread-301) 	... 16 more
13:47:25,570Z INFO  [stdout] (Thread-301)
</pre>
Another thing that I want to add is that I haven't test it in Eclipse, so I'm not sure if it is a Netbeans thing.

**Comment by skybber** [comment]
I've tested it and it works. I'm updating the [1.1.0-SNAPSHOT](https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.1.0-SNAPSHOT) continually. May be you didn't do the tests with last version I've uploaded 2 days ago. GitHub shows release date the Feb 16 there, but not update date.

**Comment by lRawd** [comment]
This is my first time running HA and I have run into this same issue. 
- CentOS 7.3
- Netbeans 8.2
- OpenJDK 1.8.0_121
- Wildfly 10.1.0.Final
- Spring Framework 4.3.2.RELEASE

**Comment by lRawd** [comment]
This issue only seems to occur when Netbeans redeploys the application without restarting wildfly. If I undeploy prior to shutting down the wildfly server, the next time I launch as Debug it functions properly.
