### ISSUE TITLE
Hotswap not working on making a change to a Java file - WatchKey 'sun.nio.fs.WindowsWatchService$WindowsWatchKey@3156f1b7' overflowed

### ISSUE THREAD

**Issue by sachinkakkar7** [HotswapProjects/HotswapAgent#193]
Hi,

Here's my technology stack:-
1. Eclipse- Kepler
2. ATG 11
3. Java 8u66
4. JBoss 6.4.0
5. DCEVM-light-8u66-installer.jar
6. hotswap-agent-1.1.0-SNAPSHOT.jar.
7. Using Maven with eclipse - multi module project

DCEVM and HA have been configured properly. The classes directory of the modules in my project is being watched.

Now, here is the issue.
1. Build Automatically in eclipse is enabled
2. The moment I make a change in java file and save it, build begins in eclipse
3. And, I see the below in JBoss console

 **WARNING (org.hotswap.agent.watch.nio.TreeWatcherNIO) - WatchKey 'sun.nio.fs.WindowsWatchService$WindowsWatchKey@3156f1b7' overflowed**

Followed by a series of errors of the below kind. The .class files are getting deleted from the workspace.

 ****HOTSWAP AGENT: 12:06:13.744 ERROR 

 (org.hotswap.agent.annotation.handler.WatchEventCommand)

 **Unable create CtClass for URI 'file:///C:/Workspaces/SomeModule/build/classes/atg/commerce/pricing/SomeFile.class'.
 java.lang.IllegalArgumentException: java.io.FileNotFoundException:** C:\Workspaces\Care\build\classes\atg\commerce\pricing\SomeFile.class (The system cannot find the path specified)****
        at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:53)
        at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:200)
        at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:129)
        at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:80)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
 Caused by: java.io.FileNotFoundException: C:\Workspaces\Care\build\classes\atg\commerce\pricing\SomeFile.class (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at java.net.URL.openStream(URL.java:1038)
        **at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:47)**
        ... 4 more

**Comment by sachinkakkar7** [comment]
So I was able to resolve the above issue. It had nothing to do with HA. 

But now when I make any change to java file, I dont see anything happening in JBoss console, no error and change doesnt get reflected on refresh on browser.

**Comment by sachinkakkar7** [comment]
I turned on the debugger, made a change and saved. Could see the redefinition logs in JBoss console and changes were there on refresh of browser.

1. Why arent the change getting picked without turning on debugger> I have set autoHotswap to true
2. I made around 3 changes which were reflected successfully. Thereafter started getting java.lang.LinkageError:LoaderConstraintViolation

Caused by: javax.servlet.ServletException: Exception occurred trying to get /com/att/wireless/profile/bean/HierarchyContext.banBean.billingAccountNumber exception: **java.lang.LinkageError: loader constraint violation: when resolving method "com.att.wireless.profile.bean.CoreHierarchyContext.getBanBean()Lcom/att/wireless/profile/bean/BanBean;" the class loader (instance of sun/reflect/DelegatingClassLoader) of the current class, sun/reflect/GeneratedMethodAccessor250, and the class loader (instance of org/jboss/modules/ModuleClassLoader) for the method's defining class,** com/att/wireless/profile/bean/CoreHierarchyContext, have different Class objects for the type com/att/wireless/profile/bean/BanBean used in the signature
        at atg.droplet.DropletDescriptorManager.getPropertyValue(DropletDescriptorManager.java:530) [_DAS_slib_sclasses.jar:]
        at atg.droplet.DropletDescriptor.getPropertyValue(DropletDescriptor.java:510) [_DAS_slib_sclasses.jar:]
        at atg.taglib.dspjsp.ParamTag.doStartTag(ParamTag.java:334) [_DAS_slib_sclasses.jar:]
        at org.apache.jsp.common.head_005fcontents_jsp._jspx_meth_dsp_005fparam_005f17(head_005fcontents_jsp.java:3831)
        at org.apache.jsp.common.head_005fcontents_jsp._jspx_meth_dsp_005fdroplet_005f18(head_005fcontents_jsp.java:3782)
        at org.apache.jsp.common.head_005fcontents_jsp._jspService(head_005fcontents_jsp.java:433)
        ... 101 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source) [:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_66]
        at atg.droplet.DropletDescriptorManager.getPropertyValue(DropletDescriptorManager.java:490) [_DAS_slib_sclasses.jar:]
        ... 106 more
**Caused by: java.lang.LinkageError: loader constraint violation: when resolving method** "com.att.wireless.profile.bean.CoreHierarchyContext.getBanBean()Lcom/att/wireless/profile/bean/BanBean;" the class loader (instance of sun/reflect/DelegatingClassLoader) of the current class, sun/reflect/GeneratedMethodAccessor250, and the class loader (instance of org/jboss/modules/ModuleClassLoader) for the method's defining class, com/att/wireless/profile/bean/CoreHierarchyContext, have different Class objects for the type com/att/wireless/profile/bean/BanBean used in the signature
        ... 110 more

**Comment by skybber** [comment]
If you setup autoHotswap and extraclassPath, it should work.

**Comment by sachinkakkar7** [comment]
I am still getting this error.

17:07:46,027 ERROR [nucleusNamespace] (http-/127.0.0.1:8080-6) Unable to set configured property "/com/att/wireless/care/profile/web/EditProfileFormHandler.transactionController" atg.nucleus.ConfigurationException: /com/att/wireless/care/base/TransactionController: **java.lang.LinkageError: loader constraint violation: when resolving method** "com.att.wireless.care.base.B2BCareFormHandler.setTransactionController(Lcom/att/wireless/care/base/TransactionController;)V" the class loader (instance of sun/reflect/DelegatingClassLoader) of the current class, **sun/reflect/GeneratedMethodAccessor298, and the class loader (instance of org/jboss/modules/ModuleClassLoader) for the method's defining class,** com/att/wireless/care/base/B2BCareFormHandler, have different Class objects for the type com/att/wireless/care/base/TransactionController used in the signature
        at sun.reflect.GeneratedMethodAccessor298.invoke(Unknown Source) [:1.8.0_66]

**Comment by skybber** [comment]
Please create a new issue if original problem is solved. Original is caused by wrong configuration.
