### ISSUE TITLE
Log4j2 Plugin doesn't check for all classes necessary

### ISSUE THREAD

**Issue by xXAndrew28Xx** [HotswapProjects/HotswapAgent#200]
I was trying this out for the first time, on load of my application; This stacktrace showed up in console:
```vb
HOTSWAP AGENT: 17:20:21.185 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 17:20:22.354 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, WatchResources, AnonymousClassPatch, ClassInitPlugin, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, JavaBeans]
== STARTING ==
2017-05-22 17:20:27,463 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
HOTSWAP AGENT: 17:20:29.952 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.log4j2.Log4j2Plugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@18b4aac2'.
HOTSWAP AGENT: 17:20:29.954 ERROR (org.hotswap.agent.plugin.log4j2.Log4j2Plugin) - Exception initializing Log4j2 on uri null.
java.lang.ClassNotFoundException: org.apache.logging.log4j.core.config.ConfigurationSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.hotswap.agent.plugin.log4j2.Log4j2Plugin.init(Log4j2Plugin.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:352)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:378)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:149)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:85)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:34)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:387)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:322)
	at net.minecraft.server.v1_8_R3.MinecraftServer.<clinit>(MinecraftServer.java:56)
	at org.bukkit.craftbukkit.Main.main(Main.java:220)
```
[I removed the Log4J2 plugin and tried again, and it worked just fine.](https://github.com/xXAndrew28Xx/HotswapAgent) I'm guessing its from it not checking if all classes necessary are present.

**Comment by sycyhy** [comment]
More information please, especially what dependencies and what version of the log4j2 you are using - I would think some really old version as this class is still present in the newest version (2.8.2).
