### ISSUE TITLE
run in centos fail

### ISSUE THREAD

**Issue by raduihys** [HotswapProjects/HotswapAgent#206]
**my hotswap-agent.jar compile in window,run in window is success,but run in  linux fail!!!**
``
HOTSWAP AGENT: 10:57:5.236 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, Mojarra, MyFaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Proxy, WebObjects, Weld, JBossModules, Resteasy, ResteasyRegistry, Gae, Deltaspike, JavaBeans]
HOTSWAP AGENT: 10:57:5.242 ERROR (org.hotswap.agent.annotation.handler.InitHandler) - InvocationTargetException in init method on plugin class org.hotswap.agent.plugin.hotswapper.HotswapperPlugin.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.annotation.handler.InitHandler.invokeInitMethod(InitHandler.java:86)
	at org.hotswap.agent.annotation.handler.InitHandler.access$100(InitHandler.java:28)
	at org.hotswap.agent.annotation.handler.InitHandler$1.onInit(InitHandler.java:110)
	at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:175)
	at org.hotswap.agent.util.HotswapTransformer.ensureClassLoaderInitialized(HotswapTransformer.java:228)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:165)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
Caused by: java.lang.IllegalArgumentException: Cannot initialize plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin', appClassLoader is null.
	at org.hotswap.agent.config.PluginRegistry.initializePlugin(PluginRegistry.java:137)
	at org.hotswap.agent.util.PluginManagerInvoker.callInitializePlugin(PluginManagerInvoker.java:26)
	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin.init(HotswapperPlugin.java:127)
	... 12 more
``

**Comment by skybber** [comment]
Could you supply your configuration ?

**Comment by edudant** [comment]
@skybber the reason could be only that classLoader is null for transform method - according to the documentation it can be for bootstrap classLoader. Should we check null classLoader and quit transformation immediately?

    @Override
    public byte[] transform(final ClassLoader classLoader, String className, Class<?> redefiningClass,
                            final ProtectionDomain protectionDomain, byte[] bytes) throws IllegalClassFormatException {
        LOGGER.trace("Transform on class '{}' @{} redefiningClass '{}'.", className, classLoader, redefiningClass);
