### ISSUE TITLE
Spring + Resteasy

### ISSUE THREAD

**Issue by lRawd** [HotswapProjects/HotswapAgent#209]
I am running Spring 4.3.2 with Resteasy 3.1.1. When I modify one of my Resteasy web service beans, the class is reloaded but all my autowired spring beans are now null in that class.

**Comment by lRawd** [comment]
Attempted to disable ReasteasyRegistry plugin but that causes the following exception to be thrown when a rest resource is accessed:
```
Caused by: java.lang.IllegalArgumentException: Plugin class org.hotswap.agent.plugin.resteasy.ResteasyRegistryPlugin is not initialized in classloader ModuleClassLoader for Module "deployment.mistic-web.war:main" from Service Module Loader.
	at org.hotswap.agent.config.PluginRegistry.getPlugin(PluginRegistry.java:199)
	at org.hotswap.agent.config.PluginManager.getPlugin(PluginManager.java:77)
	at org.hotswap.agent.config.PluginManager.getPlugin(PluginManager.java:62)
	... 91 more
```

Recompiling HA without the plugin works, and I keep my spring beans, but I am obviously unable to add/modify Paths.

**Comment by skybber** [comment]
Did you try disable plugin using global option 
`-javaagent:hotswapa-gent.jar=disablePlugin=ReasteasyRegistry` ?

**Comment by lRawd** [comment]
I was using the properties file. Using the global option seems to work for properly disabling the plugin.
