### ISSUE TITLE
Changing Spring @RequestMapping values / controller method signature causes Exceptions.

### ISSUE THREAD

**Issue by danmofo** [HotswapProjects/HotswapAgent#216]
First of all - this is a great piece of software; class reloading is working great in a basic Java servlet project and makes Java web development somewhat more bearable.

I'm having issues however when trying to integrate into an existing Spring MVC web application. Here are the versions of software:
- **Java**, 1.8.0_121
- **DCEVM**, light, update 144, build 2
- **HotswapAgent**, 1.1 (have also tried 1.0)
- **Spring**, 4.2.5
- **Apache Tomcat**, 7.0.42 running inside a VM with the following options: `-XXaltjvm=dcevm -javaagent:/vagrant/java/hotswap-agent.jar -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000`

Also note that Tomcat lives inside a VM on my machine, I'm not using the IDE to manage the server.

Some things work, like changing a method body inside a controller - I can add a bunch of logging statements and see them after reloading my page without a Tomcat restart. What is strange is that I get the following ERROR message in the logs, even though the change is reflected (I've included the surrounding debug messages if that helps):

	HOTSWAP AGENT: 19:53:47.501 DEBUG (org.hotswap.agent.plugin.javabeans.JavaBeansPlugin) - Flushing com.x
	xxxxxx.controller.OfferController
	HOTSWAP AGENT: 19:53:47.765 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing ClassPathBeanRefreshCommand{appClassLoader=WebappClassLoader
	  context: /
	  delegate: false
	  repositories:
	    /WEB-INF/classes/
	----------> Parent Classloader:
	org.apache.catalina.loader.StandardClassLoader@2362f559
	, basePackage='com.xxxxxxx.controller', className='com/xxxxxxx/controller/OfferController'}
	HOTSWAP AGENT: 19:53:47.767 DEBUG (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Executing ClassPathBeanDefinitionScannerAgent.refreshClass('com/xxxxxxx/controller/OfferController')
	HOTSWAP AGENT: 19:53:47.796 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - basePackage 'com.xxxxxxx.controller' not associated with any scannerAgent

As soon as I change controller method signatures (for example, lets say I add @RequestParam(value=...) to the method signature), it throws the following exception on page load:

`org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.InternalError: invoke`

Here's the full stack trace:

	org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.InternalError: invoke
		 at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1302)
		 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:977)
		 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
		 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
		 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
		 at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
		 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
		 at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
		 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
		 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
		 at com.xxxxxx.view.filter.VelocityFilter.doFilter(VelocityFilter.java:63)
		 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
		 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
		 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
		 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
		 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
		 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
		 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
		 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
		 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
		 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
		 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
		 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
		 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	 at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.InternalError: invoke
		 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		 at java.lang.reflect.Method.invoke(Method.java:498)
		 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
		 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
		 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
		 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
		 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
		 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
		 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
		 ... 24 more

At this point the controller method becomes unusable and I have to restart Tomcat to resolve it. I have tried disabling various plugins based on my Google searches (Hibernate and Proxy) to no effect.

I imagine the problem lies within my Spring configuration files since I read online about many people using this successfully for Spring MVC projects, but I'm not really sure what configuration would cause this.

If there is any more information I can provide I'd be more than happy to do so.

**Comment by Nick-The-Uncharted** [comment]
Can you try to download the latest source and build a jar from it?
On my end this works perfectly.

**Comment by FrederickIge** [comment]
anyone find a fix for this? I also get thus problem

**Comment by edudant** [comment]
Please try version 1.3.0
