### ISSUE TITLE
JDWP exit error when using multiple java agents

### ISSUE THREAD

**Issue by ronvanpol** [HotswapProjects/HotswapAgent#230]
I am getting the following error when I try to use DCEVM with multiple java agents:

```
JDWP exit error JVMTI_ERROR_INVALID_THREAD(10): cannot get thread local storage [threadControl.c:195]
FATAL ERROR in native method: JDWP cannot get thread local storage, jvmtiError=JVMTI_ERROR_INVALID_THREAD(10)
	at java.lang.Thread.currentThread(Native Method)
	at java.lang.Thread.interrupted(Thread.java:947)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.checkInterruptWhileWaiting(AbstractQueuedSynchronizer.java:2002)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2079)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.processEvents(AbstractNIO2Watcher.java:220)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.access$100(AbstractNIO2Watcher.java:64)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher$1.run(AbstractNIO2Watcher.java:289)
Disconnected from server
```

I am trying to combine the hotswap-agent together with another javaagent (for instance xRebel or Stackify). My vm startup parameters are: 

-XXaltjvm=dcevm -javaagent:D:\java\hotswap-agent-1.0.jar -javaagent:D:\Stackify\lib\stackify-java-apm.jar

When using a regular VM with multiple agents (hotswap + xrebel/stackify) everything works properly.

**Comment by edudant** [comment]
Please move this issue to DCEVM project: https://github.com/dcevm/dcevm
