### ISSUE TITLE
Error Integrating HotswapAgent and Jersey 2.25

### ISSUE THREAD

**Issue by AlbozDroid** [HotswapProjects/HotswapAgent#247]
Hi, 

I'm using the latest version of HotswapAgent trying to change a Jersey end point (Jersey 2.25) and then to hot-deploy, but I get the following error:

```
 HOTSWAP AGENT: 14:28:34.387 ERROR (org.hotswap.agent.plugin.jersey2.Jersey2Plugin) - Error reloading Jersey Container.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.jersey2.Jersey2Plugin$1.executeCommand(Jersey2Plugin.java:173)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.util.concurrent.RejectedExecutionException: java.io.NotSerializableException: org.glassfish.jersey.server.internal.monitoring.MonitoringStatisticsProcessor$1
	at weblogic.work.concurrent.TaskWrapper.<init>(TaskWrapper.java:84)
	at weblogic.work.concurrent.TaskWrapper.<init>(TaskWrapper.java:102)
	at weblogic.work.concurrent.ManagedScheduledExecutorServiceImpl.periodSchedule(ManagedScheduledExecutorServiceImpl.java:161)
	at weblogic.work.concurrent.ManagedScheduledExecutorServiceImpl.scheduleWithFixedDelay(ManagedScheduledExecutorServiceImpl.java:219)
	at weblogic.jaxrs.concurrent.WeblogicScheduledExecutorServiceProvider$ManagedScheduledExecutorServiceWrapper.scheduleWithFixedDelay(WeblogicScheduledExecutorServiceProvider.java:101)
	at org.glassfish.jersey.server.internal.monitoring.MonitoringStatisticsProcessor.startMonitoringWorker(MonitoringStatisticsProcessor.java:112)
	at org.glassfish.jersey.server.internal.monitoring.MonitoringEventListener.onEvent(MonitoringEventListener.java:213)
	at org.glassfish.jersey.server.internal.monitoring.CompositeApplicationEventListener.onEvent(CompositeApplicationEventListener.java:74)
	at org.glassfish.jersey.server.internal.monitoring.MonitoringContainerListener.onReload(MonitoringContainerListener.java:88)
	at org.glassfish.jersey.server.ApplicationHandler.onReload(ApplicationHandler.java:1187)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:603)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:593)
	... 6 more
Caused by: java.io.NotSerializableException: org.glassfish.jersey.server.internal.monitoring.MonitoringStatisticsProcessor$1
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at weblogic.work.concurrent.utils.ConcurrentUtils.serializeByClassloader(ConcurrentUtils.java:162)
	at weblogic.work.concurrent.TaskWrapper.<init>(TaskWrapper.java:81)
	... 17 more
```

**Comment by skybber** [comment]
I'm skeptical about it can be solved from HotswapAgent. Is it possible to disable monitoring statistics in Jersey?

**Comment by AlbozDroid** [comment]
I did disable the WebLogic statistics for Jersey which made the error go away but the Agent is not working as it should.

I just created a new Class with one static method that returns a String. On my Jersey endpoint I call that class and I keep getting "ClassNotFoundException" because apparently the HotDeploy of new class doesn't succeed...

I've got the following  warnings before the exception:
```
HOTSWAP AGENT: 14:48:10.036 INFO (org.hotswap.agent.plugin.jersey2.Jersey2Plugin) - Reloaded Jersey Containers
May 31, 2018 2:48:10 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Cannot create new registration for component type class weblogic.jaxrs.monitoring.JaxRsMonitoringListener: Existing previous registration found for the type.
WARNING: Cannot create new registration for component type class weblogic.jaxrs.server.internal.ChunkedOutputWriter: Existing previous registration found for the type.
WARNING: Cannot create new registration for component type class weblogic.jaxrs.server.internal.WeblogicServerAutoDiscoverable$ExecutorServiceBinder: Existing previous registration found for the type.

<31-May-2018 14:48:10 o'clock BST> <Warning> <org.glassfish.jersey.internal.Errors> <BEA-000000> <The following warnings have been detected: WARNING: Cannot create new registration for component type class weblogic.jaxrs.monitoring.JaxRsMonitoringListener: Existing previous registration found for the type.
WARNING: Cannot create new registration for component type class weblogic.jaxrs.server.internal.ChunkedOutputWriter: Existing previous registration found for the type.
WARNING: Cannot create new registration for component type class weblogic.jaxrs.server.internal.WeblogicServerAutoDiscoverable$ExecutorServiceBinder: Existing previous registration found for the type.

```

**Comment by skybber** [comment]
Jersey reload is triggered only on class redefinition now:

https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-jersey2-plugin/src/main/java/org/hotswap/agent/plugin/jersey2/Jersey2Plugin.java#L132

**Comment by AlbozDroid** [comment]
I'm changing the Jersey EndPoint by adding a call to an external class, no?. Shouldn't this trigger the load of the new class?.

Does this mean that I can only change existing methods and existing classes for hot-deploy to work?
