### ISSUE TITLE
Problem when adding a method to a class

### ISSUE THREAD

**Issue by tbigueres** [HotswapProjects/HotswapAgent#261]
Hi, 

I'm using Google Juice and I'm trying to integrate Hotswapagent. 
It works when I change the body of a method, but when I try to add a method to a class I have this issue : 

`HOTSWAP AGENT: 12:36:05.012 ERROR (org.hotswap.agent.plugin.jersey2.Jersey2Plugin) - Error reloading Jersey Container.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.jersey2.Jersey2Plugin$1.executeCommand(Jersey2Plugin.java:173)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(GuiceServiceLocator-1,0,399520595) has been shut down
	at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2264)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:731)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:700)
	at com.squarespace.jersey2.guice.GuiceServiceLocatorGeneratorImpl.create(GuiceServiceLocatorGeneratorImpl.java:72)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:270)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:230)
	at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
	at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:123)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:329)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:339)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:601)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:593)
	... 6 more

HOTSWAP AGENT: 12:36:05.041 ERROR (org.hotswap.agent.plugin.jersey2.Jersey2Plugin) - Error reloading Jersey Container.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.jersey2.Jersey2Plugin$1.executeCommand(Jersey2Plugin.java:173)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(GuiceServiceLocator-1,0,399520595) has been shut down
	at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2264)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1021)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.preDestroy(ServiceLocatorImpl.java:1013)
	at org.glassfish.jersey.server.ApplicationHandler.onShutdown(ApplicationHandler.java:1186)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:599)
	at org.glassfish.jersey.servlet.ServletContainer.reload(ServletContainer.java:593)
	... 6 more`

Do you know what I can do to fix this ? Is it a hotswapagent problem ? Is hotswapagent not working with Google Juice ? 

Thanks

**Comment by skybber** [comment]
Google Juice is not supported yet.

**Comment by tbigueres** [comment]
Ok thanks

**Comment by tbigueres** [comment]
Just to know, do you have an approximative date where it will be ? Or is it not in the roadmap ?

**Comment by skybber** [comment]
We have now no intention to do it now. Usually we support only frameworks which we are working with.  Its hard to maintain something you are not using regularly...

**Comment by tbigueres** [comment]
Ok, and do you know a solution that we could use to handle hot reloading with Google Juice ?

**Comment by skybber** [comment]
Unfortunately I'm not expert on Google Juice , so I can't suggest any solution.
