### ISSUE TITLE
OpenJDK 11 java.lang.NullPointerException: null at org.hotswap.agent.javassist.util.proxy.SecurityActions.setAccessible

### ISSUE THREAD

**Issue by markiewb** [HotswapProjects/HotswapAgent#267]
I have a dead simple spring boot application which runs using JDK11.
But once I activate fakereplace as javaagent the application does not start anymore. 

Regarding the stacktrace the issue is javaassist-related
```
/Users/markiewb/.sdkman/candidates/java/11.0.0-open/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:51436,suspend=y,server=n -javaagent:/Users/markiewb/IdeaProjects/2048/hotswap-agent-1.3.0.jar -XX:TieredStopAtLevel=1 -noverify -Dspring.main.banner-mode=OFF -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=51435 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:/Users/markiewb/Library/Caches/IntelliJIdea2018.2/captureAgent/debugger-agent.jar=file:/private/var/folders/t6/dz53ljws0bj3rcxpksy0tnc40000gn/T/capture.props -Dfile.encoding=UTF-8 -classpath "/Users/markiewb/IdeaProjects/2048/target/classes:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.0.3.RELEASE/spring-boot-starter-web-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter/2.0.3.RELEASE/spring-boot-starter-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot/2.0.3.RELEASE/spring-boot-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.0.3.RELEASE/spring-boot-autoconfigure-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.0.3.RELEASE/spring-boot-starter-logging-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/markiewb/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/markiewb/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.10.0/log4j-to-slf4j-2.10.0.jar:/Users/markiewb/.m2/repository/org/apache/logging/log4j/log4j-api/2.10.0/log4j-api-2.10.0.jar:/Users/markiewb/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar:/Users/markiewb/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/Users/markiewb/.m2/repository/org/yaml/snakeyaml/1.19/snakeyaml-1.19.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.0.3.RELEASE/spring-boot-starter-json-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.9.6/jackson-datatype-jdk8-2.9.6.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.6/jackson-datatype-jsr310-2.9.6.jar:/Users/markiewb/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.9.6/jackson-module-parameter-names-2.9.6.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.0.3.RELEASE/spring-boot-starter-tomcat-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.31/tomcat-embed-core-8.5.31.jar:/Users/markiewb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.31/tomcat-embed-el-8.5.31.jar:/Users/markiewb/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.31/tomcat-embed-websocket-8.5.31.jar:/Users/markiewb/.m2/repository/org/hibernate/validator/hibernate-validator/6.0.10.Final/hibernate-validator-6.0.10.Final.jar:/Users/markiewb/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar:/Users/markiewb/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar:/Users/markiewb/.m2/repository/com/fasterxml/classmate/1.3.4/classmate-1.3.4.jar:/Users/markiewb/.m2/repository/org/springframework/spring-web/5.0.7.RELEASE/spring-web-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-beans/5.0.7.RELEASE/spring-beans-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-webmvc/5.0.7.RELEASE/spring-webmvc-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-aop/5.0.7.RELEASE/spring-aop-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-context/5.0.7.RELEASE/spring-context-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-expression/5.0.7.RELEASE/spring-expression-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/boot/spring-boot-starter-thymeleaf/2.0.3.RELEASE/spring-boot-starter-thymeleaf-2.0.3.RELEASE.jar:/Users/markiewb/.m2/repository/org/thymeleaf/thymeleaf-spring5/3.0.9.RELEASE/thymeleaf-spring5-3.0.9.RELEASE.jar:/Users/markiewb/.m2/repository/org/thymeleaf/thymeleaf/3.0.9.RELEASE/thymeleaf-3.0.9.RELEASE.jar:/Users/markiewb/.m2/repository/org/attoparser/attoparser/2.0.4.RELEASE/attoparser-2.0.4.RELEASE.jar:/Users/markiewb/.m2/repository/org/unbescape/unbescape/1.1.5.RELEASE/unbescape-1.1.5.RELEASE.jar:/Users/markiewb/.m2/repository/org/thymeleaf/extras/thymeleaf-extras-java8time/3.0.1.RELEASE/thymeleaf-extras-java8time-3.0.1.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-core/5.0.7.RELEASE/spring-core-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/springframework/spring-jcl/5.0.7.RELEASE/spring-jcl-5.0.7.RELEASE.jar:/Users/markiewb/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/Users/markiewb/.m2/repository/org/webjars/bootstrap/3.3.6/bootstrap-3.3.6.jar:/Users/markiewb/.m2/repository/org/webjars/jquery/1.11.1/jquery-1.11.1.jar:/Users/markiewb/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-1/182.4129.33/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" integration.Application
Connected to the target VM, address: '127.0.0.1:51436', transport: 'socket'
HOTSWAP AGENT: 21:00:20.593 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 21:00:20.906 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, AnonymousClassPatch, ClassInitPlugin, WatchResources, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin]
HOTSWAP AGENT: 21:00:21.897 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.spring.SpringPlugin' initialized in ClassLoader 'jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15'.
HOTSWAP AGENT: 21:00:21.897 INFO (org.hotswap.agent.plugin.spring.SpringPlugin) - Spring plugin initialized - Spring core version '5.0.7.RELEASE'
2018-10-08 21:00:21.941  INFO 2660 --- [           main] integration.Application                  : Starting Application on Bennos-MacBook-Pro.local with PID 2660 (/Users/markiewb/IdeaProjects/2048/target/classes started by markiewb in /Users/markiewb/IdeaProjects/2048)
2018-10-08 21:00:21.943  INFO 2660 --- [           main] integration.Application                  : No active profile set, falling back to default profiles: default
2018-10-08 21:00:21.990  INFO 2660 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@493dfb8e: startup date [Mon Oct 08 21:00:21 CEST 2018]; root of context hierarchy
HOTSWAP AGENT: 21:00:21.991 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hibernate.HibernatePlugin' initialized in ClassLoader 'jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15'.
HOTSWAP AGENT: 21:00:22.117 INFO (org.hotswap.agent.plugin.spring.SpringPlugin) - Registering basePackage integration
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/markiewb/.m2/repository/org/springframework/spring-core/5.0.7.RELEASE/spring-core-5.0.7.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-10-08 21:00:22.768  WARN 2660 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Unexpected exception during bean creation; nested exception is java.lang.NullPointerException
2018-10-08 21:00:22.777  INFO 2660 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-10-08 21:00:22.787 ERROR 2660 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Unexpected exception during bean creation; nested exception is java.lang.NullPointerException
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at integration.Application.main(Application.java:10) ~[classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tomcatServletWebServerFactory' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/ServletWebServerFactoryConfiguration$EmbeddedTomcat.class]: Unexpected exception during bean creation; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
Disconnected from the target VM, address: '127.0.0.1:51436', transport: 'socket'
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:214) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:152) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	... 8 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.hotswap.agent.javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:153) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:136) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1143) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.javassist.CtClass.toClass(CtClass.java:1316) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.buildProxyCallbackClass(EnhancerProxyCreater.java:299) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.getProxyCreationMethod(EnhancerProxyCreater.java:131) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.doCreate(EnhancerProxyCreater.java:108) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.create(EnhancerProxyCreater.java:81) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.createProxy(EnhancerProxyCreater.java:77) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.hotswap.agent.plugin.spring.getbean.ProxyReplacer.register(ProxyReplacer.java:82) ~[hotswap-agent-1.3.0.jar:1.3.0]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1256) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1105) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 16 common frames omitted


Process finished with exit code 1
```

**Comment by skybber** [comment]
You need dcevm11 to run HotswapAgent with java11. But it is not finished.

**Comment by markiewb** [comment]
@skybber It is a javassist issue 
* https://github.com/jboss-javassist/javassist/issues/194
* https://issues.jboss.org/browse/JASSIST-271

**Comment by markiewb** [comment]
Even when I build the agent itself using openjdk11 the build fails 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hotswap-agent-core: Compilation failure
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[90,41] cannot find symbol
[ERROR]   symbol:   method defineClass(java.lang.String,byte[],int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
[ERROR]   location: variable sunMiscUnsafe of type sun.misc.Unsafe
[ERROR] -> [Help 1]
```

See the results at https://travis-ci.com/markiewb/HotswapAgent/jobs/150459290 for the updated travis file https://github.com/markiewb/HotswapAgent/blob/patch-1/.travis.yml

Again a javaassist related issue.

**Comment by skybber** [comment]
Yep, HotswapAgent is still not finished for java11, it has embedded Javassist for j10...

**Comment by noguespi** [comment]
It looks like javassist for j11 has just been released https://github.com/jboss-javassist/javassist/releases

How HotswapAgent use javassist ? It looks like it is not a pom dependency.

**Comment by skybber** [comment]
It is embedded in the HA core. I've already checked it. Javassist for java11 uses directly j11 api, therefore it must be compiled with j11, we have to chage hotswapagent's building JDK platform from j8 to j11.

**Comment by skybber** [comment]
Dcevm11 (openjdk-hotswap) binaries with embeded HA 1.3.1.SNAPSHOT are available [here](https://github.com/HotswapProjects/openjdk-jdk11/releases), could you check it?

**Comment by markiewb** [comment]
> Dcevm11 (openjdk-hotswap) binaries with embeded HA 1.3.1.SNAPSHOT are available [here](https://github.com/HotswapProjects/openjdk-jdk11/releases), could you check it please?

Yes. That that distribution worked in my manual smoketests.
