### ISSUE TITLE
HA-Agent not detecting changes to Class in JBoss + EnhancerProxyCreater can't create proxy! [1.3.1 Snapshot]

### ISSUE THREAD

**Issue by MrABKhan** [HotswapProjects/HotswapAgent#275]
**Context :**
I have deployed HA on Jboss Multi-Module project and I am using the Intelli J plugin with HA 1.3.1 snapshot!
I've added the extraClasspath in HotswapAgent and along with that in Jboss through the deployment descriptor.

**Problem with File Changes not being detected**
The Problem is that after deploying the application, HA is not being able to detect the changes that I make to a particular class file; yes I have checked the intelli-j plugin on another test project and also have enabled intellij for this run configuration so that is not an issue.
I get no class reloaded message or anything. Just the class gets rebuild by intelli-j, not regular log message that HA usually does.

I think the HA watcher might be responsible for this  but I don't know for certain.

**Problem with EnhancerProxyCreater**
I get the following warning messaging during the deployment of the application. I do not understand what it is or whether it might be responsible for the problem above but I will state it here.

This is the message I get for different classes during deployment.
**org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater**
```
"Can't create proxy for " + bean.getClass().getSuperclass()
                  + " because there is no default constructor,"
                   + " which means your non-singleton bean created before won't get rewired with new props when update class."
```

If you guys need any other debug information or anything, I'd post it here. Thank You!

**Comment by MrABKhan** [comment]
Okay after some debugging I found that the main reason my classes are not being hotswapped because the proxy classes aren't being constructed for these classes.

**Comment by skybber** [comment]
So it is not HA issue?

**Comment by MrABKhan** [comment]
I mean the reason why my classes aren't being updated when I press build is because Hotswap Agent EnhancerProxyCreater can't create the required proxy for it.


I tried testing this with the classes showed in the log, e.g

```
`14:12:52,580 INFO  [stdout] (ServerService Thread Pool -- 24) HOTSWAP AGENT: 14:12:52.580 WARNING (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - Can't create proxy for class com.etcbase.sfc.webservice.SendMailTestWebServiceImpl because there is no default constructor, which means your non-singleton bean created before won't get rewired with new props when update class.

14:12:52,583 INFO  [stdout] (ServerService Thread Pool -- 24) HOTSWAP AGENT: 14:12:52.583 WARNING (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - Can't create proxy for class com.etcbase.sfc.webservice.AuthenticationLoadTestWebServiceImpl because there is no default constructor, which means your non-singleton bean created before won't get rewired with new props when update class.

14:12:52,586 INFO  [stdout] (ServerService Thread Pool -- 24) HOTSWAP AGENT: 14:12:52.586 WARNING (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - Can't create proxy for class com.etcbase.sfc.webservice.SessionWebServiceImpl because there is no default constructor, which means your non-singleton bean created before won't get rewired with new props when update class.
`
```


I tried updating the classes mentioned in the above warnings for example **SendMailTestWebServiceImpl** , updated it and changed it and nothing happened.

This is because in the warning above it says
`Can't create proxy for class com.etcbase.sfc.webservice.SessionWebServiceImpl because there is no default constructor, `**which means your non-singleton bean created before won't get rewired with new props when update class**.

Thus HA is unable to create proxies that will allow it to update the required classes..or this is what I understood...

**Comment by MrABKhan** [comment]
I did some more debugging in the EnhancerProxyCreater method. Added the line _LOGGER.warning(e.toString());_

```
private Object doCreate(Object beanFactry, Object bean, Class<?>[] paramClasses, Object[] paramValues) {
		try {
            Method proxyCreater = getProxyCreationMethod(bean);
            if (proxyCreater == null) {
                return bean;
            } else {
				return proxyCreater.invoke(null,beanFactry, bean, paramClasses, paramValues);
            }
        } catch (IllegalArgumentException | InvocationTargetException e) {


//            LOGGER.warning("Can't create proxy for " + bean.getClass().getSuperclass()
//                    + " because there is no default constructor,"
//                    + " which means your non-singleton bean created before won't get rewired with new props when update class.");

			LOGGER.warning(e.toString());

            return bean;
        } catch (IllegalAccessException | CannotCompileException | NotFoundException e) {
            LOGGER.error("Creating a proxy failed", e);
            throw new RuntimeException(e);
        }
	}
```


It seems I always throw the **InvocationTargetException**
```
INFO  [stdout] (ServerService Thread Pool -- 4) HOTSWAP AGENT: 15:36:08.227 WARNING (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - class java.lang.reflect.InvocationTargetException
```

Can anyone suggest why is this being caused in this function?

**Comment by skybber** [comment]
Unfortunately, the HA log message is not very descriptive, could you try this form?
			LOGGER.warning("error", e);

**Comment by MrABKhan** [comment]
Done.

Here's what I get for most classes now, it seems that it can't find the class.

```
HOTSWAP AGENT: 10:49:35.672 ERROR (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - Can't create proxy for class com.etcbase.sfc.util.IdManagerImpl because there is no default constructor, which means your non-singleton bean created before won't get rewired with new props when update class.
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) HOTSWAP AGENT: 10:49:35.673 WARNING (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - error
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) java.lang.reflect.InvocationTargetException
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.lang.reflect.Method.invoke(Method.java:498)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.doCreate(EnhancerProxyCreater.java:114)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.create(EnhancerProxyCreater.java:83)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.createProxy(EnhancerProxyCreater.java:79)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.hotswap.agent.plugin.spring.getbean.ProxyReplacer.register(ProxyReplacer.java:85)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1316)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1282)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
10:49:35,673 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
10:49:35,675 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
10:49:35,676 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:205)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
10:49:35,677 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at java.lang.Thread.run(Thread.java:748)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) Caused by: org.springframework.objenesis.ObjenesisException: java.lang.NoClassDefFoundError: Could not initialize class org.springframework.objenesis.instantiator.util.UnsafeUtils
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.objenesis.SpringObjenesis.newInstantiatorOf(SpringObjenesis.java:149)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.objenesis.SpringObjenesis.newInstance(SpringObjenesis.java:100)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at HotswapAgentSpringBeanProxy_1796692748.create(HotswapAgentSpringBeanProxy_1796692748.java)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	... 92 more
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.springframework.objenesis.instantiator.util.UnsafeUtils
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.objenesis.instantiator.sun.UnsafeFactoryInstantiator.<init>(UnsafeFactoryInstantiator.java:43)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:98)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	at org.springframework.objenesis.SpringObjenesis.newInstantiatorOf(SpringObjenesis.java:125)
10:49:35,678 INFO  [stdout] (ServerService Thread Pool -- 19) 	... 94 more
```

**Comment by MrABKhan** [comment]
It's weird because I added all the classpaths to hotswap-agent's extraClasspath.

**Comment by skybber** [comment]
Are you using java11? UnsafeUtils is not acessible from used classLoader (loader field inEnhancerProxyCreater):
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.springframework.objenesis.instantiator.util.UnsafeUtils
```
So there should be used another one. I think we're not able solve it without good simple multiear Spring example project. Could you please create one?

**Comment by MrABKhan** [comment]
No, I'm using Java 8.

Yes I'll create a simple multi-ear spring project and update you then.

**Comment by MrABKhan** [comment]
I tested the same Jboss-module setup along with HA on a sample[ Spring MVC application](https://www.journaldev.com/14476/spring-mvc-example) as I couldn't find a sutiable example for an EAR.

Using the sample deployment descriptor and shared libraries, It didn't call the EnhancerProxyCreater function of creating a spring-proxy( I had debug enable in hotswap logging).

It gave me the following error after I press `Ctrl+Alt+F9` :  
```
ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - basePackage 'com.journaldev.spring' not associated with any scannerAgent
```
**Extended Log After Hot-Deployment Key**
```170 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 11:20:04.170 DEBUG (org.hotswap.agent.plugin.jdk.JdkPlugin) - Flushing com.journaldev.spring.controller.HomeController from introspector
11:20:04,172 INFO  [stdout] (JDWP Transport Listener: dt_socket) HOTSWAP AGENT: 11:20:04.172 DEBUG (org.hotswap.agent.plugin.jdk.JdkPlugin) - Flushing com.journaldev.spring.controller.HomeController from ObjectStreamClass caches
11:20:05,339 INFO  [stdout] (Thread-3) HOTSWAP AGENT: 11:20:05.338 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing ClassPathBeanRefreshCommand{appClassLoader=ModuleClassLoader for Module "deployment.spring-mvc-example.war" from Service Module Loader, basePackage='com.journaldev.spring', className='com/journaldev/spring/controller/HomeController'}
11:20:05,369 INFO  [stdout] (Thread-3) HOTSWAP AGENT: 11:20:05.343 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing org.hotswap.agent.plugin.hibernate.HibernatePlugin$1@cb3212b
11:20:05,373 INFO  [stdout] (Thread-3) HOTSWAP AGENT: 11:20:05.372 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing PurgeWildFlyBeanELResolverCacheCommand{appClassLoader=ModuleClassLoader for Module "deployment.spring-mvc-example.war" from Service Module Loader}
11:20:05,383 INFO  [stdout] (Thread-290) HOTSWAP AGENT: 11:20:05.344 DEBUG (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Executing ClassPathBeanDefinitionScannerAgent.refreshClass('com/journaldev/spring/controller/HomeController')
11:20:05,387 INFO  [stdout] (Thread-290) HOTSWAP AGENT: 11:20:05.386 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - basePackage 'com.journaldev.spring' not associated with any scannerAgent
11:20:05,396 INFO  [stdout] (Thread-292) HOTSWAP AGENT: 11:20:05.391 INFO (org.hotswap.agent.plugin.wildfly.el.PurgeWildFlyBeanELResolverCacheCommand) - Cleaning  BeanPropertiesCache com.journaldev.spring.controller.HomeController ModuleClassLoader for Module "deployment.spring-mvc-example.war" from Service Module Loader.
11:20:05,414 INFO  [stdout] (Thread-291) HOTSWAP AGENT: 11:20:05.391 DEBUG (org.hotswap.agent.plugin.hibernate.HibernatePlugin) - Refreshing BeanMetaDataManagerCache/AnnotatedMetaDataProvider cache.
11:20:05,432 INFO  [stdout] (Thread-291) HOTSWAP AGENT: 11:20:05.432 DEBUG (org.hotswap.agent.plugin.hibernate.HibernatePlugin) - Invoking org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.__resetCache on org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider@1a7f762b
11:20:05,432 INFO  [stdout] (Thread-291) HOTSWAP AGENT: 11:20:05.432 DEBUG (org.hotswap.agent.plugin.hibernate.HibernatePlugin) - Invoking org.hibernate.validator.internal.metadata.BeanMetaDataManager.__resetCache on org.hibernate.validator.internal.metadata.BeanMetaDataManager@2cb8b636

```


Although this error does enable me to add fields and methods but prevents me from hot-swapping when I use Auto-wiring. I have opened an issue on this before and updated it now. Please do have a look at it.

#272 



_Interesting thing I noticed in the Debug Log, that maybe of help to you i think._
```
10:39:55,798 INFO  [stdout] (ServerService Thread Pool -- 20) HOTSWAP AGENT: 10:39:55.798 INFO (org.hotswap.agent.plugin.spring.SpringPlugin) - Registering basePackage com.journaldev.spring
10:41:55,764 INFO  [stdout] (Thread-3) HOTSWAP AGENT: 10:41:55.751 DEBUG (org.hotswap.agent.command.impl.SchedulerImpl) - Executing ClassPathBeanRefreshCommand{appClassLoader=ModuleClassLoader for Module "deployment.spring-mvc-example.war" from Service Module Loader, basePackage='com.journaldev.spring', className='com/journaldev/spring/controller/HomeController'}
(Thread-285) HOTSWAP AGENT: 10:41:55.822 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent) - basePackage 'com.journaldev.spring' not associated with any scannerAgent
```

**Comment by savas127** [comment]
Hello,

To solve "Could not initialize class org.springframework.objenesis.instantiator.util.UnsafeUtils" issue, please add followings to your jboss module.xml file. UnsafeUtils class has a static initialization block that references to sun.misc.Unsafe.

    	<module name="sun.jdk" export="true" >
        	<imports>
            	<include path="sun/misc/Unsafe" />
        	</imports>
    	</module>

Best Regards,

**Comment by MrABKhan** [comment]
Added the above to module.xml 


It Works! No more errors for can't create proxy.

@savas127  Thank You for this!  :1st_place_medal: 


Although I tried HotSwaping on the project after this, yet nothing happens.

**Log**
```
15:44:33,624 INFO  [stdout] (default task-2) HOTSWAP AGENT: 15:44:33.624 INFO (org.hotswap.agent.plugin.wildfly.el.WildFlyELResolverPlugin) - Patched JbossELResolver
15:44:33,629 INFO  [stdout] (default task-2) HOTSWAP AGENT: 15:44:33.629 INFO (org.hotswap.agent.plugin.wildfly.el.WildFlyELResolverPlugin) - WildFlyELResolverPlugin Initializing
15:44:33,630 INFO  [stdout] (default task-2) HOTSWAP AGENT: 15:44:33.629 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.wildfly.el.WildFlyELResolverPlugin' initialized in ClassLoader 'ModuleClassLoader for Module "deployment.dcs.war" from Service Module Loader'.
15:44:35,215 INFO  [stdout] (Thread-473) HOTSWAP AGENT: 15:44:35.215 WARNING (org.hotswap.agent.util.classloader.URLClassLoaderHelper) - Added extraClassPath URLs [file:/C:/gitrepo/sparrow/service/target/classes/com/etcbase/sfc/webservice/] to classLoader org.apache.jasper.servlet.JasperLoader@626c1369
```

**Comment by MrABKhan** [comment]
@skybber anyway I can force HA to watch a classpath or changes to a class!? 


HA still won't detect changes to my class after reloading. The Changes show up in the decompiled class file but nothing on the Jboss server, and yes I added the extra classpaths as well.
