### ISSUE TITLE
InvocationTargetException Log4j2Plugin

### ISSUE THREAD

**Issue by baba43** [HotswapProjects/HotswapAgent#282]
Hello,

when running a custom server jar with Hotswap Agent 1.3.0, it fails due to the following exception.

It's the first time I'm trying Hotswap Agent so I'm not sure if this problem is related to a specific Hotswap Agent version or to the server. However, I've no idea how to come around this.

```
HOTSWAP AGENT: 23:44:14.951 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 23:44:15.213 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, ClassInitPlugin, WatchResources, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin]
Loading libraries, please wait...
HOTSWAP AGENT: 23:44:15.788 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.log4j2.Log4j2Plugin' class 'org/apache/logging/log4j/core/LoggerContext'.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:193)
        at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:89)
        at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:184)
        at sun.instrument.TransformerManager.transform(Unknown Source)
        at sun.instrument.InstrumentationImpl.transform(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:537)
        at net.minecraft.server.v1_12_R1.MinecraftServer.<clinit>(MinecraftServer.java:56)
        at org.bukkit.craftbukkit.Main.main(Main.java:222)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.destroystokyo.paperclip.Utils.invoke(Utils.java:59)
        at com.destroystokyo.paperclip.Paperclip.run(Paperclip.java:155)
        at com.destroystokyo.paperclip.Main.main(Main.java:14)
Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] no such field: config
        at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:877)
        at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:792)
        at org.hotswap.agent.plugin.log4j2.Log4j2Plugin.registerConfigurator(Log4j2Plugin.java:129)
        ... 39 more
Caused by: compile error: no such field: config
        at org.hotswap.agent.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
        at org.hotswap.agent.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
        at org.hotswap.agent.javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
        at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
        at org.hotswap.agent.javassist.compiler.ast.Member.accept(Member.java:39)
        at org.hotswap.agent.javassist.compiler.TypeChecker.atArrayAssign(TypeChecker.java:262)
        at org.hotswap.agent.javassist.compiler.TypeChecker.atAssignExpr(TypeChecker.java:225)
        at org.hotswap.agent.javassist.compiler.ast.AssignExpr.accept(AssignExpr.java:39)
        at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
        at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
        at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
        at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at org.hotswap.agent.javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:204)
        at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:367)
        at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
        at org.hotswap.agent.javassist.compiler.Javac.compileStmnt(Javac.java:567)
        at org.hotswap.agent.javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:899)
        at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:851)
        ... 41 more
```

**Comment by baba43** [comment]
Problem can be fixed by applying `=disablePlugin=Log4j2` to the `-javaagent` path. 
Not sure if this will cause any troubles but it seems to work so far.

**Comment by skybber** [comment]
I've checked last log4j2 v2.11.1, it should work with it, which version are you using?
