### ISSUE TITLE
java.lang.IllegalStateException No value for key [org.apache.commons.dbcp2.BasicDataSource@2caf99c4]

### ISSUE THREAD

**Issue by ganeshatv** [HotswapProjects/HotswapAgent#287]
I am getting the below exception when running my SpringBoot App with hotswap-agent-1.3.1-SNAPSHOT.jar ,I am using Spring 4.3 version

`2019-01-17 13:51:24 INFO  c.c.p.p.p.e.PhysicalFileStorageEndpoint:apply[28] [Camel (camel-1) thread #30 - file:///app/work/eubank/SWIFT/in] - Storing file ACHAJ09123456789TAIN201403011152.ach from C:\app\work\eubank\SWIFT\in.
2019-01-17 13:51:41 ERROR c.c.p.p.p.e.AbstractEndpoint:apply[101] [Camel (camel-1) thread #30 - file:///app/work/eubank/SWIFT/in] - Error processing stp chain: 
java.lang.IllegalStateException: No value for key [org.apache.commons.dbcp2.BasicDataSource@2caf99c4] bound to thread [Camel (camel-1) thread #30 - file:///app/work/eubank/SWIFT/in]
	at org.springframework.transaction.support.TransactionSynchronizationManager.unbindResource(TransactionSynchronizationManager.java:210)
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCleanupAfterCompletion(DataSourceTransactionManager.java:351)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.cleanupAfterCompletion(AbstractPlatformTransactionManager.java:1017)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:811)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at com.cft.pts.payment.processing.chain.transaction.CurrPlatformTransactionManager.commit(CurrPlatformTransactionManager.java:29)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:504)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.cft.pts.payment.service.PhysicalFileServiceImpl$$EnhancerBySpringCGLIB$$9532048c.insert(<generated>)
	at com.cft.pts.payment.service.PhysicalFileServiceImpl$HOTSWAPAGENT_$$FastClassBySpringCGLIB$$62fa80d8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at HotswapSpringCallback_1796692748.intercept(HotswapSpringCallback_1796692748.java)
	at com.cft.pts.payment.service.PhysicalFileServiceImpl$HOTSWAPAGENT_$$EnhancerBySpringCGLIB$$bd385b09_10.insert(<generated>)
	at com.cft.pts.payment.processing.endpoint.PhysicalFileStorageEndpoint.apply(PhysicalFileStorageEndpoint.java:37)
	at com.cft.pts.payment.processing.endpoint.AbstractEndpoint.apply(AbstractEndpoint.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cft.pts.pm.EndpointPerformanceProfilingBeanPostProcessor.lambda$0(EndpointPerformanceProfilingBeanPostProcessor.java:63)
	at com.sun.proxy.$Proxy319.apply(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.spring.getbean.HotswapSpringInvocationHandler.doInvoke(HotswapSpringInvocationHandler.java:67)
	at org.hotswap.agent.plugin.spring.getbean.HotswapSpringInvocationHandler.invoke(HotswapSpringInvocationHandler.java:62)
	at com.sun.proxy.$Proxy320.apply(Unknown Source)
	at com.cft.pts.proc.chain.camel.ProcessorExecution.lambda$1(ProcessorExecution.java:61)
	at com.cft.pts.proc.chain.camel.ProcessorExecution.apply(ProcessorExecution.java:110)
	at com.cft.pts.proc.chain.camel.ProcessorImpl.process(ProcessorImpl.java:45)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:400)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:172)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220)
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:101)
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:542)
	at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:220)
	at org.apache.camel.spring.spi.TransactionErrorHandler$1.doInTransactionWithoutResult(TransactionErrorHandler.java:183)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.apache.camel.spring.spi.TransactionErrorHandler.doInTransactionTemplate(TransactionErrorHandler.java:176)
	at org.apache.camel.spring.spi.TransactionErrorHandler.processInTransaction(TransactionErrorHandler.java:136)
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:105)
	at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:197)
	at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:460)
	at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:227)
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:191)
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:175)
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:102)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Sejalgo** [comment]
hi,

am facing same issue
