### ISSUE TITLE
Watch loader is broken on java 11

### ISSUE THREAD

**Issue by ninja-** [HotswapProjects/HotswapAgent#307]
Watch loader crashes on java 11 with

```java
java.lang.NoSuchMethodException: org.hotswap.agent.javassist.util.proxy.jdk_internal_loader_URLClassPath_$$_jvst76b_0.<init>([Ljava.net.URL;)
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getConstructor(Class.java:2152)
	at org.hotswap.agent.util.classloader.URLClassLoaderHelper.setWatchResourceLoader(URLClassLoaderHelper.java:120)
	at org.hotswap.agent.plugin.watchResources.WatchResourcesPlugin.init(WatchResourcesPlugin.java:110)
	at org.hotswap.agent.plugin.watchResources.WatchResourcesPlugin.init(WatchResourcesPlugin.java:96)
```

there was a fix attempted to use a correct constructor, but looks like it missed the other part of code in the same file and it's still using the old url[] constructor...

https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/URLClassLoaderHelper.java#L94
https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/util/classloader/URLClassLoaderHelper.java#L120

EDIT: confirming fix works, might PR later

**Comment by ninja-** [comment]
that was quick...thanks ;)

**Comment by skybber** [comment]
Thanks for report ! Looks like pretty old bug, I've updated 1.3.1-SNAPSHOT
