### ISSUE TITLE
ConcurrentModificationException in ReflectionCommand

### ISSUE THREAD

**Issue by ninja-** [HotswapProjects/HotswapAgent#308]
```
[02:16:38 INFO]: HOTSWAP AGENT: 02:16:38.785 RELOAD (org.hotswap.agent.plugin.jvm.AnonymousClassPatchPlugin) - Class 'TestPlugin' has been enhanced with anonymous classes for hotswap.
[02:16:39 WARN]: Exception in thread "Thread-2" 
[02:16:39 WARN]: java.util.ConcurrentModificationException
[02:16:39 WARN]: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
[02:16:39 WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
[02:16:39 WARN]: 	at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1524)
[02:16:39 WARN]: 	at java.base/java.util.AbstractMap.hashCode(AbstractMap.java:526)
[02:16:39 WARN]: 	at java.base/java.util.AbstractList.hashCode(AbstractList.java:567)
[02:16:39 WARN]: 	at org.hotswap.agent.command.ReflectionCommand.hashCode(ReflectionCommand.java:232)
[02:16:39 WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
[02:16:39 WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$BaseIterator.remove(ConcurrentHashMap.java:3439)
[02:16:39 WARN]: 	at org.hotswap.agent.command.impl.SchedulerImpl.processCommands(SchedulerImpl.java:104)
[02:16:39 WARN]: 	at org.hotswap.agent.command.impl.SchedulerImpl.access$100(SchedulerImpl.java:39)
[02:16:39 WARN]: 	at org.hotswap.agent.command.impl.SchedulerImpl$2.run(SchedulerImpl.java:146)
```

JVM: Java 11

**Comment by ninja-** [comment]
well, this seems to be "solved" by not using the JNLP backend by not specifying the port
