### ISSUE TITLE
Error executin method hotswap in class org.hotswap.agent.plugin.hotswapper.HotswapperCommand

### ISSUE THREAD

**Issue by ninja-** [HotswapProjects/HotswapAgent#311]
This problem has been a deal breaker for me lately...
Basically I have a jar and when I want to hotswap, I unzip the jar to folder specified in jar's hotswap-agent.properties.

It can randomly result in this, and it keeps looping with this error forever.

```
23:54:48 [INFO] HOTSWAP AGENT: 23:54:48.524 ERROR (org.hotswap.agent.command.ReflectionCommand) - Error executin method hotswap in class org.hotswap.agent.plugin.hotswapper.HotswapperCommand

23:54:48 [INFO] java.lang.reflect.InvocationTargetException

23:54:48 [INFO] 	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)



23:54:48 [INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

23:54:48 [INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

23:54:48 [INFO] 	at org.hotswap.agent.command.ReflectionCommand.doExecuteReflectionCommand(ReflectionCommand.java:207)

23:54:48 [INFO] 	at org.hotswap.agent.command.ReflectionCommand.executeCommand(ReflectionCommand.java:168)

23:54:48 [INFO] 	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)

23:54:48 [INFO] Caused by: java.lang.RuntimeException: no such class: my_class_here

23:54:48 [INFO] 	at org.hotswap.agent.plugin.hotswapper.HotSwapperJpda.toRefType(HotSwapperJpda.java:220)

23:54:48 [INFO] 	at org.hotswap.agent.plugin.hotswapper.HotSwapperJpda.reload(HotSwapperJpda.java:210)

23:54:48 [INFO] 	at org.hotswap.agent.plugin.hotswapper.HotswapperCommand.hotswap(HotswapperCommand.java:67)

23:54:48 [INFO] 	... 6 more
```

**Comment by ninja-** [comment]
This might be related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8181144 and could trigger if application is not warmed up and it's not using all of its classes yet?

**Comment by ninja-** [comment]
Hm, I wasn't aware that there's an Instrumentation backend that does the same if you don't specify jnlp port, it seems to work much better
