### ISSUE TITLE
Hotswapper-plugin is not compatible to OpenJDK8

### ISSUE THREAD

**Issue by markiewb** [HotswapProjects/HotswapAgent#313]
The Hotswapper-plugin of the HotSwap-Agent is incompatible to OpenJDK8. It uses classes which are not available in OpenJDK8. The compilation fails. 

When you use the JDK11-build agent 1.3.1-SNAPSHOT (provided by the release section here at GitHub) running on OpenJDK8 (in detail AdoptOpenJDK) the Hotswapper-plugin fails at runtime. I have seen some strange JDI-related ClassNotFoundExceptions, which lead me to investigate and create this issue.

See the build against different JDKs in my TravisCI builds: https://travis-ci.com/markiewb/HotswapAgent

```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)
Maven home: /usr/local/maven-3.6.0
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1037-gcp", arch: "amd64", family: "unix"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] HotswapAgent                                                       [pom]
[INFO] hotswap-agent-core                                                 [jar]
[INFO] hotswap-agent-hibernate-plugin                                     [jar]
[INFO] hotswap-agent-hibernate3-plugin                                    [jar]
[INFO] hotswap-agent-spring-plugin                                        [jar]
[INFO] hotswap-agent-jersey1-plugin                                       [jar]
[INFO] hotswap-agent-jersey2-plugin                                       [jar]
[INFO] hotswap-agent-jetty-plugin                                         [jar]
[INFO] hotswap-agent-tomcat-plugin                                        [jar]
[INFO] hotswap-agent-zk-plugin                                            [jar]
[INFO] hotswap-agent-logback-plugin                                       [jar]
[INFO] hotswap-agent-log4j2-plugin                                        [jar]
[INFO] hotswap-agent-cdi-plugin                                           [jar]
[INFO] hotswap-agent-myfaces-plugin                                       [jar]
[INFO] hotswap-agent-mojarra-plugin                                       [jar]
[INFO] hotswap-agent-omnifaces-plugin                                     [jar]
[INFO] hotswap-agent-seam-plugin                                          [jar]
[INFO] hotswap-agent-el-resolver-plugin                                   [jar]
[INFO] hotswap-agent-osgiequinox-plugin                                   [jar]
[INFO] hotswap-agent-owb-plugin                                           [jar]
[INFO] hotswap-agent-proxy-plugin                                         [jar]
[INFO] hotswap-agent-webobjects-plugin                                    [jar]
[INFO] hotswap-agent-weld-plugin                                          [jar]
[INFO] hotswap-agent-jbossmodules-plugin                                  [jar]
[INFO] hotswap-agent-resteasy-registry-plugin                             [jar]
[INFO] hotswap-agent-deltaspike-plugin                                    [jar]
[INFO] hotswap-agent-wildfly-el-plugin                                    [jar]
[INFO] hotswap-agent-glassfish-plugin                                     [jar]
[INFO] hotswap-agent-vaadin-plugin                                        [jar]
[INFO] hotswap-agent-wicket-plugin                                        [jar]
[INFO] hotswap-agent-cxf-plugin                                           [jar]
[INFO] hotswap-agent-freemarker-plugin                                    [jar]
[INFO] hotswap-agent-undertow-plugin                                      [jar]
[INFO] hotswap-agent-plugins                                              [pom]
[INFO] hotswap-agent                                                      [jar]
[INFO] Hotswap Agent Aggregator                                           [pom]
[INFO] 
[INFO] ---------------< org.hotswapagent:hotswap-agent-parent >----------------
[INFO] Building HotswapAgent 1.3.1-SNAPSHOT                              [1/36]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:properties (default) @ hotswap-agent-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hotswap-agent-parent ---
[INFO] Installing /home/travis/build/markiewb/HotswapAgent/hotswap-agent-parent/pom.xml to /home/travis/.m2/repository/org/hotswapagent/hotswap-agent-parent/1.3.1-SNAPSHOT/hotswap-agent-parent-1.3.1-SNAPSHOT.pom
[INFO] 
[INFO] ----------------< org.hotswapagent:hotswap-agent-core >-----------------
[INFO] Building hotswap-agent-core 1.3.1-SNAPSHOT                        [2/36]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hotswap-agent-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ hotswap-agent-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 354 source files to /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/target/classes
[INFO] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/annotation/handler/PluginClassFileTransformer.java: Some input files use or override a deprecated API.
[INFO] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/annotation/handler/PluginClassFileTransformer.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginRegistry.java: Some input files use unchecked or unsafe operations.
[INFO] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginRegistry.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/Loader.java:[425,20] cannot find symbol
  symbol:   method getDefinedPackage(java.lang.String)
  location: class org.hotswap.agent.javassist.Loader
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[295,66] cannot find symbol
  symbol:   method getModule()
  location: variable neighbor of type java.lang.Class<?>
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[295,36] cannot find symbol
  symbol:   method getModule()
  location: variable class of type java.lang.Class<org.hotswap.agent.javassist.util.proxy.DefineClassHelper>
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[297,45] cannot find symbol
  symbol:   method privateLookupIn(java.lang.Class<capture#1 of ?>,java.lang.invoke.MethodHandles.Lookup)
  location: class java.lang.invoke.MethodHandles
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[298,29] cannot find symbol
  symbol:   method defineClass(byte[])
  location: variable prvlookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[317,26] cannot find symbol
  symbol:   method defineClass(byte[])
  location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[333,28] cannot find symbol
  symbol:   method dropLookupMode(int)
  location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[334,26] cannot find symbol
  symbol:   method defineClass(byte[])
  location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[INFO] 8 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hotswap Agent Aggregator 1.3.1-SNAPSHOT:
[INFO] 
[INFO] HotswapAgent ....................................... SUCCESS [  1.348 s]
[INFO] hotswap-agent-core ................................. FAILURE [  6.459 s]
[INFO] hotswap-agent-hibernate-plugin ..................... SKIPPED
[INFO] hotswap-agent-hibernate3-plugin .................... SKIPPED
[INFO] hotswap-agent-spring-plugin ........................ SKIPPED
[INFO] hotswap-agent-jersey1-plugin ....................... SKIPPED
[INFO] hotswap-agent-jersey2-plugin ....................... SKIPPED
[INFO] hotswap-agent-jetty-plugin ......................... SKIPPED
[INFO] hotswap-agent-tomcat-plugin ........................ SKIPPED
[INFO] hotswap-agent-zk-plugin ............................ SKIPPED
[INFO] hotswap-agent-logback-plugin ....................... SKIPPED
[INFO] hotswap-agent-log4j2-plugin ........................ SKIPPED
[INFO] hotswap-agent-cdi-plugin ........................... SKIPPED
[INFO] hotswap-agent-myfaces-plugin ....................... SKIPPED
[INFO] hotswap-agent-mojarra-plugin ....................... SKIPPED
[INFO] hotswap-agent-omnifaces-plugin ..................... SKIPPED
[INFO] hotswap-agent-seam-plugin .......................... SKIPPED
[INFO] hotswap-agent-el-resolver-plugin ................... SKIPPED
[INFO] hotswap-agent-osgiequinox-plugin ................... SKIPPED
[INFO] hotswap-agent-owb-plugin ........................... SKIPPED
[INFO] hotswap-agent-proxy-plugin ......................... SKIPPED
[INFO] hotswap-agent-webobjects-plugin .................... SKIPPED
[INFO] hotswap-agent-weld-plugin .......................... SKIPPED
[INFO] hotswap-agent-jbossmodules-plugin .................. SKIPPED
[INFO] hotswap-agent-resteasy-registry-plugin ............. SKIPPED
[INFO] hotswap-agent-deltaspike-plugin .................... SKIPPED
[INFO] hotswap-agent-wildfly-el-plugin .................... SKIPPED
[INFO] hotswap-agent-glassfish-plugin ..................... SKIPPED
[INFO] hotswap-agent-vaadin-plugin ........................ SKIPPED
[INFO] hotswap-agent-wicket-plugin ........................ SKIPPED
[INFO] hotswap-agent-cxf-plugin ........................... SKIPPED
[INFO] hotswap-agent-freemarker-plugin .................... SKIPPED
[INFO] hotswap-agent-undertow-plugin ...................... SKIPPED
[INFO] hotswap-agent-plugins .............................. SKIPPED
[INFO] hotswap-agent ...................................... SKIPPED
[INFO] Hotswap Agent Aggregator ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.370 s
[INFO] Finished at: 2019-08-23T04:25:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project hotswap-agent-core: Compilation failure: Compilation failure: 
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/Loader.java:[425,20] cannot find symbol
[ERROR]   symbol:   method getDefinedPackage(java.lang.String)
[ERROR]   location: class org.hotswap.agent.javassist.Loader
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[295,66] cannot find symbol
[ERROR]   symbol:   method getModule()
[ERROR]   location: variable neighbor of type java.lang.Class<?>
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[295,36] cannot find symbol
[ERROR]   symbol:   method getModule()
[ERROR]   location: variable class of type java.lang.Class<org.hotswap.agent.javassist.util.proxy.DefineClassHelper>
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[297,45] cannot find symbol
[ERROR]   symbol:   method privateLookupIn(java.lang.Class<capture#1 of ?>,java.lang.invoke.MethodHandles.Lookup)
[ERROR]   location: class java.lang.invoke.MethodHandles
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[298,29] cannot find symbol
[ERROR]   symbol:   method defineClass(byte[])
[ERROR]   location: variable prvlookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[317,26] cannot find symbol
[ERROR]   symbol:   method defineClass(byte[])
[ERROR]   location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[333,28] cannot find symbol
[ERROR]   symbol:   method dropLookupMode(int)
[ERROR]   location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] /home/travis/build/markiewb/HotswapAgent/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/util/proxy/DefineClassHelper.java:[334,26] cannot find symbol
[ERROR]   symbol:   method defineClass(byte[])
[ERROR]   location: variable lookup of type java.lang.invoke.MethodHandles.Lookup
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hotswap-agent-core
```

**Comment by skybber** [comment]
Build-in javassist uses java11 API, therefore HotswapAgent 1.3.1 can be build only with java >=java.11, but java8 can be used as a runtime for it.

**Comment by markieww** [comment]
Okay. So my issue isn't related to the JDK-version?

I get this exception with 1.2.0,1.3.0 and 1.3.1-SNAPSHOT (I did not try even older versions of the agent)

```
HOTSWAP AGENT: 11:14:18.119 ERROR (org.hotswap.agent.command.ReflectionCommand) - Error executin method hotswap in class org.hotswap.agent.plugin.hotswapper.HotswapperCommand
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hotswap.agent.command.ReflectionCommand.doExecuteReflectionCommand(ReflectionCommand.java:188)
        at org.hotswap.agent.command.ReflectionCommand.executeCommand(ReflectionCommand.java:149)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.NoClassDefFoundError: com/sun/jdi/request/EventRequest
        at org.hotswap.agent.plugin.hotswapper.HotswapperCommand.hotswap(HotswapperCommand.java:30)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.request.EventRequest
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1955)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1798)
        ... 7 more
```

```
HOTSWAP AGENT: 11:08:45.847 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.2.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 11:08:46.513 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish]
Listening for transport dt_socket at address: 8000
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
Dynamic Code Evolution 64-Bit Server VM (AdoptOpenJDK)(build 25.71-b01-dcevmlight-26, mixed mode)
```

**Comment by skybber** [comment]
It looks like you are using jre8 instead jdk8 with tools.jar, it contains missing EventRequest class.

**Comment by skybber** [comment]
I'm closing it. HotswpaAgent > 1.3.0 must be build with java11, com.sun.jdi.request.EventRequest is part of JDK(8,11), not JRE.
