### ISSUE TITLE
no such class: org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder

### ISSUE THREAD

**Issue by lppedd** [HotswapProjects/HotswapAgent#317]
I'm trying to use HotswapAgent to hotswap an IntelliJ IDEA plugin's classes.  
However this is the error I receive after start-up.

```
18:43:36: Executing task 'runIde'...

Starting Gradle Daemon...Connected to the target VM, address: '127.0.0.1:61638', transport: 'socket'
Gradle Daemon started in 4 s 441 ms
> Task :compileKotlin
> Task :compileJava
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes
> Task :inspectClassesForKotlinIC
> Task :instrumentCode
> Task :postInstrumentCode
> Task :jar
> Task :prepareSandbox
Connected to the VM started by ':runIde' (localhost:61668). Open the debugger session tab

> Task :runIde
HOTSWAP AGENT: 18:44:14.331 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.3.1-SNAPSHOT} - unlimited runtime class redefinition.
HOTSWAP AGENT: 18:44:14.670 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow]
Starting HotswapAgent 'C:\Users\edoardo\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbr-11_0_3-windows-x64-b304.56\jbr\lib\hotswap\hotswap-agent.jar'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.ide.ClassUtilCore to field sun.net.www.protocol.jar.JarFileFactory.fileCache
WARNING: Please consider reporting this to the maintainers of com.intellij.ide.ClassUtilCore
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-09-07 18:44:22,265 [   5389]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
2019-09-07 18:44:26,931 [  10055]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: VibrantInk from plugin: com.intellij.database 
2019-09-07 18:44:26,932 [  10056]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: WarmNeon from plugin: com.intellij.database 
2019-09-07 18:44:26,932 [  10056]   WARN - s.impl.EditorColorsManagerImpl - Cannot find scheme: High ?ontrast from plugin: com.intellij.database 
2019-09-07 18:44:40,112 [  23236]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.kotlin.idea.highlighter.KotlinDefaultHighlightingSettingsProvider 
HOTSWAP AGENT: 18:45:05.570 ERROR (org.hotswap.agent.plugin.proxy.ProxyPlugin) - Error modifying class for cglib proxy creation parameter recording
org.hotswap.agent.javassist.CannotCompileException: [source error] no such class: org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:909)
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:824)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.transform(GeneratorParametersTransformer.java:57)
	at org.hotswap.agent.plugin.proxy.ProxyPlugin.transformDefinitions(ProxyPlugin.java:145)
	at jdk.internal.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:335)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:330)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:294)
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:280)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.sf.cglib.core.AbstractClassGenerator.<init>(AbstractClassGenerator.java:42)
	at net.sf.cglib.proxy.AdvancedEnhancer.<init>(AdvancedEnhancer.java:154)
	at net.sf.cglib.proxy.AdvancedProxy.createProxy(AdvancedProxy.java:112)
	at net.sf.cglib.proxy.AdvancedProxy.createProxy(AdvancedProxy.java:96)
	at net.sf.cglib.proxy.AdvancedProxy.createProxy(AdvancedProxy.java:81)
	at com.intellij.util.xml.impl.DomInvocationHandler.getProxy(DomInvocationHandler.java:524)
	at com.intellij.util.xml.impl.DomFileElementImpl.getRootElement(DomFileElementImpl.java:320)
	at com.intellij.jam.model.util.JamCommonUtil.getRootElement(JamCommonUtil.java:136)
	at com.intellij.javaee.web.facet.WebFacetImpl.lambda$getWebApps$2(WebFacetImpl.java:254)
	at com.intellij.util.containers.ContainerUtilRt.mapNotNull(ContainerUtilRt.java:382)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:2060)
	at com.intellij.javaee.web.facet.WebFacetImpl.getWebApps(WebFacetImpl.java:254)
	at com.intellij.javaee.web.facet.WebFacetImpl.getRoot(WebFacetImpl.java:222)
	at com.intellij.spring.web.config.webXml.WebXmlSpringWebModelContributor.getFilesets(WebXmlSpringWebModelContributor.java:46)
	at com.intellij.spring.web.mvc.model.SpringMVCModelServiceImplKt.getSpringFileSetsWithDependencies(SpringMVCModelServiceImpl.kt:70)
	at com.intellij.spring.web.mvc.model.SpringMVCModelServiceImplKt.access$getSpringFileSetsWithDependencies(SpringMVCModelServiceImpl.kt:1)
	at com.intellij.spring.web.mvc.model.SpringMVCModelServiceImplKt$getSpringMVCModelsMap$1.compute(SpringMVCModelServiceImpl.kt:50)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:240)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:241)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValueFromExHolder(CachedValuesManagerImpl.java:72)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:45)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:119)
	at com.intellij.spring.web.mvc.model.SpringMVCModelServiceImplKt.getSpringMVCModelsMap(SpringMVCModelServiceImpl.kt:45)
	at com.intellij.spring.web.config.SpringWebModelProvider.getFilesets(SpringWebModelProvider.kt:26)
	at com.intellij.spring.facet.SpringFileSetServiceImpl.getModelProviderSets(SpringFileSetServiceImpl.java:72)
	at com.intellij.spring.facet.SpringFileSetServiceImpl.getAllSets(SpringFileSetServiceImpl.java:54)
	at com.intellij.spring.facet.validation.SpringUnmappedConfigurationFilesCollector.collect(SpringUnmappedConfigurationFilesCollector.java:99)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.runCollectors(SpringConfigurationCheckTask.java:130)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.lambda$null$0(SpringConfigurationCheckTask.java:78)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:153)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:146)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.lambda$run$1(SpringConfigurationCheckTask.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:126)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.spring.facet.validation.SpringConfigurationCheckTask.run(SpringConfigurationCheckTask.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: compile error: no such class: org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder
	at org.hotswap.agent.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:711)
	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:360)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at org.hotswap.agent.javassist.compiler.Javac.compileStmnt(Javac.java:578)
	at org.hotswap.agent.javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:931)
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:883)
	... 80 more
```

And on every re-compile.

```
HOTSWAP AGENT: 18:46:14.312 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.proxy.ProxyPlugin' class 'org/angular2/inspections/AngularInaccessibleComponentMemberInAotModeInspection$2'.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParamsMap(GeneratorParametersTransformer.java:103)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParams(GeneratorParametersTransformer.java:130)
	at org.hotswap.agent.plugin.proxy.ProxyPlugin.transformCglibProxy(ProxyPlugin.java:105)
	... 10 more
```

Any idea what it could be?

**Comment by skybber** [comment]
I have no possibility to check this case. Are you able to look at the problem with   GeneratorParametersRecorder class using debugger? Probably it is not found in this method: https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/compiler/MemberResolver.java#L407

**Comment by lppedd** [comment]
@skybber sure I can try. What do you want me to check and report?

**Comment by skybber** [comment]
Method should step into classPool.createCtClass and https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/ClassPool.java#L545 probably will return null. Could you confirm it?

**Comment by lppedd** [comment]
@skybber that's what I get, hope I did as you intended.  
![image](https://user-images.githubusercontent.com/19871649/64485899-564d2f80-d226-11e9-80cf-cb9466ea0584.png)

**Comment by lppedd** [comment]
@skybber I've also made a gif for the `MemberRisolver` you mentioned above.
![error](https://user-images.githubusercontent.com/19871649/64486180-0cfedf00-d22a-11e9-99f0-d301dba56251.gif)

**Comment by skybber** [comment]
It looks like the classpath is missing in ClassPoolTail.pathList. I'm not familiar with the mechanism of filling this list. Btw is it working with java8 ?

**Comment by lppedd** [comment]
@skybber I will try with JDK8 ASAP. Why would it be missing `ClassPoolTail`? I mean, it's in the same JAR.
I choosed the Trava build because I had problems with patching Oracle JDK.

Anyway, an interesting detail, removing the Proxy plugin solves the problem without producing other issues, it seems. What am I losing this way?

**Comment by skybber** [comment]
You lost opportunity to hotswap cglib proxy classes, for instance @Component classes.

**Comment by lppedd** [comment]
@skybber Oh well, there is not much of that on IntelliJ Plugins. However I'd like to understand this odd behavior. I'll try with JDK8 as promised.

**Comment by lppedd** [comment]
@skybber Oracle JDK 8_181 - patched, works fine with all plugins.

**Comment by skybber** [comment]
It looks like problem in javassist at this place: https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/javassist/ClassPoolTail.java#L247 

Are you able to comment out the IF block (java11 could use same code like and check it), otherwise I'll prepare some fork for you.

**Comment by lppedd** [comment]
@skybber yeah I'll edit the `.class` bytecode and remove that if entirely.

```
if (org.hotswap.agent.javassist.bytecode.ClassFile.MAJOR_VERSION < org.hotswap.agent.javassist.bytecode.ClassFile.JAVA_9)
    return appendClassPath(new ClassClassPath());
```

**Comment by skybber** [comment]
I'm sorry, leave the content of If block and remove the rest. Thanks.

**Comment by lppedd** [comment]
@skybber oh ok!

**Comment by lppedd** [comment]
@skybber done, unfortunately the error is still there.

**Comment by skybber** [comment]
I've checked the problem with java11 again, are you using dcevm11 (https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases) or plain java11?

**Comment by lppedd** [comment]
@skybber hi! I'm using Trava JDK 11.
Do you need some kind of info?

**Comment by skybber** [comment]
Could you contact me by email?

**Comment by lppedd** [comment]
@skybber done!
