### ISSUE TITLE
HotswapSpringInvocationHandler cannot be cast to org.apache.cxf.frontend.ClientProxy

### ISSUE THREAD

**Issue by folfix** [HotswapProjects/HotswapAgent#327]
Hi!
I am struggling with a following exception:
`Caused by: java.lang.ClassCastException: org.hotswap.agent.plugin.spring.getbean.HotswapSpringInvocationHandler cannot be cast to org.apache.cxf.frontend.ClientProxy
	at org.apache.cxf.frontend.ClientProxy.getClient(ClientProxy.java:127)
	at com.schenker.nges.backend.francebarcode.impl.ws.FranceRoutingShortDistanceTourWSClient.afterPropertiesSet(FranceRoutingShortDistanceTourWSClient.java:40)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 183 common frames omitted`

**org.apache.cxf.frontend.ClientProxy:107 (org.apache.cxf:cxf-rt-frontend-simple:3.2.8)**
![debug](https://i.imgur.com/nDWJUys.png)

### Hotswap start logs
`HOTSWAP AGENT: 11:29:34.513 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.2.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 11:29:35.332 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, Seam, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish]
`

### Environment
Version **1.1.0-SNAPSHOT** is working fine. Problem occurs for all of the versions newer than that.
- JDK: Oracle Java 1.8.0_181-b13
- DCEVM: 8u181-build2
- Multi-module Maven project
- Apache Tomcat/9.0.29
- Linux Mint 19.2 4.18.0-25-generic

Thank you in advance!

**Comment by skybber** [comment]
It looks that you directly call https://github.com/apache/cxf/blob/b6e9e297a253e8b6e285e009d57ab8964065939a/rt/frontend/simple/src/main/java/org/apache/cxf/frontend/ClientProxy.java#L126
but HA creates proxy for com.sun.proxy https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-spring-plugin/src/main/java/org/hotswap/agent/plugin/spring/getbean/ProxyReplacer.java#L86 

the code in ClientProxy should look something like:

    (ClientProxy)Proxy.getInvocationHandler(((HotswapSpringInvocationHandler )Proxy.getInvocationHandler(o)).getTarget())

You can't modify CXF code, but you could modify the call. Would you like check it please by modification the call from your app :

    ClientProxy.getClient(Proxy.getInvocationHandler(o))

does it help?

We can add some abstract mechanism to unwrap com.sun.proxy to avoid cross dependecne between plugins in the furure.

**Comment by folfix** [comment]
Thanks for response skybber.
Yes, it's direct call:
``` java
TlsCertificateFixer.disableCertificateCheck((HTTPConduit) (ClientProxy.getClient(wsClient).getConduit()));
```
I invoked following in debuger:
- `((Proxy) wsClient).h` -> returns HotswapSpringInvocationHandler
- `ClientProxy.getClient(wsClient.h.getTarget())` -> returns unwrapped client
- `TlsCertificateFixer.disableCertificateCheck(ClientProxy.getClient(((Proxy) wsClient).h.getTarget()).getConduit())` -> is equal to original code

Unfortunately I am not able to import HA sources and test if changes compatible with HA will either work with plain Hotspot JVM. I guess they will not.

I found workaround to be able to use HA 1.3.1-SNAPSHOT and I will wait patiently for mentioned abstract mechanism :)

Thanks!

**Comment by ruediste** [comment]
I wanted to add a `Transformer` to patch `java.lang.reflect.Proxy.getInvocationHandler(Object)` to return the original invocation handler. I set a breakpoint in ProxyReplacer#86 but it was never reached in the unit tests. Do you know how to get spring to use `Proxy` to create proxies?
