### ISSUE TITLE
Payara 5.201 + jdk8  java.lang.reflect.InvocationTargetException: Caused by: compile error: no such field: beanMetaDataCache

### ISSUE THREAD

**Issue by FiruzzZ** [HotswapProjects/HotswapAgent#339]
I am moving from Payara 4 to 5 (5.201, the latest) and trying to add hotswapAgent to it, I got an exception. I tried Agent 1.3.0, 1.3.1 and 1.4.0, I couldn't make it work with any version

_Running Payara Version: Payara Server  5.201 #badassfish (build 512)|#]
  Server log file is using Formatter class: com.sun.enterprise.server.logging.ODLLogFormatter|#]
  Data grid encryption is enabled|#]
  Registered fish.payara.ha.hazelcast.store.HazelcastBackingStoreFactoryProxy for persistence-type = hazelcast in BackingStoreFactoryRegistry|#]
  Hazelcast Instance Bound to JNDI at payara/Hazelcast|#]
  JSR107 Caching Provider Bound to JNDI at payara/CachingProvider|#]
  JSR107 Default Cache Manager Bound to JNDI at payara/CacheManager|#]
  Network Listener http-listener-1 started in: 8ms - bound to [/0.0.0.0:8080]|#]
  Network Listener http-listener-2 started in: 2ms - bound to [/0.0.0.0:8181]|#]
  Network Listener admin-listener started in: 2ms - bound to [/0.0.0.0:4848]|#]
  Grizzly 2.4.3 started in: 4.466ms - bound to [http-listener-1:8080, http-listener-2:8181, admin-listener:4848]|#]
  Network Listener iiop-service started in: 2ms - bound to [/0.0.0.0:3700]|#]
  HV000001: Hibernate Validator 6.1.2.Final|#]_
` java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:193)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:89)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:184)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2344)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2162)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2096)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1565)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1982)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:435)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.jvnet.hk2.config.WriteableView.<clinit>(WriteableView.java:96)
	at org.jvnet.hk2.config.ConfigSupport.getWriteableView(ConfigSupport.java:217)
	at org.jvnet.hk2.config.ConfigSupport.getWriteableView(ConfigSupport.java:240)
	at org.jvnet.hk2.config.ConfigSupport._apply(ConfigSupport.java:163)
	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:139)
	at org.jvnet.hk2.config.ConfigSupport.apply(ConfigSupport.java:118)
	at com.sun.enterprise.config.modularity.parser.ConfigurationParser.parseAndSetConfigBean(ConfigurationParser.java:128)
	at com.sun.enterprise.config.modularity.ConfigBeanInstaller.applyConfigIfNeeded(ConfigBeanInstaller.java:113)
	at com.sun.enterprise.config.modularity.ConfigBeanInstaller.postConstruct(ConfigBeanInstaller.java:94)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:303)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:679)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at com.sun.enterprise.naming.impl.NamedNamingObjectManager.tryNamedProxies(NamedNamingObjectManager.java:127)
	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:164)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:476)
	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at fish.payara.microprofile.faulttolerance.service.FaultToleranceServiceImpl.postConstruct(FaultToleranceServiceImpl.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] no such field: beanMetaDataCache
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:79)
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:45)
	at org.hotswap.agent.plugin.hibernate.HibernateTransformers.beanMetaDataManagerRegisterVariable(HibernateTransformers.java:106)
	... 83 more
Caused by: compile error: no such field: beanMetaDataCache
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupField(MemberResolver.java:313)
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:299)
	at org.hotswap.agent.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:876)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:578)
	at org.hotswap.agent.javassist.compiler.ast.Expr.accept(Expr.java:68)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:665)
	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at org.hotswap.agent.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at org.hotswap.agent.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at org.hotswap.agent.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at org.hotswap.agent.javassist.compiler.Javac.compileMethod(Javac.java:169)
	at org.hotswap.agent.javassist.compiler.Javac.compile(Javac.java:95)
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 85 more`

**Comment by skybber** [comment]
Could you try disable hibernate plugin? Does it help?

**Comment by FiruzzZ** [comment]
yes, I can, I am using Eclipselink not hibernate, how do I disable it?

**Comment by skybber** [comment]
-javaagent: .... hotswap-agent.jar=disablePlugin=Hibernate

**Comment by FiruzzZ** [comment]
worked, seems that newer versions of Hibernate removed some methods used by HotswapAg

**Comment by skybber** [comment]
We have test up to v5.4.3 :

https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-hibernate-plugin/run-tests.sh

It's strange that the HibernatePlugin is activated at all...
