### ISSUE TITLE
 javax.el.PropertyNotFoundException in xhtml

### ISSUE THREAD

**Issue by Sindhuja1295** [HotswapProjects/HotswapAgent#358]
Dear Team,

Java verson:  jdk1.8.0_191
DCEVM - 181 version
Hotswap-agent- 1.4 snapshot.jar

Issue:
1. Creating boolean variable in Model java class.

 private boolean sampletest;
      public boolean isTestsample() {
        return testsample;
    }

    public void setTestsample(boolean testsample) {
        this.testsample = testsample;
    }
2. Using this variable in xhtml as below,

<p:commandButton id="MAB_samplesearchbtn"  icon="fa fa-search" rendered ="true"
                                  actionListener="#{MAB.ctrl.btnsampleClassSearchActionPerformed}"  disabled="#{MAB.model.testsample}" />
                   
3. While am opening the module, am getting the below error,

16:38:21,992 ERROR [stderr] (default task-19) Caused by: javax.el.PropertyNotFoundException: The class 'com.svm.lrp.nfr.multiagencyModel.MABModel' does not have the property 'testsample'.
16:38:21,992 ERROR [stderr] (default task-19)   at javax.el.BeanELResolver.getBeanProperty(BeanELResolver.java:567)
16:38:21,992 ERROR [stderr] (default task-19)   at javax.el.BeanELResolver.getValue(BeanELResolver.java:229)
16:38:21,992 ERROR [stderr] (default task-19)   at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
16:38:21,992 ERROR [stderr] (default task-19)   at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
16:38:21,992 ERROR [stderr] (default task-19)   at com.sun.el.parser.AstValue.getValue(AstValue.java:139)
16:38:21,992 ERROR [stderr] (default task-19)   at com.sun.el.parser.AstValue.getValue(AstValue.java:203)
16:38:21,992 ERROR [stderr] (default task-19)   at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
16:38:21,992 ERROR [stderr] (default task-19)   at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
16:38:21,992 ERROR [stderr] (default task-19)   at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
16:38:21,993 ERROR [stderr] (default task-19)   at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)

**Comment by skybber** [comment]
Could you please open BeanELResolver.java using decompiler and send the content of method `javax.el.BeanELResolver.getBeanProperty` to help  find out the problem? There are many implementations of BeanELResolver...

**Comment by Sindhuja1295** [comment]
Dear Team, 

Kindly find an attached el-api jar. 

Regards, 
Sindhuja A J 

----- Original Message -----

**Comment by Sindhuja1295** [comment]
Kindly find the below image

![image](https://user-images.githubusercontent.com/54404515/86918474-68e50d80-c144-11ea-876c-c3f3b7708c0c.png)

**Comment by skybber** [comment]
it seems, we don't have support for this jbossEL version.

**Comment by Sindhuja1295** [comment]
May i know, which el version of jboss it supports? 

----- Original Message -----

**Comment by skybber** [comment]
https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-el-resolver-plugin/src/main/java/org/hotswap/agent/plugin/elresolver/ELResolverPlugin.java#L60

**Comment by Sindhuja1295** [comment]
Hi, am using below versions as mentioned in the above url,

![image](https://user-images.githubusercontent.com/54404515/87004215-b3b16480-c1da-11ea-98de-beaed9ee3598.png)

though the same error occurs, kindly assist us for this issue!

**Comment by Sindhuja1295** [comment]
Hi, any update on this!
