### ISSUE TITLE
Does not work (Possibly Intellij Idea related)

### ISSUE THREAD

**Issue by AkashaP** [HotswapProjects/HotswapAgent#367]
I'm getting errors after upgrading to dcevm 11.0.8+1, can't build my project, it was working before i upgraded versions

Not sure if related but i also updated Kotlin version to 1.4.0-rc-release-IJ2020.1-2

It's says loading hotswap agent {1.4.1} and then crashes with
Stacktrace
```
Starting HotswapAgent '/home/akasha/.jdks/dcevm-11.0.8+1/lib/hotswap/hotswap-agent.jar'
HOTSWAP AGENT: 02:19:49.544 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NullPointerException
        at org.hotswap.agent.config.PluginManager.init(PluginManager.java:138)
        at org.hotswap.agent.HotswapAgent.premain(HotswapAgent.java:69)
        ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted (core dumped)


```

strange... getting the same error when downgrading back to 11.0.7+4 now.

**Comment by AkashaP** [comment]
i think this is more of a jdk 11 dcevm issue so i'll post it there instead

**Comment by skybber** [comment]
Do you have this problem even with the last dcevm11?

**Comment by skybber** [comment]
should be resolved in dcevm11/jbr11/17
