### ISSUE TITLE
Hibernate Plugin error

### ISSUE THREAD

**Issue by nittynite** [HotswapProjects/HotswapAgent#373]
On OpenJDK11 version, I am getting error on Hibernate Plugin.  

I have tested on multiple versions of hibernate on version 5, I continue to get the same error.

HOTSWAP AGENT: 11:51:06.403 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.hibernate.HibernatePlugin' class 'org/hibernate/validator/internal/metadata/BeanMetaDataManager'.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.createValidator(ValidatorFactoryImpl.java:308)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.getValidator(ValidatorFactoryImpl.java:206)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$ValidationInitializer.run(BackgroundPreinitializer.java:142)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.runSafely(BackgroundPreinitializer.java:104)
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.run(BackgroundPreinitializer.java:95)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] no such field: beanMetaDataCache
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:84)
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:50)
	at org.hotswap.agent.plugin.hibernate.HibernateTransformers.beanMetaDataManagerRegisterVariable(HibernateTransformers.java:124)
	... 25 more
Caused by: compile error: no such field: beanMetaDataCache
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupField(MemberResolver.java:321)
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:307)
	at org.hotswap.agent.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:904)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605)
	at org.hotswap.agent.javassist.compiler.ast.Expr.accept(Expr.java:71)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:693)
	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:360)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at org.hotswap.agent.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
	at org.hotswap.agent.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
	at org.hotswap.agent.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
	at org.hotswap.agent.javassist.compiler.Javac.compileMethod(Javac.java:175)
	at org.hotswap.agent.javassist.compiler.Javac.compile(Javac.java:102)
	at org.hotswap.agent.javassist.CtNewMethod.make(CtNewMethod.java:79)
	... 27 more

**Comment by skybber** [comment]
Hibernate plugin should be working up to v5.4.8.Final at least. What version are you using?

**Comment by nittynite** [comment]
The oldest I have tried is v5.4.10. Maybe that's why it was not working.  I did replace HotswapAgent jar file comes with DCEVM Open JDK 11 package with the latest snapshot then it works perfectly for new version up to 5.4.22, the latest hibernate release.

So far, it's working perfectly but since it's snapshot,  probably better to stick to v5.4.8 for now.

**Comment by nittynite** [comment]
One suggestion is that probably it's better to track such compatible version list and published it somewhere so that everyone knows what's been supported.   That's something I can contribute to (Of course, with coding also if you guys need help)

**Comment by skybber** [comment]
compatibility tests are at https://github.com/HotswapProjects/HotswapAgent/blob/master/plugin/hotswap-agent-hibernate-plugin/run-tests.sh

**Comment by skybber** [comment]
I have checked closed issues and the problem was reported at #357 , so fixed in snapshot now as you wrote.
