### ISSUE TITLE
VaadinPlugin looking for classes in the wrong place

### ISSUE THREAD

**Issue by FiruzzZ** [HotswapProjects/HotswapAgent#375]
I couldn't determinate a 100% reproducible case, but for some reason is looking for classes in `/WEB-INF/classes`, these exceptions are thrown for every class in the project (it is a very long log), compiled are in `\target\classes\` right?

`java.lang.IllegalArgumentException: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\prestadores\controller\PreliquidacionOrdenViewController.class (The system cannot find the path specified)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:76)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:218)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:147)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:98)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\prestadores\controller\PreliquidacionOrdenViewController.class (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:70)
	... 4 more
|#]
java.lang.IllegalArgumentException: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\controller\logger\EmptyLogException.class (The system cannot find the path specified)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:76)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:218)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:147)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:98)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\controller\logger\EmptyLogException.class (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:70)
	... 4 more
|#]
java.lang.IllegalArgumentException: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\controller\logger\EmptyLogException.class (The system cannot find the path specified)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:76)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.createCtClass(WatchEventCommand.java:218)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:147)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:98)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.io.FileNotFoundException: C:\NetBeansProjects\saos-prestadores\target\saos-prestadores\WEB-INF\classes\org\saos\controller\logger\EmptyLogException.class (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at org.hotswap.agent.util.IOUtils.toByteArray(IOUtils.java:70)
	... 4 more`

I am using V14.4.1 and hotswap 1.4.2-snap on Netbeans 12.0

**Comment by skybber** [comment]
May be is it on class delete?

**Comment by FiruzzZ** [comment]
I not sure what you mean but I am not deleting classes/files nor renaming, just adding lines for now (methods, attributes). Like I said it is not about one or 2 files, that exception is thrown for every file in the projects (hundreds)

**Comment by skybber** [comment]
`WEB-INF\classes` is empty all the time? May be it is used by maven to create war/exploded war? Are you using `extraclassPath` and `autoHotswap` ?

**Comment by FiruzzZ** [comment]
no, it's not empty actually, the complete project is there, `autoHotswap` is false (as default) and `extraClassPath` I didn't touch it, so it is at its default value.
I had an old knowledge about desktop apps (Java SE), that compiled classes were in /target/classes, so I don't know why the exceptions are thrown, I kept looking at that path to see if the IDE does some unexpected clean but no, files are always there
