### ISSUE TITLE
Spring AspectJ compile time weaving LinkageError

### ISSUE THREAD

**Issue by cdalexndr** [HotswapProjects/HotswapAgent#376]
Error on hotswap:
```
HOTSWAP AGENT: 15:53:13.608 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.proxy.ProxyPlugin' class 'pse/shop/product/smart/ProductPropertyRepository'.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
Caused by: java.lang.LinkageError: loader org.springframework.data.jpa.repository.config.InspectionClassLoader @27960b1e attempted duplicate class definition for org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder. (org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersRecorder is in unnamed module of loader org.springframework.data.jpa.repository.config.InspectionClassLoader @27960b1e, parent loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878)
	at org.springframework.instrument.classloading.ShadowingClassLoader.doLoadClass(ShadowingClassLoader.java:156)
	at org.springframework.instrument.classloading.ShadowingClassLoader.loadClass(ShadowingClassLoader.java:118)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParamsMap(GeneratorParametersTransformer.java:102)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParams(GeneratorParametersTransformer.java:130)
	at org.hotswap.agent.plugin.proxy.ProxyPlugin.transformCglibProxy(ProxyPlugin.java:105)
	... 10 more
```

Hotswap log lines:
```
HOTSWAP AGENT: 15:52:14.655 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 15:52:14.927 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Starting HotswapAgent 'C:\Program Files\Java\dcevm-11.0.9+1\lib\hotswap\hotswap-agent.jar'
HOTSWAP AGENT: 15:52:30.086 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory C:\Developer\pse\source\backend\server\build\classes\java\main 
HOTSWAP AGENT: 15:52:30.088 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory C:\Developer\pse\source\backend\server\build\resources\main 
HOTSWAP AGENT: 15:52:30.088 INFO (org.hotswap.agent.watch.nio.TreeWatcherNIO) - Registering directory C:\Developer\pse\source\backend\commons\build\classes\java\main 
HOTSWAP AGENT: 15:52:30.088 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hibernate.HibernatePlugin' initialized in ClassLoader 'jdk.internal.loader.ClassLoaders$AppClassLoader@61064425'.
HOTSWAP AGENT: 15:52:30.088 INFO (org.hotswap.agent.plugin.hibernate.HibernatePlugin) - Hibernate plugin initialized - Hibernate Core version '5.4.20.Final'
```

Hotswap Agnet 1.4.1

**Comment by skybber** [comment]
I'm not sure, but last dcevm11 https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases/tag/dcevm-11.0.10%2B3 could resolve your problem
