### ISSUE TITLE
WeldPlugin: InvocationTargetException in ProxyFactory: "no such field: classLoader"

### ISSUE THREAD

**Issue by thiesw** [HotswapProjects/HotswapAgent#391]
Application runs but following error is logged on startup/deployment.

Using:
- JVM 1.8.0_181-b13 (with dcevm)
- Hotswap agent {1.4.2-SNAPSHOT}
- Tomcat 8.5.54.0
- **Weld:  org.jboss.weld.servlet:weld-servlet-shaded  3.1.7.Final**

```
HOTSWAP AGENT: 16:21:41.651 INFO (org.hotswap.agent.plugin.weld.WeldPlugin) - Weld plugin initialized.
HOTSWAP AGENT: 16:21:44.779 ERROR (org.hotswap.agent.annotation.handler.PluginClassFileTransformer) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.weld.WeldPlugin' class 'org/jboss/weld/bean/proxy/ProxyFactory'.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:218)
	at org.hotswap.agent.annotation.handler.PluginClassFileTransformer.transform(PluginClassFileTransformer.java:112)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:246)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2395)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at org.jboss.weld.bean.builtin.AbstractFacadeBean.initializeAfterBeanDiscovery(AbstractFacadeBean.java:61)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$AfterBeanDiscoveryInitializerFactory.doWork(ConcurrentBeanDeployer.java:111)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$AfterBeanDiscoveryInitializerFactory.doWork(ConcurrentBeanDeployer.java:102)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hotswap.agent.javassist.CannotCompileException: [source error] no such field: classLoader
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:909)
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:824)
	at org.hotswap.agent.plugin.weld.transformer.ProxyFactoryTransformer.patchProxyFactory(ProxyFactoryTransformer.java:71)
	... 25 more
Caused by: compile error: no such field: classLoader
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupField(MemberResolver.java:321)
	at org.hotswap.agent.javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:307)
	at org.hotswap.agent.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:904)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605)
	at org.hotswap.agent.javassist.compiler.ast.Expr.accept(Expr.java:71)
	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:235)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:763)
	at org.hotswap.agent.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:723)
	at org.hotswap.agent.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
	at org.hotswap.agent.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
	at org.hotswap.agent.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
	at org.hotswap.agent.javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:260)
	at org.hotswap.agent.javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:414)
	at org.hotswap.agent.javassist.compiler.CodeGen.atStmnt(CodeGen.java:385)
	at org.hotswap.agent.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
	at org.hotswap.agent.javassist.compiler.Javac.compileStmnt(Javac.java:578)
	at org.hotswap.agent.javassist.CtBehavior.insertAfterAdvice(CtBehavior.java:924)
	at org.hotswap.agent.javassist.CtBehavior.insertAfter(CtBehavior.java:883)
	... 27 more

```

**Comment by skybber** [comment]
Unitest even works now... I didn't test re-injection after redefinition (e.g. @Inject new fields in @ApplicationScoped -  it works well with OWB)

**Comment by skybber** [comment]
1.4.2 SHAPSHOT release is updated

**Comment by thiesw** [comment]
Wow, what a fast response!  Thumbs up! (all three, if I had)
I just tested and no warning/error anymore and a performed redefinition works.

**Comment by skybber** [comment]
It should even reinject new @Injected fields @SessionScoped, @ApplicationScoped beans after redefinition, if it does not work, I'll look on it.
