### ISSUE TITLE
NullPointerException - WatchResourcesPlugin.init

### ISSUE THREAD

**Issue by 3rrki** [HotswapProjects/HotswapAgent#394]
I am observing some nullpointer exception while starting the application:

```
HOTSWAP AGENT: 14:20:04.806 ERROR (org.hotswap.agent.annotation.handler.InitHandler) - InvocationTargetException in init method on plugin class org.hotswap.agent.plugin.watchResources.WatchResourcesPlugin.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.hotswap.agent.annotation.handler.InitHandler.invokeInitMethod(InitHandler.java:104)
        at org.hotswap.agent.annotation.handler.InitHandler.access$100(InitHandler.java:46)
        at org.hotswap.agent.annotation.handler.InitHandler$1.onInit(InitHandler.java:128)
        at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:197)
        at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:316)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.lang.NullPointerException
        at org.hotswap.agent.plugin.watchResources.WatchResourcesPlugin.init(WatchResourcesPlugin.java:96)
        ... 10 more
```

For some reason the plugin is null once it is about to be initialized.

https://github.com/HotswapProjects/HotswapAgent/blob/ae419ffd222c672d23d922fe9d4c73422fb7ac4d/hotswap-agent-core/src/main/java/org/hotswap/agent/plugin/watchResources/WatchResourcesPlugin.java#L96

Perhaps due to the PluginRegistry may return null ?

https://github.com/HotswapProjects/HotswapAgent/blob/ae419ffd222c672d23d922fe9d4c73422fb7ac4d/hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginRegistry.java#L170

**Comment by skybber** [comment]
It can be, if you have WatchResourcesPlugin disabled. Is it your case? If so, then we must check tne null in HA

**Comment by 3rrki** [comment]
That is the question, since I cannot really find any place where we actually disable that plugin.
I have checked all the hotswap-agent.properties files that we use and cant see that. But for some reason it gets disabled.
