### ISSUE TITLE
Hot Swapping a controller class causes an error

### ISSUE THREAD

**Issue by Matsuuu** [HotswapProjects/HotswapAgent#403]
I have a controller class using JAX-RS bindings. When I update it with the hot reloading, I run into the error:

```
10:02:44,130 INFO  [stdout] (Thread-556) HOTSWAP AGENT: 10:02:44.129 INFO (org.hotswap.agent.plugin.wildfly.el.PurgeWildFlyBeanELResolverCacheCommand) - Cleaning  BeanPropertiesCache org.my.Project ModuleClassLoader for Module "myProject.war" from Service Module Loader.
10:03:43,750 INFO  [stdout] (Thread-561) HOTSWAP AGENT: 10:03:43.746 INFO (org.hotswap.agent.plugin.wildfly.el.PurgeWildFlyBeanELResolverCacheCommand) - Cleaning  BeanPropertiesCache org.my.Project.FrontPageController ModuleClassLoader for Module "myProject.war" from Service Module Loader.
10:03:43,840 INFO  [stdout] (Thread-560) HOTSWAP AGENT: 10:03:43.839 ERROR (org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand) - Could not reload rest class org.my.Project.FrontPageController
10:03:43,840 INFO  [stdout] (Thread-560) org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: javax.servlet.ServletContext
10:03:43,842 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:77)
10:03:43,843 INFO  [stdout] (Thread-560)        at javax.servlet.api@2.0.0.Final//com.sun.proxy.$Proxy220.getAttribute(Unknown Source)
10:03:43,843 INFO  [stdout] (Thread-560)        at org.wildfly.microprofile.opentracing-smallrye@24.0.1.Final//org.wildfly.microprofile.opentracing.smallrye.TracerDynamicFeature.configure(TracerDynamicFeature.java:60)
10:03:43,843 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:113)
10:03:43,844 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:354)
10:03:43,844 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:277)
10:03:43,844 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:228)
10:03:43,845 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:201)
10:03:43,845 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:187)
10:03:43,845 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:164)
10:03:43,846 INFO  [stdout] (Thread-560)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:81)
10:03:43,846 INFO  [stdout] (Thread-560)        at myProject.war//org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand.executeCommand(RefreshRegistryCommand.java:115)
10:03:43,847 INFO  [stdout] (Thread-560)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
10:03:43,847 INFO  [stdout] (Thread-560)
10:03:43,848 INFO  [stdout] (Thread-558) HOTSWAP AGENT: 10:03:43.840 ERROR (org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand) - Could not reload rest class org.my.Project.FrontPageController
10:03:43,848 INFO  [stdout] (Thread-558) org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: javax.servlet.ServletContext
10:03:43,848 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:77)
10:03:43,849 INFO  [stdout] (Thread-558)        at javax.servlet.api@2.0.0.Final//com.sun.proxy.$Proxy220.getAttribute(Unknown Source)
10:03:43,849 INFO  [stdout] (Thread-558)        at org.wildfly.microprofile.opentracing-smallrye@24.0.1.Final//org.wildfly.microprofile.opentracing.smallrye.TracerDynamicFeature.configure(TracerDynamicFeature.java:60)
10:03:43,850 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:113)
10:03:43,850 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:354)
10:03:43,850 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:277)
10:03:43,855 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:228)
10:03:43,855 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:201)
10:03:43,856 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:187)
10:03:43,856 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:164)
10:03:43,857 INFO  [stdout] (Thread-558)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:81)
10:03:43,857 INFO  [stdout] (Thread-558)        at myProject.war//org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand.executeCommand(RefreshRegistryCommand.java:115)
10:03:43,858 INFO  [stdout] (Thread-558)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
10:03:43,859 INFO  [stdout] (Thread-558)
10:03:43,859 INFO  [stdout] (Thread-559) HOTSWAP AGENT: 10:03:43.840 ERROR (org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand) - Could not reload rest class org.my.Project.FrontPageController
10:03:43,860 INFO  [stdout] (Thread-559) org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: javax.servlet.ServletContext
10:03:43,861 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:77)
10:03:43,861 INFO  [stdout] (Thread-559)        at javax.servlet.api@2.0.0.Final//com.sun.proxy.$Proxy220.getAttribute(Unknown Source)
10:03:43,861 INFO  [stdout] (Thread-559)        at org.wildfly.microprofile.opentracing-smallrye@24.0.1.Final//org.wildfly.microprofile.opentracing.smallrye.TracerDynamicFeature.configure(TracerDynamicFeature.java:60)
10:03:43,862 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:113)
10:03:43,862 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:354)
10:03:43,863 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:277)
10:03:43,869 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:228)
10:03:43,870 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:201)
10:03:43,871 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:187)
10:03:43,871 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:164)
10:03:43,872 INFO  [stdout] (Thread-559)        at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:81)
10:03:43,873 INFO  [stdout] (Thread-559)        at myProject.war//org.hotswap.agent.plugin.resteasy.RefreshRegistryCommand.executeCommand(RefreshRegistryCommand.java:115)
10:03:43,873 INFO  [stdout] (Thread-559)        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
10:03:43,873 INFO  [stdout] (Thread-559)
```

(For security reasons I've changed the names of the .war and the controller file paths.)

**Comment by skybber** [comment]
Could you try resteasyregistry plugin instead of rest easy? I don't know a lot of reast easy plugins, they have been not maintained for some time ...

**Comment by Matsuuu** [comment]
I'm sorry I'm quite new to hotswapagent.

How do I enable resteasyregistry instead of resteasy?

**Comment by skybber** [comment]
It can be disablbed using  `-javaagent:"<path_to_agent>hotswap-agent.jar=disablePlugin=<plugin_name>`

**Comment by Matsuuu** [comment]
I can't seem to be able to disable the class.

I ran the opts
`XXaltjvm=dcevm -javaagent:C:\prog\wildfly20\dcevm\dcevm-11.0.11+1\lib\hotswap\hotswap-agent.jar=disablePlugin=RestEasy`

But still am running into the error

**Comment by skybber** [comment]
Please remove `-XXaltjvm=dcevm` and add `-XX:HotswapAgent=external`

**Comment by Matsuuu** [comment]
I changed it to -XX:HotswapAgent=external and disabled the plugin `ResteasyRegistry`. 

Now i got everything working!

Thanks a lot of the support and the awesome work on this tool
