### ISSUE TITLE
HotSwapAgent + JetBrainsRuntime 17 not working

### ISSUE THREAD

**Issue by lorenzoferrante** [HotswapProjects/HotswapAgent#416]
I'm trying to use HotSwap Agent with JBR 17.0.1 and I'm using hotswap-agent-1.4.2-SNAPSHOT.jar.
When I run the app this is the errors I get:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final jdk.internal.loader.URLClassPath java.net.URLClassLoader.ucp accessible: module java.base does not "opens java.net" to unnamed module @1e730495
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.hotswap.agent.util.classloader.URLClassLoaderHelper.prependClassPath(URLClassLoaderHelper.java:86)
        at org.hotswap.agent.config.PluginConfiguration.initExtraClassPath(PluginConfiguration.java:200)
        at org.hotswap.agent.config.PluginConfiguration.init(PluginConfiguration.java:181)
        at org.hotswap.agent.config.PluginConfiguration.<init>(PluginConfiguration.java:80)
        at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:191)
        at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:316)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
```

And also:
```
HOTSWAP AGENT: 16:33:56.160 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.lorenzoferrante.demo.HelloServlet] (autoHotswap)
HOTSWAP AGENT: 16:33:56.162 ERROR (org.hotswap.agent.plugin.jdk.JdkPlugin) - flushClassInfoCache() exception Unable to make public final void com.sun.beans.util.Cache.clear() accessible: module java.desktop does not "exports com.sun.beans.util" to unnamed module @1e730495.
```

These are the java opts:
```
-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n 
-javaagent:/opt/hotswap-agent/hotswap-agent.jar 
-Dextra.class.path=/extra_class_path 
-Dwebapp.dir=/webapp_dir 
--add-opens java.base/jdk.internal.loader=ALL-UNNAMED 
--add-opens java.desktop/com.sun.beans.introspect=ALL-UNNAMED
```

How can I fix these errors? 

Thank you very much

**Comment by skybber** [comment]
Could you try `--add-opens java.base/java.net=ALL-UNNAMED` ?

**Comment by lorenzoferrante** [comment]
I've added `--add-opens java.base/java.net=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED` and now the errors are gone and when I edit a class it gives me this log:
```
HOTSWAP AGENT: 17:36:21.146 RELOAD (org.hotswap.agent.config.PluginManager) - Reloading classes [com.lorenzoferrante.demo.HelloServlet] (autoHotswap)
```
so I assume it's working, but sadly nothing is happening in the webapp

**Comment by skybber** [comment]
Are you using `-XX:+AllowEnhancedClassRedefinition` ?

**Comment by skybber** [comment]
You can also use `-XX:HotswapAgent=external`

**Comment by lorenzoferrante** [comment]
Yes, here's all my java opts:
```
ENV JAVA_OPTS="-XX:+AllowEnhancedClassRedefinition -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n -javaagent:/opt/hotswap-agent/hotswap-agent.jar -Dextra.class.path=/extra_class_path -Dwebapp.dir=/webapp_dir --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.desktop/com.sun.beans.introspect=ALL-UNNAMED --add-opens java.desktop/com.sun.beans.util=ALL-UNNAMED --add-exports java.desktop/com.sun.beans.util=ALL-UNNAMED --add-exports java.base/java.net=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED"
```

**Comment by skybber** [comment]
Is the standard redefinition working?

**Comment by lorenzoferrante** [comment]
I'm sorry, what do you mean by standard redefinition?

**Comment by skybber** [comment]
If the hotswap is working without HotswapAgent+AllowEnhancedClassRedefinition - in standard JVM without any addition.

**Comment by lorenzoferrante** [comment]
Oh I'm sorry, yes it's working for example with Java 11 + Tomcat in Intellij but the dockerized container with jbr17.0.1 + HotswapAgent is not.

**Comment by skybber** [comment]
No problem, did you see https://github.com/HotswapProjects/hotswap-docklands ?

**Comment by skybber** [comment]
Is there `hotswap-agent.properties` in `demo-1.0-SNAPSHOT.war` ?
https://github.com/skybber/ping/blob/master/src/main/resources/hotswap-agent.properties

**Comment by lorenzoferrante** [comment]
Problem solved. I was updating a variable inside the `init`method:
```
public void init() {
        message = "Hello World!";
}
```
and probably that's not possible.
Once I moved the variable in the `doGet`method everything is working fine.
We can close this issue. Thank you so much for your help!
