### ISSUE TITLE
java.lang.AbstractMethodError in com.sun.proxy.$Proxy117

### ISSUE THREAD

**Issue by angryfang** [HotswapProjects/HotswapAgent#429]
Use jdk proxy thrift iface Implement class，when add or sub filed in thrift method, sometimes hotswap failed。when client calls the server， I got the error in server
```java
java.lang.AbstractMethodError: com.test.HelloThriftService.hello(Ljava/lang/String;)Ljava/lang/String;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
```

I  found proxy class signatureMap equal judge sometimes are not right, and I made some fixed up as below
```java
public class ReloadJavaProxyCommand extends MergeableCommand {
   //......

    public void executeSingleCommand() {
        try {
            Class<?> clazz = classLoader.loadClass(className);
            Map<String, String> signatureMap = ProxyClassSignatureHelper.getNonSyntheticSignatureMap(clazz);
            LOGGER.debug("executeSingleCommand class:{}, signature equals:{}", className, signatureMap.equals(signatureMapOrig));
            if (!signatureMap.equals(signatureMapOrig) || !isImplementInterface(signatureMap, clazz)) {
                byte[] generateProxyClass = ProxyGenerator.generateProxyClass(className, clazz.getInterfaces());
                Map<Class<?>, byte[]> reloadMap = new HashMap<>();
                reloadMap.put(clazz, generateProxyClass);
                PluginManager.getInstance().hotswap(reloadMap);
                LOGGER.reload("Class '{}' has been reloaded.", className);
            }
            ProxyPlugin.removeProxyDefiningClassName(className);
        } catch (ClassNotFoundException e) {
            LOGGER.error("Error redefining java proxy {}", e, className);
        }
    }

    // Whether all methods of the interface are implemented
    private boolean isImplementInterface(Map<String, String> signatureMap, Class<?> clazz) {
        String clazzSignature = "";
        try {
            clazzSignature = ProxyClassSignatureHelper.getJavaClassSignature(clazz).replaceAll("final ", "");
            LOGGER.debug("clazzSignature: {}", clazzSignature);
        } catch (Exception e) {
            LOGGER.error("Error getJavaClassSignature {}", clazz, e);
            return true;
        }
        for (Map.Entry<String, String> entry : signatureMap.entrySet()) {
            if(clazzSignature.contains(entry.getKey()) && entry.getValue().contains("public abstract")) {
                LOGGER.debug("{} Signature: {}", entry.getKey(), entry.getValue());
                String[] methodSigatures = entry.getValue().replaceAll("abstract ", "").split(";");
                for (String methodSigature : methodSigatures) {
                    if(!clazzSignature.contains(methodSigature)) {
                        return false;
                    }
                }
            }
        }
        return true;
    }
}
```

**Comment by skybber** [comment]
Is it java17 related? Jdk proxy has changed on java17 , there is no fix for it in the HA yet.

**Comment by angryfang** [comment]
> Is it java17 related? Jdk proxy has changed on java17 , there is no fix for it in the HA yet. (I see 1.8.0_181 but not sure if you are really using java8)

I use java8 and java11

**Comment by skybber** [comment]
Could you please make PR?

**Comment by angryfang** [comment]
> Could you please make PR?

I have just submit my change to personal fork project， and create a pull request， is that PR meaning？

**Comment by skybber** [comment]
yes
