### ISSUE TITLE
Too many open files exception for jbr-17

### ISSUE THREAD

**Issue by Mugenor** [HotswapProjects/HotswapAgent#440]
Hi

We have a pretty big project in monorepository with a lot of modules. And when I try to use hotswap agent with jbr-17 JDK I get a lot of errors like this one during spring context initialization (where `__dirname__` is the directory with compiled classes):

```
java.nio.file.FileSystemException: __dirname__: Too many open files
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/sun.nio.fs.MacOSXWatchService$MacOSXWatchKey$DirectorySnapshot.create(MacOSXWatchService.java:609)
	at java.base/sun.nio.fs.MacOSXWatchService$MacOSXWatchKey$DirectoryTreeSnapshot.createForOneDirectory(MacOSXWatchService.java:482)
	at java.base/sun.nio.fs.MacOSXWatchService$MacOSXWatchKey$DirectoryTreeSnapshot.build(MacOSXWatchService.java:461)
	at java.base/sun.nio.fs.MacOSXWatchService$MacOSXWatchKey.enable(MacOSXWatchService.java:350)
	at java.base/sun.nio.fs.MacOSXWatchService.register(MacOSXWatchService.java:107)
	at java.base/sun.nio.fs.UnixPath.register(UnixPath.java:885)
	at org.hotswap.agent.watch.nio.WatcherNIO2.register(WatcherNIO2.java:72)
	at org.hotswap.agent.watch.nio.WatcherNIO2.access$000(WatcherNIO2.java:42)
	at org.hotswap.agent.watch.nio.WatcherNIO2$1.preVisitDirectory(WatcherNIO2.java:61)
	at org.hotswap.agent.watch.nio.WatcherNIO2$1.preVisitDirectory(WatcherNIO2.java:58)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2817)
	at org.hotswap.agent.watch.nio.WatcherNIO2.registerAll(WatcherNIO2.java:58)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.addDirectory(AbstractNIO2Watcher.java:206)
	at org.hotswap.agent.watch.nio.AbstractNIO2Watcher.addEventListener(AbstractNIO2Watcher.java:111)
	at org.hotswap.agent.annotation.handler.WatchHandler.registerResourceListener(WatchHandler.java:140)
	at org.hotswap.agent.annotation.handler.WatchHandler.registerResources(WatchHandler.java:109)
	at org.hotswap.agent.annotation.handler.WatchHandler.initMethod(WatchHandler.java:63)
	at org.hotswap.agent.annotation.handler.AnnotationProcessor.processMethodAnnotations(AnnotationProcessor.java:153)
	at org.hotswap.agent.annotation.handler.AnnotationProcessor.processAnnotations(AnnotationProcessor.java:120)
	at org.hotswap.agent.config.PluginRegistry.initializePlugin(PluginRegistry.java:181)
```
I'm using these java parameters: `-XX:-MaxFDLimit -XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar`
I tried to raise the maxfiles limit in OS but it didn't help in any way.

The interesting thing is that when I'm using [trava-jdk-11-dcevm](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases) it works out of the box without a problem.
I'm using macOS Monterey 12, btw.

Can you help me to solve this issue, please?

**Comment by theigl** [comment]
I had the same issue and solved it like this: https://apple.stackexchange.com/a/420678

**Comment by Mugenor** [comment]
It worked, thank you!
Btw, this parameter still required for the java process you want to use hotswap with.
