### ISSUE TITLE
Exceptions when reloading Spring related classes

### ISSUE THREAD

**Issue by Kidlike** [HotswapProjects/HotswapAgent#45]
Hi,

Here are some of the exceptions thrown when I recompile the classes while in debug mode:

```
Exception in thread "Thread-17" HOTSWAP AGENT: 9:32:13.911 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class com/company/cts/training/domain/TrainingCertification$22 in classLoader ContextLoader@1349563128
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:73)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.IllegalArgumentException: Illegal arguments method org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent([interface org.springframework.core.type.classreading.MetadataReader]) on org.springframework.context.annotation.ClassPathBeanDefinitionScanner@3e281ac9, params [org.springframework.core.type.classreading.SimpleMetadataReader@54c8ce83]
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:49)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.isCandidateComponent(ClassPathBeanDefinitionScannerAgent.java:306)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.resolveBeanDefinition(ClassPathBeanDefinitionScannerAgent.java:224)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:130)
    ... 5 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@4d38eed8
    at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:47)
    ... 8 more

HOTSWAP AGENT: 9:32:13.912 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class com/company/cts/training/controllers/UserTrainingAssignmentController in classLoader ContextLoader@1349563128
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:73)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.IllegalArgumentException: Illegal arguments method org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent([interface org.springframework.core.type.classreading.MetadataReader]) on org.springframework.context.annotation.ClassPathBeanDefinitionScanner@3e281ac9, params [org.springframework.core.type.classreading.SimpleMetadataReader@19d71fa8]
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:49)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.isCandidateComponent(ClassPathBeanDefinitionScannerAgent.java:306)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.resolveBeanDefinition(ClassPathBeanDefinitionScannerAgent.java:224)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:130)
    ... 5 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@2a21ef14
    at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:47)
    ... 8 more

HOTSWAP AGENT: 9:32:13.929 ERROR (org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand) - Error refreshing class com/company/cts/site/domain/UserSiteRole_$$_javassist_48 in classLoader ContextLoader@1349563128
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:73)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.IllegalArgumentException: Illegal arguments method org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent([interface org.springframework.core.type.classreading.MetadataReader]) on org.springframework.context.annotation.ClassPathBeanDefinitionScanner@3e281ac9, params [org.springframework.core.type.classreading.SimpleMetadataReader@49e3c6d]
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:49)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.isCandidateComponent(ClassPathBeanDefinitionScannerAgent.java:306)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.resolveBeanDefinition(ClassPathBeanDefinitionScannerAgent.java:224)
    at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:130)
    ... 5 more
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@23cb7d87
    at sun.reflect.GeneratedMethodAccessor133.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.hotswap.agent.util.ReflectionHelper.invoke(ReflectionHelper.java:47)
    ... 8 more
```

I am running this jvm:

```
HOTSWAP AGENT: 10:29:33.958 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.1-beta4} - unlimited runtime class redefinition.
HOTSWAP AGENT: 10:29:34.795 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver]
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.2) (7u65-2.5.2-3~14.04)
Dynamic Code Evolution 64-Bit Server VM (build 24.51-b03-dcevmfull-3, mixed mode)
```

Bare in mind that the codebase in this application is big (several mlocs). When I clicked compile in 1 class in debug mode, 450 classes where reloaded. Several had similar exceptions.
I would have to run the test again if you want a full and clean log.

Does this look like something that could be an environment/setup issue or is it a bug in the agent?

Thanks!

**Comment by edudant** [comment]
Please reopen if still valid.
