### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hotswap/agent/config/PluginManager

### ISSUE THREAD

**Issue by Natank25** [HotswapProjects/HotswapAgent#453]
Hi,
I tried to use HotswapAgent with minecraft fabric 1.19 modding, but  I can't start the game. I followed the instruction but I get this error:

```HOTSWAP AGENT: 12:45:31.657 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.1} - unlimited runtime class redefinition.
HOTSWAP AGENT: 12:45:31.886 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [JdkPlugin, Hotswapper, WatchResources, ClassInitPlugin, AnonymousClassPatch, Hibernate, Hibernate3JPA, Hibernate3, Spring, Jersey1, Jersey2, Jetty, Tomcat, ZK, Logback, Log4j2, MyFaces, Mojarra, Omnifaces, ELResolver, WildFlyELResolver, OsgiEquinox, Owb, Proxy, WebObjects, Weld, JBossModules, ResteasyRegistry, Deltaspike, GlassFish, Vaadin, Wicket, CxfJAXRS, FreeMarker, Undertow, MyBatis]
Starting HotswapAgent 'C:\Program Files\Java\jbrsdk_dcevm-17-windows-x64-b135.1\jbrsdk\lib\hotswap\hotswap-agent.jar'
[12:45:32] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.11
[12:45:33] [ERROR] [FabricLoader/]: Uncaught exception in thread "main"
java.lang.NoClassDefFoundError: org/hotswap/agent/config/PluginManager
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:642)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:245)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:176)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:666)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.getLogger(Log4jLogHandler.java:58)
	at net.fabricmc.loader.impl.game.minecraft.Log4jLogHandler.log(Log4jLogHandler.java:51)
	at net.fabricmc.loader.impl.util.log.BuiltinLogHandler.replay(BuiltinLogHandler.java:128)
	at net.fabricmc.loader.impl.util.log.Log.init(Log.java:34)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.setupLogHandler(MinecraftGameProvider.java:367)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:338)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.ClassNotFoundException: can't load class org.hotswap.agent.config.PluginManager at C:\Program Files\Java\jbrsdk_dcevm-17-windows-x64-b135.1\jbrsdk\lib\hotswap\hotswap-agent.jar as it hasn't been exposed to the game (yet? The system property fabric.classPathGroups may not be set correctly in-dev)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:240)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more
```

I also tried checking other issues but it still didn't work.

Do you have any idea on why and how I can fix it ? Or do I need to create an issue on the Fabric Loader github ?
Thank you in advance

**Comment by skybber** [comment]
You can check if plugin classes are injected into `KnotClassLoader` by this code:

https://github.com/HotswapProjects/HotswapAgent/blob/master/hotswap-agent-core/src/main/java/org/hotswap/agent/config/PluginManager.java#L185

it should call `classLoaderPatcher.patch(...)`, passing `classLoader=KnotClassLoader`. If the KnotClassLoader is patched, then the problem will be in `KnotClassDelegate` and it can be solved by a new HA plugin patching to `launch.knot.KnotClassDelegate`

**Comment by Natank25** [comment]
Well I managed to make it work by using the core and not the fatjar.
I tried passing `classLoader=KnotClassLoader` and i got an error.
ThanIks anyways

**Comment by SuperCoolMC** [comment]
For anyone who is having the same issue, I managed to fix this with the fatjar by passing the path to the fatjar into the VM options using `-Dfabric.systemLibraries=<path to fatjar>` (https://github.com/FabricMC/fabric-loader/pull/680)
