### ISSUE TITLE
Spring plugin - ProxyReplacer dependency

### ISSUE THREAD

**Issue by edudant** [HotswapProjects/HotswapAgent#52]
PluginClass must not contain dependencies to any framework specific classes. If launched in multiple classloader envorinment (servlet container), an error occures:
  java.lang.NoClassDefFoundError: net/sf/cglib/proxy/Callback

Framework specific code should be run:
- using java reflection with correct classloader
- or via invocation from modified class inside application classloader.

See http://www.hotswapagent.org/how-does-it-work/hotswap-agent-implementation for more information.

There is example project for [plain servlet](https://github.com/HotswapProjects/HotswapAgentExamples/tree/master/custom-plugin) and with [spring and hibernate](https://github.com/HotswapProjects/HotswapAgentExamples/tree/master/spring-hibernate).

**Comment by srandy** [comment]
This issue still seen with the latest code. 

>HOTSWAP AGENT: 1:32:48.345 ERROR (org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater) - Creating a proxy failed
**org.hotswap.agent.javassist.NotFoundException: net.sf.cglib.proxy.MethodInterceptor**
	at org.hotswap.agent.javassist.ClassPool.get(ClassPool.java:445)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.buildProxyCallbackClass(EnhancerProxyCreater.java:221)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.getProxyCreationMethod(EnhancerProxyCreater.java:115)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.create(EnhancerProxyCreater.java:83)
	at org.hotswap.agent.plugin.spring.getbean.EnhancerProxyCreater.createProxy(EnhancerProxyCreater.java:78)
	at org.hotswap.agent.plugin.spring.getbean.ProxyReplacer.register(ProxyReplacer.java:46)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968)

**Comment by erkieh** [comment]
Please provide a quickstart demonstrating the problem. I have used it with some spring 3 and 4 versions and can't say i have seen this issue again.

**Comment by srandy** [comment]
The problem is with Spring 4.1.5 release. It doesn't show up with spring 4.0.X versions.

But with Spring 4.0.X I see a different issue.

>HOTSWAP AGENT: 10:59:23.399 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.proxy.ProxyPlugin' class 'com/Acme/service/AcmeServiceImpl$$EnhancerBySpringCGLIB$$b7103509'.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:157)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.redefineClasses(InstrumentationImpl.java:170)
	at org.hotswap.agent.config.PluginManager.hotswap(PluginManager.java:254)
	at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin$1.executeCommand(HotswapperPlugin.java:94)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: No such field class org.hotswap.agent.plugin.proxy.hscglib.GeneratorParams.getParam on org.hotswap.agent.plugin.proxy.hscglib.GeneratorParams@21079b1d
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParams(GeneratorParametersTransformer.java:116)
	at org.hotswap.agent.plugin.proxy.ProxyPlugin.transformCglibProxy(ProxyPlugin.java:71)
	... 14 more
Caused by: java.lang.IllegalArgumentException: No such field class org.hotswap.agent.plugin.proxy.hscglib.GeneratorParams.getParam on org.hotswap.agent.plugin.proxy.hscglib.GeneratorParams@21079b1d
	at org.hotswap.agent.util.ReflectionHelper.get(ReflectionHelper.java:84)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParams.valueOf(GeneratorParams.java:79)
	at org.hotswap.agent.plugin.proxy.hscglib.GeneratorParametersTransformer.getGeneratorParams(GeneratorParametersTransformer.java:114)
	... 15 more

**Comment by erkieh** [comment]
About the 4.0.x issue:
Are you sure you don't have any local changes?
For some reason ReflectionHelper is looking for a field named "getParam" but the String literal for the fieldname in 
https://github.com/HotswapProjects/HotswapAgent/blob/4e1643652a9cb8719cd6a8cc6117a80b12eda092/plugin/hotswap-agent-proxy-plugin/src/main/java/org/hotswap/agent/plugin/proxy/hscglib/GeneratorParams.java
is "param"

**Comment by srandy** [comment]
I didn't have any changes. But, I tried again after rebuilding, i don't see the issue any more. Thanks for checking on it, i will let you know if I see it again.

On a side note,  I had to use a older revision ** Merge pull request #61 from frankdavid/master ** - commit sha1 - eff4f76f6242565c2aa9617a4ef67019ff9e5c1f because the HEAD revision from git is failing during 'mvn clean install' with error 
``` java 
HOTSWAP AGENT: 9:56:53.480 ERROR (org.hotswap.agent.plugin.weld.command.BeanDeploymentArchiveAgent) - basePackage '/C:/workspace/git/HotswapAgent/plugin/hotswap-agent-weld-plugin/target/test-classes' not associated with any archiveAgent
Tests run: 7, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 3.384 sec <<< FAILURE! - in org.hotswap.agent.plugin.weld.WeldPluginTest
hotswapPrototypeTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.232 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.swapClasses(WeldPluginTest.java:166)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapPrototypeTest(WeldPluginTest.java:125)

hotswapSeviceAddMethodTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 1.102 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.swapClasses(WeldPluginTest.java:166)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapSeviceAddMethodTest(WeldPluginTest.java:77)

hotswapRepositoryNewMethodTest(org.hotswap.agent.plugin.weld.WeldPluginTest)  Time elapsed: 0.034 sec  <<< ERROR!
java.lang.NullPointerException: null
	at java.lang.String.length(String.java:623)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:414)
	at java.lang.StringBuilder.append(StringBuilder.java:132)
	at org.hotswap.agent.plugin.weld.testBeans.HelloServiceImpl.hello(HelloServiceImpl2.java:22)
	at org.hotswap.agent.plugin.weld.WeldPluginTest.hotswapRepositoryNewMethodTest(WeldPluginTest.java:108)


Results :

Failed tests: 
  WeldPluginTest.hotswapPrototypeTest:125->swapClasses:166 null
  WeldPluginTest.hotswapSeviceAddMethodTest:77->swapClasses:166 null

Tests in error: 
  WeldPluginTest.hotswapRepositoryNewMethodTest:108 » NullPointer

Tests run: 7, Failures: 2, Errors: 1, Skipped: 0
```
