### ISSUE TITLE
How do I run this from gradle / openjdk? (Exception on changes)

### ISSUE THREAD

**Issue by reubenfirmin** [HotswapProjects/HotswapAgent#521]
With gradle, I'm using openjdk 17 rather than the JBR. Here's what I've tried so far; it starts the agent, but does not pick up changes.

```
val jvmMain by getting {
   dependencies {
       // ...
       implementation("org.hotswapagent:hotswap-agent-core:1.4.0")
   } 
}

application {
    mainClass.set("my.main.class")

    tasks.named<JavaExec>("run") {
        doFirst {
            // a little brittle but it works
            val hotswapAgentCore = configurations.first { it.name == "allSourceSetsCompileDependenciesMetadata" }.let {
                it.fileCollection(it.allDependencies.first { it.name.startsWith("hotswap") })
                    .files
                    .first()
            }

            if (hotswapAgentCore != null) {
                println("Monitoring ${project.buildDir.absolutePath}/classes/kotlin/jvm/main/ for changes!")
                jvmArgs(
                    "-javaagent:${hotswapAgentCore.absolutePath}=autoHotswap=true",
                    "-Dhotswap.classes.dir=${project.buildDir.absolutePath}/classes/kotlin/jvm/main/"
                )
            } else {
                throw IllegalStateException("Hotswap Agent Core dependency not found in the 'implementation' configuration.")
            }
        }

        val main by sourceSets.getting
        args = main.output.asPath.split(":")
    }
}
```

When I do `gradle run`, I get:

```
HOTSWAP AGENT: 05:59:16.316 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {1.4.0} - unlimited runtime class redefinition.
HOTSWAP AGENT: 05:59:16.390 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.hotswapper.HotswapperPlugin' initialized in ClassLoader 'jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7'.
HOTSWAP AGENT: 05:59:16.397 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, JdkPlugin, AnonymousClassPatch, ClassInitPlugin, WatchResources]
...
```

It's a little slow to detect changes, but when it happens I get an exception:

```
HOTSWAP AGENT: 05:59:47.088 ERROR (org.hotswap.agent.annotation.handler.WatchEventCommand) - InvocationTargetException in method watchReload on plugin org.hotswap.agent.plugin.hotswapper.HotswapperPlugin
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:190)
        at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:98)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hotswap.agent.util.classloader.ClassLoaderHelper
        at org.hotswap.agent.plugin.hotswapper.HotswapperPlugin.watchReload(HotswapperPlugin.java:74)
        ... 7 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.findLoadedClass(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @67117f44 [in thread "Thread-22"]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at org.hotswap.agent.util.classloader.ClassLoaderHelper.<clinit>(ClassLoaderHelper.java:37)
        ... 8 more
```

**Comment by reubenfirmin** [comment]
Great, solved. Thank you! 

FYI my final config here:

```
application {
    mainClass.set("my.main.class")

    tasks.named<JavaExec>("run") {

        // a little brittle but it works
        val hotswapAgentCore = configurations.first { it.name == "allSourceSetsCompileDependenciesMetadata" }.let {
            it.fileCollection(it.allDependencies.first { it.name.startsWith("hotswap") })
                .files
                .first()
        }

        if (hotswapAgentCore != null) {
            println("Monitoring ${project.buildDir.absolutePath}/classes/kotlin/jvm/main/ for changes!")
            jvmArgs(
                "-javaagent:${hotswapAgentCore.absolutePath}=autoHotswap=true",
                "--add-opens", "java.base/java.lang=ALL-UNNAMED",
                "--add-opens", "java.base/jdk.internal.loader=ALL-UNNAMED",
                "--add-opens", "java.base/java.io=ALL-UNNAMED",
                "--add-opens", "java.desktop/java.beans=ALL-UNNAMED",
                "--add-opens", "java.desktop/com.sun.beans=ALL-UNNAMED",
                "--add-opens", "java.desktop/com.sun.beans.introspect=ALL-UNNAMED",
                "--add-opens", "java.desktop/com.sun.beans.util=ALL-UNNAMED",
                // TODO try using the non-deprecated alternative to buildDir (I couldn't figure out how to get a path from it in 60s so gave up)
                "-Dhotswap.classes.dir=${project.buildDir.absolutePath}/classes/kotlin/jvm/main/"

            )
        } else {
            throw IllegalStateException("Hotswap Agent Core dependency not found in the 'implementation' configuration.")
        }

        val main by sourceSets.getting
        args = main.output.asPath.split(":")
    }
}
```
