### ISSUE TITLE
Application run failed

### ISSUE THREAD

**Issue by lei-huang-netty** [HotswapProjects/HotswapAgent#523]
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "org.hotswap.agent.plugin.spring.reload.SpringChangedAgent.onEvent(Lorg/hotswap/agent/plugin/spring/listener/SpringEvent;)V" the class loader (instance of org/springframework/boot/loader/LaunchedURLClassLoader) of the current class, org/hotswap/agent/plugin/spring/reload/SpringChangedAgent, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for interface org/hotswap/agent/plugin/spring/listener/SpringListener have different Class objects for the type org/hotswap/agent/plugin/spring/listener/SpringEvent used in the signature
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_372]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_372]
	at org.hotswap.agent.plugin.spring.SpringPlugin.init(SpringPlugin.java:86) ~[classes!/:1.4.2-SNAPSHOT]
	... 24 common frames omitted

**Comment by lei-huang-netty** [comment]
Versions:

OS: Oracle Linux Server 7.9
Hotswap Agent: [1.4.2-SNAPSHOT](https://github.com/HotswapProjects/HotswapAgent/releases)
DCEVM: [dcevm8u282b08](https://github.com/TravaOpenJDK/trava-jdk-8-dcevm/releases/tag/dcevm8u282b08)
Spring: 5.3.23
Spring-boot: 2.7.5
Tomcat: 9.0.68

**Comment by lei-huang-netty** [comment]
use java -jar
