### ISSUE TITLE
Multiple instances of MapperScannerRegistrar appear, causing subsequent updates to fail

### ISSUE THREAD

**Issue by XuxuGood** [HotswapProjects/HotswapAgent#538]
Excuse me, Why do springChangeAgents register so many, and all are the same MapperScannerRegistrar

![WX20240305-224309@2x](https://github.com/HotswapProjects/HotswapAgent/assets/45960164/bb2303a7-6d2c-49e3-9d7d-2b3cdd7cc0bb)

Only when these springChangeAgents execute and calls processPropertyPlaceHolders array first MapperScannerRegistrar contains applicationContext, All remaining applicationContext is empty, resulting in the following error. How do I solve this problem?

HOTSWAP AGENT: 22:44:40.589 INFO (org.hotswap.agent.plugin.spring.reload.SpringBeanReload) - ##### [2th] finish reloading 'org.springframework.beans.factory.support.DefaultListableBeanFactory@6db616f0', it cost 2027ms
HOTSWAP AGENT: 22:44:40.589 ERROR (org.hotswap.agent.plugin.spring.reload.XmlsChangedCommand) - Error invoking method
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hotswap.agent.plugin.spring.reload.SpringChangedReloadCommand.executeCommand(SpringChangedReloadCommand.java:33)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.hotswap.agent.plugin.spring.reload.SpringBeanReload.invokeBeanFactoryPostProcessors(SpringBeanReload.java:655)
        at org.hotswap.agent.plugin.spring.reload.SpringBeanReload.doReload(SpringBeanReload.java:296)
        at org.hotswap.agent.plugin.spring.reload.SpringBeanReload.reload(SpringBeanReload.java:259)
        at org.hotswap.agent.plugin.spring.reload.SpringChangedAgent.doReload(SpringChangedAgent.java:201)
        at org.hotswap.agent.plugin.spring.reload.SpringChangedAgent.reloadAll(SpringChangedAgent.java:189)
        at org.hotswap.agent.plugin.spring.reload.SpringChangedAgent.reload(SpringChangedAgent.java:140)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hotswap.agent.plugin.spring.reload.SpringBeanReload.invokePostProcessorRegistrationDelegate(SpringBeanReload.java:666)
        at org.hotswap.agent.plugin.spring.reload.SpringBeanReload.invokeBeanFactoryPostProcessors(SpringBeanReload.java:646)
        ... 11 more
Caused by: java.lang.NullPointerException
        at org.mybatis.spring.mapper.MapperScannerConfigurer.processPropertyPlaceHolders(MapperScannerConfigurer.java:386)
        at org.mybatis.spring.mapper.MapperScannerConfigurer.postProcessBeanDefinitionRegistry(MapperScannerConfigurer.java:354)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:142)
        ... 17 more

**Comment by homejim** [comment]
https://github.com/homejim/HotswapAgent/releases/tag/1.4.2.1-SNAPSHOT 

This package works correctly and resolves the issue.

**Comment by skybber** [comment]
fixed by @homejim in https://github.com/homejim/HotswapAgent/releases/tag/1.4.2.1-SNAPSHOT
