### ISSUE TITLE
Whether jdk21 version is supported

### ISSUE THREAD

**Issue by dazer007** [HotswapProjects/HotswapAgent#540]
There is no problem using JDK jbr17. An error is reported when using JDK jbr21 to start。

```shell
# jvm options
-XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
```

```xml
Caused by: java.lang.IllegalAccessError: failed to access class sun.nio.ch.ChannelInputStream from class org.hotswap.agent.util.IOUtils (sun.nio.ch.ChannelInputStream is in module java.base of loader 'bootstrap'; org.hotswap.agent.util.IOUtils is in unnamed module of loader 'app')
	at org.hotswap.agent.util.IOUtils.extractFileNameFromInputStream(IOUtils.java:176)
	at org.hotswap.agent.util.IOUtils.extractFileNameFromInputSource(IOUtils.java:221)
	at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java)
	at org.apache.ibatis.parsing.XPathParser.<init>(XPathParser.java:127)
	at com.baomidou.mybatisplus.core.MybatisXMLConfigBuilder.<init>(MybatisXMLConfigBuilder.java:82)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:473)
```

**Comment by skybber** [comment]
Thanks for report, should be fixed in new [1.4.2-SNAPSHOT release](https://github.com/HotswapProjects/HotswapAgent/releases/tag/1.4.2-SNAPSHOT)
