### ISSUE TITLE
Spring Plugin with Grails hitting a snag

### ISSUE THREAD

**Issue by davydotcom** [HotswapProjects/HotswapAgent#553]
Getting an error it appears with micronaut combined with spring boot in Grails framework 6.1.2 (Spring 5.3) on JBR 17 (JDK 17)

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2805)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867)
        at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1703)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:356)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
        at grails.boot.GrailsApp.createApplicationContext(GrailsApp.groovy:157)

```

This may be a simple thing to fix but new to this library. Hoping to make this work

**Comment by vsachinv** [comment]
@davydotcom  Did you get any solution ?

**Comment by sbglasius** [comment]
@davydotcom Perhaps this is related: https://github.com/apache/grails-core/issues/15207
