### ISSUE TITLE
Tomcat 8 deployment fails with spring

### ISSUE THREAD

**Issue by gdrouet** [HotswapProjects/HotswapAgent#63]
WatchHandler.registerResources() fails with tomcat 8 (everything works fine with tomcat 7). Seems to be a classpath issue. Here is a stacktrace with a spring config file               :

at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'datasyncManagerFactory' defined in URL [jar:file:/D:/tools/apache-tomcat/8.0.3/webapps/arsm-ws/WEB-INF/lib/app-3.2.jar!/spring/app-core-datasource.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[AbstractBeanFactory$1.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[DefaultSingletonBeanRegistry.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[AbstractBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[AbstractBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:424) ~[DefaultListableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:277) ~[BeanFactoryUtils.class:3.1.2.RELEASE]
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:139) ~[PersistenceExceptionTranslationInterceptor.class:3.1.2.RELEASE]
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.<init>(PersistenceExceptionTranslationInterceptor.java:79) ~[PersistenceExceptionTranslationInterceptor.class:3.1.2.RELEASE]
                at org.springframework.dao.annotation.PersistenceExceptionTranslationAdvisor.<init>(PersistenceExceptionTranslationAdvisor.java:70) ~[PersistenceExceptionTranslationAdvisor.class:3.1.2.RELEASE]
                at org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor.setBeanFactory(PersistenceExceptionTranslationPostProcessor.java:103) ~[PersistenceExceptionTranslationPostProcessor.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1475) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1443) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                ... 55 more
Caused by: java.lang.NullPointerException
                at org.hotswap.agent.annotation.handler.WatchHandler.registerResources(WatchHandler.java:82) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.annotation.handler.WatchHandler.initMethod(WatchHandler.java:48) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.annotation.handler.AnnotationProcessor.processMethodAnnotations(AnnotationProcessor.java:135) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.annotation.handler.AnnotationProcessor.processAnnotations(AnnotationProcessor.java:102) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.config.PluginRegistry.initializePlugin(PluginRegistry.java:158) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.util.PluginManagerInvoker.callInitializePlugin(PluginManagerInvoker.java:26) ~[hotswap-agent.jar:0.2]
                at org.hotswap.agent.plugin.hibernate.HibernatePersistenceHelper.initPlugin(HibernatePersistenceHelper.java:77) ~[catalina.jar:0.2]
                at org.hotswap.agent.plugin.hibernate.HibernatePersistenceHelper.createContainerEntityManagerFactoryProxy(HibernatePersistenceHelper.java:43) ~[catalina.jar:0.2]
                at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java) ~[HibernatePersistenceProvider.class:4.3.7.Final]
                at org.hibernate.ejb.HibernatePersistence._createContainerEntityManagerFactoryHibernatePersistence(HibernatePersistence.java:67) ~[HibernatePersistence.class:4.3.7.Final]
                at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java) ~[HibernatePersistence.class:4.3.7.Final]
                at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:268) ~[LocalContainerEntityManagerFactoryBean.class:3.1.2.RELEASE]
                at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310) ~[AbstractEntityManagerFactoryBean.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294) ~[AbstractBeanFactory$1.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225) ~[DefaultSingletonBeanRegistry.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291) ~[AbstractBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[AbstractBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:424) ~[DefaultListableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:277) ~[BeanFactoryUtils.class:3.1.2.RELEASE]
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:139) ~[PersistenceExceptionTranslationInterceptor.class:3.1.2.RELEASE]
                at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.<init>(PersistenceExceptionTranslationInterceptor.java:79) ~[PersistenceExceptionTranslationInterceptor.class:3.1.2.RELEASE]
                at org.springframework.dao.annotation.PersistenceExceptionTranslationAdvisor.<init>(PersistenceExceptionTranslationAdvisor.java:70) ~[PersistenceExceptionTranslationAdvisor.class:3.1.2.RELEASE]
                at org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor.setBeanFactory(PersistenceExceptionTranslationPostProcessor.java:103) ~[PersistenceExceptionTranslationPostProcessor.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1475) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1443) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519) ~[AbstractAutowireCapableBeanFactory.class:3.1.2.RELEASE]
                ... 55 more

**Comment by edudant** [comment]
This should work in current version. Please reopen if still valid.
