### ISSUE TITLE
WHen using hibernate 3 An error message appears on startup 

### ISSUE THREAD

**Issue by rojan507** [HotswapProjects/HotswapAgent#65]
It would be great if a warning message appear instead of error and start up the application as normal

HOTSWAP AGENT: 16:57:26.997 ERROR (org.hotswap.agent.annotation.handler.OnClassLoadedHandler) - InvocationTargetException in transform method on plugin 'class org.hotswap.agent.plugin.hibernate.HibernatePlugin' class 'org/hibernate/cfg/Configuration'.
java.lang.reflect.InvocationTargetException
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by funsterisdafunniest** [comment]
@rojan507 were you able to deploy a dto with hibernate 3? mine said classnotfoundexception on org.hibernate.version have you encountered this before?

**Comment by rojan507** [comment]
I was able to Deploy it with out error.But not using it now.Could you please send more detailed log?

**Comment by funsterisdafunniest** [comment]
sure, it's over at paste bin <a href="http://pastebin.com/zxyt48G6">http://pastebin.com/zxyt48G6</a>

**Comment by rojan507** [comment]
Not sure...Sorry

**Comment by funsterisdafunniest** [comment]
woops.. i'm dumb. the owner only supported hibernate 4 and that class i mentioned only exists in hibernate 4

**Comment by Julianstouch** [comment]
I have this error, I can add more stack.

With Hibernate 3.6.8 :
Caused by: org.hotswap.agent.javassist.NotFoundException: buildSessionFactory(..) is not found in org.hibernate.cfg.Configuration
at org.hotswap.agent.javassist.CtClassType.getDeclaredMethod(CtClassType.java:1186)
at org.hotswap.agent.plugin.hibernate.HibernateTransformers.proxySessionFactory(HibernateTransformers.java:71)

**Comment by skybber** [comment]
Hibernate 3.x is not supported. Look at #10

**Comment by skybber** [comment]
supported in v0.4

**Comment by funsterisdafunniest** [comment]
@skybber  Thanks!! will try it tomorrow morning when i'm at work.
