### ISSUE TITLE
HotSwapAgent Plugin - ClassNotFound exception from PluginRegistry

### ISSUE THREAD

**Issue by martin-macak** [HotswapProjects/HotswapAgent#67]
I created plugin within my application (running on WLS). When hotswap-agent kicks in, there is an exception when plugin is being loaded by PluginRegistry:
```Exception
####<Feb 9, 2015 12:45:54 AM PST> <Notice> <Stdout> <testbox.mycompany> <AdminServer> <Thread-87> <<WLS Kernel>> <> <> <1423471554463> <BEA-000000> <HOTSWAP AGENT: 0:45:54.463 ERROR (org.hotswap.agent.config.PluginRegistry) - Error in plugin initial processing for plugin package 'mycompany.infrastructure.hotswap.agent'
java.lang.ClassNotFoundException: mycompany.infrastructure.hotswap.agent.HotSwapMyCompanyPlugin
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at org.hotswap.agent.config.PluginRegistry.scanPlugins(PluginRegistry.java:89)
    at org.hotswap.agent.config.PluginConfiguration.initPluginPackage(PluginConfiguration.java:120)
    at org.hotswap.agent.config.PluginConfiguration.init(PluginConfiguration.java:109)
    at org.hotswap.agent.config.PluginConfiguration.<init>(PluginConfiguration.java:97)
    at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:154)
    at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:163)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)>

My hotswap-agent.properties file is configured like this:

```properties
pluginPackages=mycompany.infrastructure.hotswap.agent
autoHotswap=false
LOGGER=info

It seems that hotswap-agent properly identifies config file and tries to load plugin class, which is managed from child classloader. This obviously fails and the exception is thrown.

Tested on WebLogic appserver.

**Comment by skybber** [comment]
Plugin classes must be inside hotspap-agent.jar file.

**Comment by martin-macak** [comment]
The documentation says otherwise:

You can write plugin directly as a part of your application. Set pluginPackages=your.plugin.package inside your hotswap-agent.properties configuration to discover @Plugin annotated classes. You will also need agent JAR dependency to compile, but be careful NOT to add the JAR to your application, it must be loaded only as a javaagent. Maven dependency:

    <dependency>
        <groupId>org.hotswap.agent</groupId>
        <artifactId>HotswapAgent</artifactId>
        <version>${project.version}</version>
        <scope>provided</scope>
    </dependency>
(Note that the JAR is not yet in central maven repository - you need to build it from source first).

See ExamplePlugin (part of TestApplication) to go through a commented simple plugin. Read agent readme to understand agent concepts. Check existing plugins source code for more examples.

Text copied from HotSwapAgent git repo markdown

**Comment by edudant** [comment]
@martin-macak is correct, this should be supported and I use it in several application-specific plugins.

Technically this is solved by ClassLoaderPatcher service. It works in both ways - it duplicates class definition from hotswap-agent.jar into applicaiton classloader AND duplicates classes from pluginPackages into root (agent) classloader).

WLS is not fully supported yet and may be the cause of your problem. Can you try on Tomcat/Jetty?

**Comment by raould** [comment]
hi, is there any update/progress on this issue? I wanted to learn how to write something for SpigotMC after reading that same note that @martin-macak quoted, but then (a) one of the links in there is a 404 and (b) then i google'd up stuff that lead me eventually to here, so i am sad that apparently i can't try the simple way of doing an @Plugin addition?

**Comment by edudant** [comment]
Hi,

please look at [custom plugin documentation](http://hotswapagent.org/mydoc_custom_plugins.html) and [example custom plugin project](https://github.com/HotswapProjects/HotswapAgentExamples/blob/master/custom-plugin/src/main/java/org/hotswap/agent/example/plugin/ExamplePlugin.java). Please let me know if everything works for you.

Jiri
