### ISSUE TITLE
Eclipse Luna SR2 - dcevm, hotswap-agent jar makes Eclipse Tomcat stuck on debug/restart

### ISSUE THREAD

**Issue by krishna81m** [HotswapProjects/HotswapAgent#69]
Deploying my maven multi module project on Eclipse latest Tomcat 7.x instance gets stuck at "Preparing Launch Delegate" or "Starting" for more than 10 minutes otherwise typically completes startup in less than a minute? If I remove -XXaltjvm and -Djava.library.path, everything works fine the very next time and the whole thing repeats once I include these settings second time occassionally. I have used a brand new Eclipse Luna SR2, latest Hotswap + DCEVM release agent as per the documentation for this purpose.

The logs only show the first two lines:
HOTSWAP AGENT: 0:31:51.396 INFO (org.hotswap.agent.HotswapAgent) - Loading Hotswap agent {0.2} - unlimited runtime class redefinition.
HOTSWAP AGENT: 0:31:51.652 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox]

-Dcatalina.base="C:\Work\luna-SR2-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp1" -Dcatalina.home="C:\Work\tools\apache-tomcat-7.0.42" -Dwtp.deploy="C:\Work\luna-SR2-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp1\wtpwebapps" -Djava.endorsed.dirs="C:\Work\tools\apache-tomcat-7.0.42\endorsed"

-XXaltjvm=dcevm -javaagent:C:\Work\tools\hotswap-agent.jar
-Djava.library.path=C:\Work\tools\apache-tomcat-7.0.59\tcnative

**Comment by skybber** [comment]
It can be slower if you have FastDebug DCEVM build. FastDebug is slower. I don't know if official DCEVM release uses PRODUCT(faster) or FastDebug version. You can build dcevm youself, it should help. But there is no significant difference of performance between dcevm / openjdk / oracle VMs.

**Comment by krishna81m** [comment]
My concern as I mentioned above is not being slower, it just hangs way too long "Occasionally" requiring a full build.

**Comment by skybber** [comment]
What is result if you use -XXaltjvm without -javaagent? Is it dcevm issue or hotswap-agent issue?

**Comment by krishna81m** [comment]
Uh oh, didn't try that, will keep you posted by tomorrow.

**Comment by krishna81m** [comment]
So far it has been pretty stable if I remove the agent
-Djavaagent:C:\Work\tools\hotswap-agent.jar

**Comment by erkieh** [comment]
Does it use the cpu in this state?
Can you provide a stacktrace, when it hangs?
You can use the jstack.exe from your java installation. Use the -f flag to force a stacktrace, if it does not give it otherwise.

**Comment by akmusleh** [comment]
I ran into a similar problem. Skipping all the breakpoints and then starting the server in debug mode worked for me.

**Comment by yate** [comment]
Same issue for me, here's the jstack output.

Tomcat: 7.0.63
JDK: 1.7.0.51
Hotswap: 0.3 - stable
DCEVM: DCEVM (light) for Java 8u51 (build 3)
Eclipse: Mars SR1 4.5.1

```
Full thread dump Dynamic Code Evolution 64-Bit Server VM (24.79-b02-dcevmfull-7 mixed mode):

"Attach Listener" daemon prio=10 tid=0x00007f7780001000 nid=0x2e54 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-5" daemon prio=10 tid=0x00007f7768002800 nid=0x2d2e waiting for monitor entry [0x00007f7795b35000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:942)
	- waiting to lock <0x00000000b2501390> (a org.apache.catalina.loader.StandardClassLoader)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:666)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hotswap.agent.javassist.ClassPool.toClass2(ClassPool.java:1082)
	- locked <0x00000000b252c148> (a java.lang.Class for org.hotswap.agent.javassist.ClassPool)
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1067)
	at org.hotswap.agent.javassist.CtClass.toClass(CtClass.java:1265)
	at org.hotswap.agent.util.classloader.ClassLoaderDefineClassPatcher$1.visit(ClassLoaderDefineClassPatcher.java:62)
	at org.hotswap.agent.util.scanner.ClassPathScanner.scanJar(ClassPathScanner.java:116)
	at org.hotswap.agent.util.scanner.ClassPathScanner.scan(ClassPathScanner.java:53)
	at org.hotswap.agent.util.classloader.ClassLoaderDefineClassPatcher.patch(ClassLoaderDefineClassPatcher.java:42)
	at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:150)
	- locked <0x00000000b257fab0> (a org.hotswap.agent.config.PluginManager)
	at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:163)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

"Service Thread" daemon prio=10 tid=0x00007f77a0764800 nid=0x2d29 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007f77a0762000 nid=0x2d28 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007f77a0760000 nid=0x2d27 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Thread-2" daemon prio=10 tid=0x00007f77a01a4800 nid=0x2d20 waiting on condition [0x00007f77962bd000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.hotswap.agent.command.impl.SchedulerImpl$2.run(SchedulerImpl.java:124)

"Thread-1" daemon prio=10 tid=0x00007f77a01a2800 nid=0x2d1f waiting on condition [0x00007f77963be000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000b2501120> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:489)
	at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:678)
	at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)
	at org.hotswap.agent.watch.nio.WatcherNIO2.processEvents(WatcherNIO2.java:180)
	at org.hotswap.agent.watch.nio.WatcherNIO2.access$100(WatcherNIO2.java:32)
	at org.hotswap.agent.watch.nio.WatcherNIO2$2.run(WatcherNIO2.java:272)

"Thread-0" daemon prio=10 tid=0x00007f77a01a0800 nid=0x2d1e runnable [0x00007f77964bf000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.fs.LinuxWatchService.poll(Native Method)
	at sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47)
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:311)
	at java.lang.Thread.run(Thread.java:744)

"JDWP Command Reader" daemon prio=10 tid=0x00007f7784001000 nid=0x2d18 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Event Helper Thread" daemon prio=10 tid=0x00007f77a00bf000 nid=0x2d17 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"JDWP Transport Listener: dt_socket" daemon prio=10 tid=0x00007f77a00bb000 nid=0x2d15 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007f77a00a6000 nid=0x2d13 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007f77a008f800 nid=0x2d12 in Object.wait() [0x00007f779706c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000b2501280> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000000b2501280> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:189)

"Reference Handler" daemon prio=10 tid=0x00007f77a008e000 nid=0x2d11 in Object.wait() [0x00007f779716d000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000b25012b0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x00000000b25012b0> (a java.lang.ref.Reference$Lock)

"main" prio=10 tid=0x00007f77a000c800 nid=0x2d0b waiting for monitor entry [0x00007f77a5929000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:145)
	- waiting to lock <0x00000000b257fab0> (a org.hotswap.agent.config.PluginManager)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:106)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	- locked <0x00000000b2501390> (a org.apache.catalina.loader.StandardClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1282)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1342)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1555)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:615)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:280)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:454)

"VM Thread" prio=10 tid=0x00007f77a0089800 nid=0x2d10 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007f77a0770000 nid=0x2d2a waiting on condition 

JNI global references: 1815


Found one Java-level deadlock:
=============================
"Thread-5":
  waiting to lock monitor 0x00007f7788003cf8 (object 0x00000000b2501390, a org.apache.catalina.loader.StandardClassLoader),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007f7788003988 (object 0x00000000b257fab0, a org.hotswap.agent.config.PluginManager),
  which is held by "Thread-5"

Java stack information for the threads listed above:
===================================================
"Thread-5":
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:942)
	- waiting to lock <0x00000000b2501390> (a org.apache.catalina.loader.StandardClassLoader)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:666)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:794)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hotswap.agent.javassist.ClassPool.toClass2(ClassPool.java:1082)
	- locked <0x00000000b252c148> (a java.lang.Class for org.hotswap.agent.javassist.ClassPool)
	at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1067)
	at org.hotswap.agent.javassist.CtClass.toClass(CtClass.java:1265)
	at org.hotswap.agent.util.classloader.ClassLoaderDefineClassPatcher$1.visit(ClassLoaderDefineClassPatcher.java:62)
	at org.hotswap.agent.util.scanner.ClassPathScanner.scanJar(ClassPathScanner.java:116)
	at org.hotswap.agent.util.scanner.ClassPathScanner.scan(ClassPathScanner.java:53)
	at org.hotswap.agent.util.classloader.ClassLoaderDefineClassPatcher.patch(ClassLoaderDefineClassPatcher.java:42)
	at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:150)
	- locked <0x00000000b257fab0> (a org.hotswap.agent.config.PluginManager)
	at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:163)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
"main":
	at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:145)
	- waiting to lock <0x00000000b257fab0> (a org.hotswap.agent.config.PluginManager)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler.transform(OnClassLoadedHandler.java:106)
	at org.hotswap.agent.annotation.handler.OnClassLoadedHandler$1.transform(OnClassLoadedHandler.java:76)
	at org.hotswap.agent.util.HotswapTransformer.transform(HotswapTransformer.java:129)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:424)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	- locked <0x00000000b2501390> (a org.apache.catalina.loader.StandardClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.apache.tomcat.util.digester.ObjectCreateRule.begin(ObjectCreateRule.java:144)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1282)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1342)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1555)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:615)
	at org.apache.catalina.startup.Catalina.load(Catalina.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:280)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:454)

Found 1 deadlock.
```

**Comment by skybber** [comment]
Check if your JDK match with DCEVM versions, you should have 
DCEVM: DCEVM (light) for Java 8u51 (build 3)
in JDK: 1.8.0.51 (not JDK: 1.7.0.51)

**Comment by yate** [comment]
Sorry I put in the wrong dcevm version, I do have DCEVM (light) for Java 7u51 (build 10) and jdk 1.7.0.51

**Comment by vra5107** [comment]
I have the same problem. I have tried various versions of **Hotswapagent**. The server starts only when I use **hotswap-agent-core-1.3.0.jar**. If I add **hotswap-agent-1.3.0.jar** to arguments it just hangs forever. None of the others work. (1.0, 1.10-SNAPSHOT, 1.2.0, 1.2.1-SNAPSHOT. 1.3.0).

Using 
Eclipse Oxygen
Tomcat 7.0.53

How do I enable trace logging to find out more ?
