### ISSUE TITLE
Please provide a headless installer

### ISSUE THREAD

**Issue by KIC** [HotswapProjects/HotswapAgent#72]
In our team no one is running services like tomcat, wildfly, etc. locally. Instead we all use predifined docker images. Sadly it seems not to be possible to install the installer-light-*.jar from a Dockerfile. But it would be a great thing if you could simply provide a command line only version.

<pre>
root@3b6f20649f05:/data# java -jar installer-light-jdk8u5.52.jar 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at com.github.dcevm.installer.MainWindow.<init>(MainWindow.java:43)
	at com.github.dcevm.installer.Main.main(Main.java:46)
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at com.github.dcevm.installer.Main.main(Main.java:51)
</pre>

**Comment by skybber** [comment]
It is DCEVM issue. Please put it to DCEVM's  issues. 
Btw, the installer copies lib file (libjvm.so) to dcevm directory (in my case /usr/lib/jvm/default/jre/lib/amd64/dcevm) You can do the same in a script using unzip. The lib file is in the jar, or I would recommend to build your own libdcevm.so

**Comment by KIC** [comment]
Dcevm has "issues" not enabled. But thanks for the hint copying the .so file. Such a simple task realy needs a gui? :-)

**Comment by KIC** [comment]
Ahh sorry i have just seen this dcevm is just a fork. Yes i will put the issue there. Thx!

**Comment by KIC** [comment]
Thx you were right, simply compile from source and replace the /usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so

From Dockerfile:
<pre>
# add dcevm
ADD libjvm.so /usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so
RUN java -version
</pre>

PS If you compile the dcevm from src you will be able to use Java 8 update 40 Build 25!

**Comment by skybber** [comment]
Yes, and the last version also include the deopt flag, that makes hotswap event faster!
https://groups.google.com/forum/#!topic/hotswapagent/GhTrJ6eCqLQ
