### ISSUE TITLE
Plugin not found in the registry 

### ISSUE THREAD

**Issue by workmonitored** [HotswapProjects/HotswapAgent#87]
I have downloaded the github source and built hotswap agent. I am getting a plugin not found in registry with tomcat. It's specifically the jsfplugin. 

Two questions:
1) What could be the possible cause ?
2) How can I debug it? I have looked at the jsf plugin and there are no errors that I can see during build stage.

Stack trace.. This is tomcat 7.0.63 with jsf faces 2.1.23 api
HOTSWAP AGENT: 9:21:55.183 INFO (org.hotswap.agent.config.PluginRegistry) - Discovered plugins: [Hotswapper, AnonymousClassPatch, WatchResources, Hibernate, Spring, Jersey2, Jetty, Tomcat, ZK, Logback, JSF, Seam, ELResolver, OsgiEquinox, Proxy, WebObjects, Weld]
Listening for transport dt_shmem at address: tomcat_shared_memory_id

Jul 17, 2015 9:21:59 AM com.sun.faces.config.ConfigureListener contextInitialized
INFO: Initializing Mojarra 2.1.23 ( 20130613-1525 https://svn.java.net/svn/mojarra~svn/tags/2.1.23@11994) for context '/manager'
Jul 17, 2015 9:21:59 AM com.sun.faces.spi.InjectionProviderFactory createInstance
INFO: JSF1048: PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked with these annotations will have said annotations processed.
Jul 17, 2015 9:21:59 AM com.sun.faces.spi.InjectionProviderFactory createInstance
INFO: JSF1048: PostConstruct/PreDestroy annotations present.  ManagedBeans methods marked with these annotations will have said annotations processed.
Jul 17, 2015 9:21:59 AM com.sun.faces.config.ConfigureListener contextInitialized
SEVERE: Critical error during deployment: 
java.lang.IllegalArgumentException: Plugin not found in the registry org.hotswap.agent.plugin.jsf.JsfPlugin@57997f63
	at org.hotswap.agent.config.PluginRegistry.getAppClassLoader(PluginRegistry.java:235)
	at org.hotswap.agent.annotation.handler.InitHandler.initField(InitHandler.java:42)
	at org.hotswap.agent.annotation.handler.AnnotationProcessor.processFieldAnnotations(AnnotationProcessor.java:118)
	at org.hotswap.agent.annotation.handler.AnnotationProcessor.processAnnotations(AnnotationProcessor.java:95)
	at org.hotswap.agent.config.PluginRegistry.initializePlugin(PluginRegistry.java:158)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:387)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:216)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5015)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5531)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)

**Comment by workmonitored** [comment]
This has not happened., The issue was tomcat multiple thread loading being enabled.. 


      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true" startStopThreads="3">

changed startStopThreads to 1
