### ISSUE TITLE
Problem with spring 4.2.0.RELEASE

### ISSUE THREAD

**Issue by ravshansbox** [HotswapProjects/HotswapAgent#90]
Problem with spring 4.2.0.RELEASE:

java.lang.NoSuchFieldException: handlerMethods

**Comment by The-Alchemist** [comment]
Do you have a stack trace we could look at?

**Comment by ravshansbox** [comment]
java.lang.NoSuchFieldException: handlerMethods
	at java.lang.Class.getDeclaredField(Class.java:1953)
	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:44)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)

**Comment by The-Alchemist** [comment]
Looks like sometime recently in the Spring Web world, stuff got moved around:
* ``handlerMethods`` is in  ``HandlerMethodResolver``
* ``urlMap`` is in ``SimpleUrlHandlerMapping``

I'm not sure if the usage of those fields inside Spring is the same.

**Comment by ravshansbox** [comment]
Yes, and I was sure something serious changed inside Spring 4.2.0.RELEASE, because spring-loaded was also unable to reload and reporting same message about handleMethods.

**Comment by skybber** [comment]
Could you please supply an example?

**Comment by arey** [comment]
I've got the same issue with Spring 4.2.5
```
HOTSWAP AGENT: 8:42:34.743 ERROR (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Failed to clear HandlerMappings
java.lang.NoSuchFieldException: handlerMethods
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:44)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
````
You may reproduce this issue with the Spring Petclinic sample application: https://github.com/spring-projects/spring-petclinic/

**Comment by jfmenard** [comment]
Still having the same issue with Spring 4.2.6

```
HOTSWAP AGENT: 23:44:53.175 INFO (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Spring: clearing HandlerMapping for class org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
HOTSWAP AGENT: 23:44:53.175 ERROR (org.hotswap.agent.plugin.spring.ResetRequestMappingCaches) - Failed to clear HandlerMappings
java.lang.NoSuchFieldException: handlerMethods
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.hotswap.agent.plugin.spring.ResetRequestMappingCaches.reset(ResetRequestMappingCaches.java:44)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.defineBean(ClassPathBeanDefinitionScannerAgent.java:169)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanDefinitionScannerAgent.refreshClass(ClassPathBeanDefinitionScannerAgent.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.spring.scanner.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:74)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
```

**Comment by msalman86** [comment]
I have created a PR with a fix
