### ISSUE TITLE
Wield exception

### ISSUE THREAD

**Issue by flyasky** [HotswapProjects/HotswapAgent#95]
JDK 1.7.0_79 with 
swap-agent.jar v.0.3
and DCEVM (full) for Java 7u79 (build 7)

Run Weblogic 12.1.3 with ear + war

Eclipse 4.5 (Mars)

Have this error in console after save java file.
Breakpoint in debugger and tracing seems like code was replaced, but why I see exception?

HOTSWAP AGENT: 10:47:56.754 WARNING (org.hotswap.agent.plugin.weld.WeldPlugin) - classReload() exception : c.b.s.r.s.w.i18n.LocaleRetriever
HOTSWAP AGENT: 10:47:56.769 WARNING (org.hotswap.agent.plugin.weld.WeldPlugin) - classReload() exception : c.b.s.r.s.w.i18n.LocaleRetriever$Proxy$_$$_WeldClientProxy
Exception in thread "Thread-62" java.lang.NoClassDefFoundError: org/jboss/weld/environment/deployment/WeldBeanDeploymentArchive
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getDeclaredMethod(Class.java:2007)
	at org.hotswap.agent.plugin.weld.command.ClassPathBeanRefreshCommand.executeCommand(ClassPathBeanRefreshCommand.java:66)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.ClassNotFoundException: org.jboss.weld.environment.deployment.WeldBeanDeploymentArchive
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 5 more

**Comment by skybber** [comment]
This exception  is related to Weld plugin, it looks that there is some problem on Weblogic. You can disable Weld plugin in hotswap-agent.properties until this problem is fixed. Weld/CDI plugin solves CDI's injection reloading, so that you should restart if you make some changes in injections.

**Comment by D3athNaM** [comment]
same exception with same scenario, just the weblogic server is 12.1.2.

**Comment by skybber** [comment]
Could you specify the Weld version?
